### ISSUE TITLE
Login mit Captcha wird nicht validiert

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#100]
ist immer gültig. 
Liegt es an yform oder ycom? Ist mir nicht ganz klar. 

Mache ich was falsch?

> objparams|form_skin|bootstrap
> objparams|form_class|hide-label
> 
> ycom_auth_form_info||Bitte einloggen|Benutzer wurde ausgeloggt|Login ist fehlgeschlagen|Benutzer wurde erfolgreich eingeloggt|
> 
> ycom_auth_form_login|login|Benutzername|#placeholder:Benutzername
> ycom_auth_form_password|passwort|Passwort|#placeholder:Passwort
> captcha|Sicherheitscode|Der Sicherheitscode wurde falsch eingegeben
> validate|empty|login|Bitte geben Sie Ihren Benutzernamen ein. 
> validate|empty|passwort|Bitte Passwort eingeben
> 
> submit|label|Abschicken|no_db|btn btn-danger btn-block

**Comment by dergel** [comment]
dasliegt daran, dass das login von ycom nicht über das formular geprüft wird, sondern über Extension Point davor.. ein Captcha mit Login ist so quasi gar nicht möglich

**Comment by skerbis** [comment]
Hast du einen alternativen Vorschlag?

**Comment by dergel** [comment]
bin mir gereade unsicher, aber ich glaube es gibt bei der ycom auch eine validate klasse mit der man sich einloggen kann, und dann würde auch das captcha validate greifen (habe leider gerade keine zeit das zu prüfen)

**Comment by skerbis** [comment]
Wenn Du Zeit hast bitte. Das wäre eine große Hilfe.

**Comment by dergel** [comment]
Bitte per Skype oder REDAXO Slack
