### ISSUE TITLE
User-Sperre nach X Login-Versuchen

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#101]
Wäre sehr nützlich

**Comment by ceekay82** [comment]
Als Feature: E-Mail-Benachrichtigung an alle Admins oder die Adresse, die unter System hinterlegt ist.

**Comment by skerbis** [comment]
Alternative: ycom schreibt ins Server-Log. Dann könnte mit fail2ban gesperrt werden.

**Comment by dergel** [comment]
ohne benachrichtigung ist es nun eingebaut, danke @skerbis dafür ..
