### ISSUE TITLE
Backend: Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by tyrant88** [yakamara/redaxo_ycom#102]
Warning: Invalid argument supplied for foreach() in /var/www/dev5/redaxo/src/addons/ycom/boot.php on line 14

passiert wenn noch keine Tabellen angelegt sind mit dem yform manager.

**Comment by skerbis** [comment]
Passiert auch, wenn Tabellen angelegt sind. 

> Warning	Invalid argument supplied for foreach()	
> redaxo/src/addons/ycom/boot.php

**Comment by dergel** [comment]
ist behoben..
