### ISSUE TITLE
Feature-Wunsch :: Sitemap im Backend

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#105]
Eine Sitemap im Backend, die hilft einen Überblick über die vergebenen Kategorie- und Artikelrechte zu erhalten.

**Comment by dergel** [comment]
das wäre ein ziemliches Monster, weil es ja zu jeder Seite verschiedene Rechte gibt. Wir selbst benutzen manchmal sogar noch Kriterien, die man in dieser Sitemap gar nicht sehen würde, wie z.B. IP Adresse oder ähnliches .. deswegen leider nein. (Hätte ich aber auch mal früher antworten können) ;) ..
