### ISSUE TITLE
Error Installation mit YForm Version 2.0

### ISSUE THREAD

**Issue by paddle07** [yakamara/redaxo_ycom#106]
Das ycom Addon lässt sich nicht mit der neusten Version (2.0) von YForm installieren (getFields() error). Habe es solange mit der YForm Version 1.0 installiert.

**Comment by darwin26** [comment]
Hi,
hab das gerade auch mit einer blanken R5 getestet.
yCom lässt sich nicht mehr installieren:

redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php on line 183
Call to a member function getFields() on null

**Comment by joachimdoerr** [comment]
Kann ich bestätigen.

**Comment by darwin26** [comment]
wie  paddle07 - schon beschrieben...
yForm1.0 und yCom1.0 - funktionieren....

**Comment by NGWNGW** [comment]
Selbes Problem hier... 
Ich habe ein eigenes AddOn programmiert, welches - ähnlich wie ycom -, eine yForm Tabelle beim Installieren anlegen soll. Ich vermute, dass der Fehler eher in diesem AddOn als bei yCom vorhanden ist.

**Comment by psgehe** [comment]
Selbes Problem. Sowohl lokal als auch online. yForm V 2.0, yCom1.0

**Comment by dergel** [comment]
mittlerweile behoben.. yform 2.2
