### ISSUE TITLE
Installationssequenz unsauber

### ISSUE THREAD

**Issue by gupi** [yakamara/redaxo_ycom#107]
der 1. Installationsversuch wurde mit einemHinweis auf fehlende Resourcen (Addons) beendet.
Dabei wurde aber bereits die rex_yform_table aktualisiert und rex_ycom_user eingetragen.
Dieser Eintrag führt aber bei dem nächsten Installationsversuch von ycom zu einer Fehlermeldung wegen eines doppelten Eintrags.

**Comment by dergel** [comment]
das sollte seit yform 2.1 behoben sein..
