### ISSUE TITLE
Redaxo Community Rechte Verwaltung

### ISSUE THREAD

**Issue by Martihap** [yakamara/redaxo_ycom#108]
Guten Abend zusammen,
> ich benutzte Ihr CMS Redaxo und habe eine Frage.
>
> Kurze Erklärung zu meinem Projekt:
> Ich erstelle eine Seite für 16 Löschgruppen der Feuerwehr und muss verschiedene Berechtigungen erstellen.
> Ich habe das Community Add on ycom installiert und möchte verschiedene Rollen erstellen.
> Leider ist es nicht möglich den Rollen den Zugriff auf das Community Add on unter Strukturen zu entziehen.
>
> Das Bedeutet: User X hat Zugriff auf eine Sturktur und erstellt eine Kategorie. In der Unterkategorien kann der User X
> verschiedene Communityrechte vergeben. Die Sichtbarkeit für eingeloggte und nicht eingeloggte User kann er verändern.
>
> Lösung: Man müsste unter Rollen->Rollen bearbeiten->Rolle X->keine Communityvergabe einstellen können
> Andere Add ons wie Event_Cal bieten soetwas an
> Vielen Dank und eine schöne Woche noch
>
> Martin Happe

**Comment by dergel** [comment]
ist lange her .. aber die idee ist gut ..
