### ISSUE TITLE
Session Gültigkeitsdauer

### ISSUE THREAD

**Issue by christophevouillamoz** [yakamara/redaxo_ycom#109]
Wenn ich mich mittels dem ycom auth plugin einlogge und das Cookie über den Chrome Einstellungen anschaue dann steht bei "Läuft ab" **Beim Beenden der Browsersitzung**. In der plugins/auth/lib/ycom_auth.php Datei wird in der Zeile 133 das Cookie gesetzt anhand folgendem Code:

`setcookie(self::getLoginKey(), $session_key, time() + (3600 * 24 * rex_addon::get('ycom')->getConfig('cookie_ttl')), "/" );`

Daraus lese ich die Config **cookie_ttl**, welche ich aber sonst nirgends vorfinde. Gibt es eine Möglichkeit die Ablaufzeit anzupassen ohne das Plugin zu beinträchtigen, sprich den Code hier zu ändern?

**Comment by dergel** [comment]
Leider nur, wenn du es direkt dort anpasst. Ich prüfe das und wird beim nächsten Update besser laufen. Es etehen sowieso ein paar Änderungen an, kommt dann "in der nächsten Zeit" ..

**Comment by dergel** [comment]
das ist bereits angepasst. war in der config noch falsch gepspeichert
