### ISSUE TITLE
Installation die zweite

### ISSUE THREAD

**Issue by Kalle01** [yakamara/redaxo_ycom#110]
Basis ist die Com Demo mit YForm 2.0!
Folgende Fehlermeldung:
"ErrorException" thrown in /kunden/252992_40822/webseiten/CMS-LH-Rex-5-2-comunity/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php on line 183
Fatal error: Call to a member function getFields() on null

activate safe mode

Wenn man den Safe Mode aktiviert ist ycom nicht installiert ein erneuter Installationsversuch führt zu

AddOn ycom konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement using params {"table_name":"rex_ycom_user","status":"1","name":"translate:ycom_user","description":"","list_amount":"100","list_sortfield":"login","list_sortorder":"DESC","prio":"1","search":"0","hidden":"0","export":"1","import":"1"}! SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'rex_ycom_user' for key 'table_name'

Für mich nicht lösbar

Gruß Kalle

**Comment by Goldfischpeter** [comment]
Nach diesem Fehler kann man das so zum laufen bringen:
- YFORM: alle Plugins deinstallieren
- YFORM 2.0 löschen
- YFORM 1.0 installieren
- YCOM installieren
- YFORM 2.0 aktualisieren

**Comment by dergel** [comment]
hehe.. das sollte nicht der weg sein ;) .. aber die aktualisierte YForm, kommt in dieser oder in der nächsten Woche (v2.1), wird den fehler beheben.
