### ISSUE TITLE
Wünsche: LDAP 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#111]
- Eine LDAP-Anbindung für die User / Gruppen wäre super (Bitte melden) @dergel 
- editiert -

**Comment by dergel** [comment]
zwei verschiedene Dinge.. Die Rechte über eine Baumstruktur fände ich auch gut.
ldap . kommt darauf an wie .. machst du für die baumstruktur ein neues issue auf ?

**Comment by skerbis** [comment]
https://github.com/yakamara/redaxo_ycom/issues/112

**Comment by dergel** [comment]
ldap werde ich nicht native reinnehmen. Finde keinen pauschalen sinnvollen Weg.
