### ISSUE TITLE
Pflege der Rechte über Baumstruktur

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#112]
Die Pflege der Rechte wäre einfacher und übersichtlicher über eine Baumstruktur, evtl. bietet sich da das AddOn Treestructure dafür an.

**Comment by tbaddade** [comment]
> bietet sich da das AddOn Treestructure dafür an

@skerbis Hast du einen Link?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/treestructure

**Comment by dergel** [comment]
gab irgendwo anders auch schon ein ähnliches issue.. das problem ist, dass die rechte nicht auf user begrenzt sein müssen. da diese erweitert werden können, kann man durch eine kategoriezuweiseung auch nicht garantieren, dass dieser user dann darauf zugriff hat. deswegen würde ich das issue nicht umsetzen wollen.. sorry.
