### ISSUE TITLE
Alternative User Tabelle wählen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#113]
Aktuell scheint  die `rex_ycom_user` fest vorgegeben zu sein.

**Comment by Hirbod** [comment]
Oh, hatte ich auch in Slack gemeldet. +1 dazu

**Comment by alexplusde** [comment]
+1 bräuchten wir gerade auch. Ich weiß noch nicht, wie ich es löse, evtl. kommt hierzu ein PR. (Hilfe willkommen)

**Comment by alexplusde** [comment]
Ist das nach wie vor gewünscht? (Wir haben es inzwischen anders gelöst)

**Comment by dergel** [comment]
weiss nicht .. finde das eher hinderlich. nur die Tabelle entsprechend zu ändern reicht nicht .. es gibt sehr viele Feldabhängigkeiten, die dann auch entsprechend aufgelöst werden müssen.
