### ISSUE TITLE
User Tabelle wird nicht gefunden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#114]
https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/action/ycom_auth_db.php#L28

`rex::getTable('ycom_user')` oder `rex_ycom_user::query->getTable()`

**Comment by gharlan** [comment]
Neuerdings (seit eben) ginge nun auch `rex_ycom_user::table()`.

**Comment by dergel** [comment]
sollte mittlerweile passen...
