### ISSUE TITLE
Template ycom_auth_form_info.php anlegen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#117]
Durch diesen Commit 583daf2555bb0743e518fb9e477e02635153051b wird das Template nicht gefunden. Ich ging fälschlicherweise davon aus, dass die Templates generell optional sein können. Das gilt aber scheinbar nur, wenn man mehrere Templates zum parsen notiert und alle außer das zuletzt notierte optional sein dürfen.

**Comment by dergel** [comment]
sollte mittlerweile wieder passen..auch bei classic
