### ISSUE TITLE
Feature Request LinkedIn Authentifizierung/Anmeldung

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#118]

**Comment by alexplusde** [comment]
Könnte man abstrahieren, auch für facebook/Google nutzen + für die Anmeldung im Redaxo Backend ermöglichen?

**Comment by dergel** [comment]
ja .. :)

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/issues/240
