### ISSUE TITLE
Query: SELECT * from rex_article WHERE id = 1 and clang_id = 1

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#120]
Hallo,

bei installiertem Auth Plugin wird in der Strukturansicht das ausgegeben:

```Query: SELECT * from rex_article WHERE id = 1 and clang_id = 1```

Ich weiß, dass es nix _schlimmes_ ist und Ihr das kennt und es bei der nächsten Version wieder verschwindet. Nur. Wo kann ich es bis dahin abstellen. Finde es gerade nicht :-(.

LG
Oliver

**Comment by staabm** [comment]
ich glaube das wurde bereits in https://github.com/yakamara/redaxo_ycom/commit/7be7ab7a84aed328497744889ef06b4407004191 behoben, nur noch kein neues release seitdem

**Comment by olien** [comment]
Danke. Die Info hatte ich gesucht!

LG
Oliver
