### ISSUE TITLE
Fehler nach löschen eines Feldes

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#121]
```
Error while executing statement "ALTER TABLE `rex_ycom_user` ADD `activation_key` varchar(255) NOT NULL"! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activation_key'
```

Passierte in der Instanz der neuen Website.

**Comment by skerbis** [comment]
Auch hier, bei jeder Aktion im Tablemanager


`Error while executing statement "ALTER TABLE `rex_ycom_user` ADD `activation_key` varchar(255) NOT NULL"! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activation_key'
#0 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php(615): rex_sql->setQuery('ALTER TABLE `re...')
#1 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(1655): rex_yform_manager_table_api::generateTablesAndFields(false)
#2 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(1284): rex_yform_manager->generateAll()
#3 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/addons/yform/plugins/manager/pages/table_field.php(21): rex_yform_manager->getFieldPage()
#4 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/addons/yform/pages/index.php(3): include('/var/www/vhosts...')
#5 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/core/lib/packages/package.php(228): include('/var/www/vhosts...')
#6 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/index.php', Array)
#7 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/var/www/vhosts...')
#8 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/core/backend.php(138): rex_be_controller::includeCurrentPage()
#9 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/src/core/boot.php(107): require('/var/www/vhosts...')
#10 /var/www/vhosts/diedomain.tldhttpdocs/redaxo/index.php(9): require('/var/www/vhosts...')
#11 {main}`

**Comment by andreaswillkens** [comment]
Wird der Fehler bald behoben? Oder soll ich die aktuelle Github-Version laden?

**Comment by dergel** [comment]
eigentlich sollte der fehler mit der aktuellen YForm behoben sein.. wenn nicht - bitte das issue auf reopen oder neu

**Comment by loesungsmittel** [comment]
Der Fehler tritt hier in der 2.1b2 noch immer auf. Ich wollte das AddOn neu installieren, dann erschien die Fehlermeldung. Das Löschen des Feldes bringt nichts. Es wird neu erstellt und die Meldung kommt.

Redaxo Version 5.3
yform | 2.3b2
