### ISSUE TITLE
rex_ycom_auth verwendet falschen Konfig-Schlüssel

### ISSUE THREAD

**Issue by tgoellner** [yakamara/redaxo_ycom#125]
Die Klasse `rex_ycom_auth` in `addons/ycom/plugins/auth/lib/yvom_auth.php` verwendet einen falschen Konfig-Schlüssel. Dort werden die Einstellungen über

`rex_addon::get('ycom')->getConfig()`

abgefragt, aber erst wenn das zu

`rex_addon::get('ycom')->getPlugin('auth')->getConfig()`

geändert wird, funktioniert das Addon.

In der Datenbank lautet der Schlüssel auch nicht `ycom` sondern `ycom/auth`.

**Comment by dergel** [comment]
wurde vom thomas hier gelöst. vielen dank dennoch
https://github.com/yakamara/redaxo_ycom/commit/d8e8ae1ff6f1d742961f3abfc3a207660a2b57d2
