### ISSUE TITLE
be_manager_relation führt postAction IMMER aus

### ISSUE THREAD

**Issue by tgoellner** [yakamara/redaxo_ycom#127]
...dadurch werden Zuordnungen des aktuellen NUtzers immer entfernt, wenn dieser sich einloggt.

**Comment by dergel** [comment]
leider blicke ich da nicht durch.. es sind einige sachen mehr in dem fork deren zusammenhaenge ich nicht verstehe. Ansonsten ist das hier natürlich ein wichtiges Thema..

**Comment by tgoellner** [comment]
Ich seh grad, dass das hier im falschen Repository angelegt wurde. Ich hab's zu [YForm](https://github.com/yakamara/redaxo_yform/issues/326) geschoben.
