### ISSUE TITLE
Authentifizierung.. Weiterleitungen

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#128]
Zumindest die Weiterleitung bei "wenn erfolgreich eingeloggt" funktioniert nicht.. (In der Demo).

**Comment by olien** [comment]
https://redaxo.org/forum/allgemeines-r5-f39/weiterleitung-auf-pages-nach-authentifizierung-t21769.html?sid=63bd9ab59dcab6dc55f7bbca5dc9e01f

**Comment by dergel** [comment]
das sollt mir der korrektur vom thomas erledigt sein

https://github.com/yakamara/redaxo_ycom/commit/d8e8ae1ff6f1d742961f3abfc3a207660a2b57d2
