### ISSUE TITLE
Login - SQL-Exception

### ISSUE THREAD

**Issue by psgehe** [yakamara/redaxo_ycom#129]
Habe unter lokal mit xampp Redaxo 5.3.0 (PHP 7.0.3) YFORM. YREWRITE und YCOM am laufen. Über das Registrierungsformular (welche problemlos funktioniert) habe ich einen neuen User angelegt. Wenn ich mich anschließend einloggen will kommt folgende Fehlermeldung:

> Error while executing statement using params {"p1":"Hier kommt dann die E-Mail-Adresse hinein"}! SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause'

Woran kann das liegen? Ich habe mich beim Login-Formular direkt an die Orginalvorlage in der Anleitung gehalten. Der User ist auf aktiv (händisch im Backend geändert), die AUTH ist auch aktiviert und es ist auch ein Artikel hinterlegt auf den nach Login weitergeleitet wird.

Cache habe ich auch mehrmals im Backend geleert...

Über jede Hilfe bin ich dankbar.

**Comment by staabm** [comment]
hast du im system log geschaut ob dort mehr infos drinnen stehen zu dem fehlgeschlagenen sql query?

**Comment by psgehe** [comment]
Hallo,

ja das habe ich, exakt die gleiche Fehlermeldung.

**Comment by staabm** [comment]
d.h. dort sieht man auch nicht das statement selbst?

**Comment by psgehe** [comment]
Hier ist nur der Pfad zur entsprechenden Datei verlinkt welche den Fehler verursacht bzw. ausgibt

> redaxo\src\core\lib\sql\sql.php

>   throw new rex_sql_exception('Error while executing statement using params ' . json_encode($params) . '! ' . $e->getMessage(), $e);

Mehr steht hier leider nicht dabei

**Comment by paddle07** [comment]
Hi, habe genau das gleiche Problem... Redaxo 5.3, ycom 2.0, yform 2.2, PHP 5.6.3 ...

**Comment by paddle07** [comment]
Habe mal einen Test gemacht... wenn ich Redaxo 5.2 mit ycom 1.0 und yform 2.2 installiere funktioniert es. Auch wenn ich den Core anschliessend via Installer auf 5.3 update und ycom auf 2.0 klappt alles wunderbar. Wenn ich jedoch Redaxo 5.3 direkt installiere (mit ycom 2.0 und yform 2.2) kommt die sql_exception... sieht aus, als ob das login-Feld aus den Einstellungen dann nicht übergeben wird.

**Comment by Hirbod** [comment]
Ich hab ebenfalls das Problem.. hatte gehofft es hat bereits jemand gefixed. Gibt es hier schon eine Lösung?

**Comment by Hirbod** [comment]
Ok, es gibt eine Lösung: Dieser PR fixed das Problem:
https://github.com/yakamara/redaxo_ycom/pull/126

Es wird einfach nicht das richtige Feld übergeben..

**Comment by psgehe** [comment]
Vielen Dank Hirbod für den Hinweis. 
Ich habe einfach die ycom_auth.php mit der aktuellen von hier ersetzt und der Login funktioniert wieder.

**Comment by eaCe** [comment]
Hi, habe das gleiche Problem mit yCom  2.1b... habe die Datei schon ersetzt und cache geleert, auth reinstalliert... gibt es hier noch irgend eine weitere Sache die ich machen muss?

**Comment by eaCe** [comment]
Ich muss nun auch ein Login bauen und bekomme mit der selben ycom_auth den selben Fehler. Gibt es hier noch andere möglichkeiten?
