### ISSUE TITLE
label Tag wird ersetzt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#130]
Eingabe:

`objparams|real_field_names|1`
`ycom_auth_form_login|label|Benutzername:`

Ausgabe:
```
<rex_ycom_auth_name class="control-rex_ycom_auth_name" for="yform-formular-field-5">Benutzername:</rex_ycom_auth_name>
```

passiert hier:
https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/value/ycom_auth_form_login.php#L21

**Comment by tbaddade** [comment]
Betrifft auch das Passwort Value
https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/value/ycom_auth_form_password.php#L8

Eingabe:
`objparams|real_field_names|1`
`ycom_auth_form_password|password|Passwort:`

Ausgabe: (siehe type)
```
<input class="form-control" name="rex_ycom_auth_psw" type="ycom_auth_form_password" id="yform-formular-field-6" value="">
```

**Comment by dergel** [comment]
musste dochwieder rein -- als info .- je nach situation ob class oder bootstrap und ob real_names oder nicht gibt es verschiedene feldnamen und verschiedene feldtype (login, password, text .. ) .. deswegen muss immer dann das feld eingetragen werden mit dem festen namen. ist aber nun geprüft und fehler sind behoben

**Comment by tbaddade** [comment]
Wäre sinnvoller das classic zu entfernen.

**Comment by dergel** [comment]
noch nicht .. es geht auch eher um das prinzip, dass man eigene views einbauen können.
