### ISSUE TITLE
yform Formulare werden direkt versendet, wenn man via ycom im FE eingeloggt ist

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#132]
Ist man per ycom im FE eingeloggt und öffnet eine Seite mit einem yform-Formular, wird dieses direkt versendet. 
Das Formular erhält irgendwoher (von ycom?) einen "send"-Parameter der true/1 ist. Dies führt dazu, dass direkt die Validierung oder action des Formulars ausgeführt wird.
Das passiert allerdings nur, wenn im Formular objparams|real_field_names|true gesetzt ist.
Getestet auch mit der Community-Demo.

Fragen bitte an @sbrinkers im Slack

**Comment by xong** [comment]
Ich kann den Fehler bestätigen. Hat mir viel Kopfzerbrechen bereitet.
Problem ist die Methode [`rex_yform_manager_dataset::save()`](https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/manager/dataset.php#L443). Dort wird in Zeile 462 der Parameter `send` gesetzt, der dafür sorgt, das nachfolgende Formulare sofort abgeschickt werden, wenn `real_field_names` aktiviert ist.
Der Aufruf erfolgt u. a. in [Zeile 163](https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/ycom_auth.php#L163) der Methode `rex_ycom_auth::login()`.

**Comment by dergel** [comment]
Danke fürs melden .. werden wir korrigieren.

**Comment by javanita** [comment]
Ist schon eine Lösung in Sicht?

**Comment by xong** [comment]
@javanita Die einzige Lösung besteht im Moment darin, `real_field_names` nicht zu verwenden, wenn du mit dem Community-Addon arbeitest.

**Comment by dergel** [comment]
Im Moment ist das leider wirklich die einzige Lösung .. Wir sind dran .. ist ein YForm Problem

**Comment by alexplusde** [comment]
In Slack wird das z.Z. immer wieder berichtet.

**Comment by tyrant88** [comment]
Hab ich mich vor 2 Wochen mit rumgeärgert. Ich sollte öfters nach issues sehen ;-)

**Comment by gharlan** [comment]
Kann jemand testen, ob das Problem hiermit erstmal gelöst ist?
https://github.com/yakamara/redaxo_yform/commit/d57e84d954f0eb7c6a2c57f2e874cea0ab77d037

(Wir müssen den Part in YForm allgemein irgendwann mal bisschen verbessern, aber ich habe die Hoffnung, dass so das Problem zumindest erstmal gelöst ist.)

**Comment by dergel** [comment]
ich schließe das Issue hier .. dennoch kann gerne ein Kommentar hinterlegt werden ob es damit klappt. Ist ja ein YForm Problem

**Comment by tyrant88** [comment]
@gharlan Ja, die Validierung wird nicht ausgelöst! Es klappt anscheinend.

**Comment by alexplusde** [comment]
Wir würden das am Freitag testen...

**Comment by alexplusde** [comment]
PS: es funktioniert.
