### ISSUE TITLE
Gruppen-Rechte bei den Artikeln werden ignoriert

### ISSUE THREAD

**Issue by bega011** [yakamara/redaxo_ycom#135]
Die zugewiesenen Gruppen-Rechte bei den Seiten/Artikeln werden ignoriert bzw. es werden alle der 2. Ebene in der Navigation gezeigt, egal welcher Gruppe die gehören, auch bei nicht eingeloggten Usern.

**Comment by olien** [comment]
Ein ähnliches Verhalten habe ich auch bei einigen älteren Installationen (update REX / ycom / yform gemacht auf die aktuellsten Versionen) 

Sofern ich eine neue Installation nutze funktioniert alles.

**Comment by alexplusde** [comment]
@olien was meinst du mit aktuellster Version?

**Comment by olien** [comment]
Die Versionen die im Installer verfügbar sind.

**Comment by bega011** [comment]
Gerade mit der Installer-Version hats nicht funktioniert. Erst wo ich die Klasse ycom_auth.php mit der Github-Version überschrieben habe, hats gefunzt. Und auch Logout ignoriert die angabe wo es nach dem Logout springen soll.
