### ISSUE TITLE
Logout führt zum falschen Artikel

### ISSUE THREAD

**Issue by greatif** [yakamara/redaxo_ycom#136]
Nach Update **ycom 1.0 -> 2.1b**:

- Zunächst wurde unter **Community -> Einstellungen -> Authentifizierung** die "**Authentifizierung aktiviert**" u. "**Weiterleitungen zu Artikel**" gesetzt.

- Logout-Artikel wurde _(hier im Beispiel-Fall)_ gesetzt auf den Artikel:
`/login/logged-out/`

- Nach dem Logout landet man jedoch über den Pfad:
`/login/?rex_ycom_auth_ref=%252Fmein-profil%252Flogout%252F%253Frex_ycom_auth_logout%253D1`
auf dem Login-Artikel (wobei `mein-profil` und `logout` andere Artikel sind).

- Statt auf den Logout-Artikel `logged_out` verweist `/?rex_ycom_auth_ref=%252F...%252F...%252Frex_ycom_auth_logout%253D1`
also auf einen anderen Artikel, als denjenigen, der in der Konfiguration gesetzt ist.

- außer dem Update von ycom 1.0 auf 2.1b wurde nichts geändert
- mit ycom 1.0 funktioniert der Logout einwandrei

**Comment by alexplusde** [comment]
Das Problem wurde in Slack und sogar im Forum öfters berichtet...

**Comment by dergel** [comment]
@alexplusde auch bei Version 2.1b ?

**Comment by alexplusde** [comment]
Scheint behoben.

**Comment by dergel** [comment]
ich denke auch .. ok

**Comment by rolandsee** [comment]
Habe es eben in zwei Redaxo Instanzen getestet (YForm 2.3b, YCom 2.1b). Bei mir schlägt der Redirect nach dem Logout noch immer fehl. Führt nach wie vor wieder auf die Login-Seite.

**Comment by dergel** [comment]
und das obwohl du die Config neu gespeichert hast - cache auch mal gelöscht etc .. ? Kannst Du mir das Beispiel online stellen und per Mail oder Slack zuschicken ?

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_ycom/issues/137#issuecomment-313919596 ?

**Comment by greatif** [comment]
Das Phänomen hat folgende Ursache:

Der "Fehler" tritt dann auf, wenn der Logout-Artikel im geschützten Bereich liegt, d.h. die Zugriffsrechte auf "Zugriff für eingeloggte User" stehen.
Der Artikel wird 2x aufgerufen, um die Umleitung auf den Loggedout-Artikel durchzuführen und da der User beim 2. Mal aber schon abgemeldet ist, erfolgt die Weiterleitung dann aufgrund der aktuellen Einstellung zum Login.
Der Logout erfolgt in diesem Fall über das Modul "YForm Formbuilder" -> "Felddefinitionen" -> "**ycom_auth_form_logout**"
Stellt man die Zugriffsrechte auf "Zugriff für alle User", funktioniert der Logout.

**Comment by skerbis** [comment]
Der Fehler tritt zudem auch auf, wenn der User sich abgemeldet hat und dann noch mal in einem anderen geöffneten Fenster auf Abmelden klickt, auch wenn man das Problem von @greatif beachtet hat und den logout-Artikel für alle freigegeben hat.

**Comment by dergel** [comment]
weiss gar nicht warum ich das issiue reopened habe, die Erklärung passt ja und man muss darauf achten, dass der Logout Artikel für nicht eingeloggte User verfügbar ist.
