### ISSUE TITLE
YCom leitet nicht auf Login-Seite, wenn Nutzer ausgeloggt.

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#137]
Wenn man die URL aufruft, die gepserrt ist, wird man nicht auf die in den Einstellungen hinterlegte Seite weitergeleitet.

Ein zweiter Klick auf den Logout-Link führt im übrigen zu einem unendlichen Redirect.

Rückfragen / direkter Zugang gerne via Slack @dergel

**Comment by alexplusde** [comment]
evtl. zusammenhängend mit https://github.com/yakamara/redaxo_ycom/issues/135

**Comment by netzproductions** [comment]
Ich habe ein ähnliches Verhalten: ycom 2.1b auf R5.3 installiert, Authentifizierung aktiviert und Artikel eingerichtet, bestimmten Artikel geschützt, dieser kann trotzdem aufgerufen werden.

**Comment by alexplusde** [comment]
An vielen Stellen stimmen die Keys der Einstellungen nicht überein, z.B.

https://github.com/yakamara/redaxo_ycom/blob/master/pages/main.manual_user_header_navi_code.inc#L16
`rex_addon::get("ycom")->getConfig("article_login_ok")`

https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/pages/settings.php#L17
`$this->setConfig('article_id_jump_ok', rex_request('article_id_jump_ok', 'int'));`

**Comment by skerbis** [comment]
Hier einfach in den Einstellungen die Seite neu setzen, bei mir hat es dann geklappt

**Comment by dergel** [comment]
@alexplusde hatte das bei dir auch geklappt ?

**Comment by tbaddade** [comment]
Wichtig wäre dass das param `rex_ycom_auth_logout` aus der Url verschwindet. Ansonsten kann man sich nicht  gleich wieder einloggen, wenn die Urls beim Loginformular genommen wird.

@dergel siehe aktuelles Upgrade-Projekt.

**Comment by dergel** [comment]
Als Info .. Logout Urls wurden als Referer verwendet, d.h. man hat sich eingeloggt und wurde auf die logout url geleitet .. :) .. .. jetzt nicht mehr ..
