### ISSUE TITLE
Feld für Gruppenzuordnung fehlt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#138]
Man kann einen Nutzer keiner Gruppe zuordnen.

Edit: Scheinbar gibt's das Problem mit einer geupdateten Version, bei einer Neuinstallation tritt das nicht auf. Darf aber irgendwie auch nicht sein.

**Comment by skerbis** [comment]
https://github.com/yakamara/redaxo_ycom/issues/134

**Comment by alexplusde** [comment]
Sollte auf jeden Fall so sein, dass ein Update das Skript dazu ausführt.

**Comment by dergel** [comment]
@alexplusde kannst du mir das bei einer installation zeigen und beschreiben welches update du gemacht hast ?

**Comment by alexplusde** [comment]
leider habe ich dazu gerade keine Installation mehr parat. 
Ich habe von 2.1 auf die vor 5 Tagen aktuelle Installer-Version geupdatet.

**Comment by dergel** [comment]
ich glaube das lag daran, dass das Gruppenplugin nicht automatisch mit aktualisiert wurde. sollte aber nun so sein. bis ich eines besseren belehrt werde, schliesse ich das hier :)

**Comment by alexplusde** [comment]
einverstanden :)
