### ISSUE TITLE
Setzen von form_ytemplate wirft eine Warnung

### ISSUE THREAD

**Issue by eaCe** [yakamara/redaxo_ycom#140]
Wenn ich `$yform->setObjectparams('form_ytemplate', 'classic');` nutzen möchte, bekomme ich folgende Warnung:

![login](https://user-images.githubusercontent.com/2708231/28200379-0211fb88-686c-11e7-83a5-1a357f7e0038.PNG)

Bin nicht sicher ob es um das selbe geht wie hier: https://github.com/yakamara/redaxo_ycom/issues/117

**Comment by dergel** [comment]
ist das mit der github version immernoch so ? ..
