### ISSUE TITLE
Einstellungen Gruppen - Text und Einstellungen fehlen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#143]
![image](https://user-images.githubusercontent.com/3855487/28521903-153f9690-7076-11e7-943c-40f619eb1bb8.png)

**Comment by DavidBruchmann** [comment]
Tja, das ist immer noch soo

**Comment by dergel** [comment]
wenn ich nur wüsste was man da reinschreiben könnte :) .. vielleicht einfach den Reiter entfernen..

**Comment by DavidBruchmann** [comment]
Gruppenliste, Gruppenrechte, Gruppenmitglieder?

**Comment by dergel** [comment]
Gruppenliste habe ich in einer eigenen Tabelle und auch die Gruppenmitglieder (ist ja eine userliste mit gruppenfilter) .. Deswegen bin ich mir etwas unsicher was für einen Mehrwert es hat .. Deswegen ist die Userliste auch dort nicht drin.

**Comment by DavidBruchmann** [comment]
Tja, auch Gruppenrechte könnte man sich in der Strukturhierarchie mühsam zusammensuchen.
Eine Seitenansicht soll ja in erster Linie der Übersicht dienen und kein normalisiertes Datenmodell wiederspiegeln. Aber ich bin bei dem System relativ leidenschaftslos, insofern ist meine Meinung sicherlich nicht ausschlaggebend. Wichtiger sind andere Dinge sowieso, z.B, das Installationsproblem.
