### ISSUE TITLE
Feature-Wunsch: User in der Gruppen-Ansicht zuordnen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#144]
![image](https://user-images.githubusercontent.com/3855487/28521968-58d09cf6-7076-11e7-8e37-9a64739d1acd.png)

Hier könnte man mit einem Relations-Popup (wie bei YForm sonst) Nutzer nachträglich einer Gruppe zuweisen, bspw., wenn die Gruppe neu angelegt wurde und die Nutzer bereits existieren.

**Comment by dergel** [comment]
Das geht dann nur über eine Verknüpfungstabelle. Das will ich aber ungern entsprechend ändern. Deswegen wohl erstmal damit leben..
