### ISSUE TITLE
Registrierungsbestätigung geht nicht

### ISSUE THREAD

**Issue by psgehe** [yakamara/redaxo_ycom#146]
Hallo,

ich möchte gerne meine Registrierung bestätigen lassen. Um dies zuveranlassen habe ich wie in der Doku das E-Mail Template sowie das Formular eingerichtet. Jedoch kommt jedes Mal eine Fehlermeldung welche hinterlegt ist.
Wichtig anzumerken: Ich möchte die Bestätigung ausschließlich via **rex_ycom_activation_key**. Zusätzlich soll dann in eine andere Datenbank die User-Id geschrieben werden.

> hidden|status|1
> objparams|submit_btn_show|0
> objparams|send|1
> 
> validate|ycom_auth_login|activation_key=rex_ycom_activation_key|status=0|Zugang wurde bereits bestätigt oder ist fehlgeschlagen|status
> 
> action|ycom_auth_db|update
> 
> action|db_query|insert into rex_profil set profil_id = rex_ycom_id
> 
> action|html|<div class="alert alert-success alert-dismissible" role="alert"><h4>Vielen Dank!</h4><p>Deine E-Mail wurde bestätigt. Du bist jetzt eingeloggt.</p></div>

Und im E-Mail Template ist folgende URL hinterlegt:
`$url = rex::getServer().rex_getUrl(20,'',[ 'activation_key' => REX_YFORM_DATA[field="activation_key"]); 
$url = str_replace(['./','//','http:/'],['','/','http://'],$url);`

Diese URL geb ich mir dann aus und der Link sieht z.B so aus:
`http://dev.meinedomain.de/registrierung/registrierungsbestaetigung/?activation_key=904d1gea12t06459b8495214a09`

Leider klappt so die Registrierungsbestätigung aber nicht. Ich teste auf eine Subdomain.-
Über Anregung oder Lösungsansätze wäre ich dankbar.

LG, Patrick

**Comment by dima-clicksports** [comment]
Problem liegt in **ycom/plugins/auth/lib/ycom_auth.php** in Zeile 330

`$loginField = rex_config::get('ycom', 'login_field');`

soll sein:

`$loginField = rex_config::get('ycom/auth', 'login_field');`

in der Community-Demo funktioniert es nur weil das alte Config-Feld noch vorhanden ist.

**Comment by dergel** [comment]
ist korrigiert..

**Comment by dima-clicksports** [comment]
Sehr geehrte Damen und Herren,

ich bin ab dem 09. Oktober gerne wieder persönlich für Sie da.

In dringenden Fällen wenden Sie sich bitte an meine Kollegen unter info@clicksports.de oder 09561/838900

Viele Grüße,
Dmitry Chernitsov

CLICKSPORTS
Cortendorfer Str. 37
D-96450 Coburg

Tel: 09561/83890-0
Fax: 09561/83890-20
Skype: clicksports_dc

USt.-ID: DE 229 373 391
