### ISSUE TITLE
Bug: User-Status wird in den Login-Weiterleitungen leider nicht überprüft

### ISSUE THREAD

**Issue by dima-clicksports** [yakamara/redaxo_ycom#148]
Hallo,

mir ist aufgefallen das die Status aus dem Backend leider nicht berücksichtigt werden. 

Status "Zugang wurde angefragt, Zugang wurde bestätigt" hat den gleichen Effekt wie Status "Zugang ist aktiv". Dies macht doch keinen Sinn oder? Hier würde ich doch erwarten das sich der User erst einloggen kann sobald der Status auf "Zugang ist aktiv" gesetzt wurde.

Oder ist hier vorgesehen das die Prüfungen vom Entwickler im Template nachgerüstet werden?

Dieses Verhalten konnte ich nicht nur in meinem Projekt sonder auch direkt in der Demo für YCom feststellen.

**Comment by renmlp** [comment]
funktinoiert bei mir auch nicht

**Comment by dergel** [comment]
ist wohl ein Fehler.. Wird noch korrigiert.
