### ISSUE TITLE
Wunsch :: Community-Seitenrechte ausblenden, wenn kein Recht

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#149]
Nimmt, sehr viel Platz ein obwohl der Nutzer nicht berechtigt ist es zu benutzen. 
![bildschirmfoto 2017-08-23 um 08 49 35](https://user-images.githubusercontent.com/791247/29602358-20411196-87e0-11e7-8d60-a1c67bf8be6d.png)

**Comment by dergel** [comment]
das stimmt. aber ich finde die Info wichtig für den Redakteur. Einen Bezug muss er haben. Und da man die Seitenrechte ergänzen kann und das auf der YForm basiert, kann ich das nicht rausnehmen oder anders darstellen. deswegen schliesse ich das issue
