### ISSUE TITLE
fehlerhafte weiterleitungen nach login, logout

### ISSUE THREAD

**Issue by DavidBruchmann** [yakamara/redaxo_ycom#151]
Absolut frische Installation, warum wird endlos umgeleitet? :

http://domain.com/index.php?article_id=5&rex_ycom_auth_ref=%252Findex.php%253Farticle_id%253D5%2526rex_ycom_auth_ref%253D%2525252Findex.php%2525253Farticle_id%2525253D5%25252526rex_ycom_auth_ref%2525253D%25252525252Findex.php%25252525253Farticle_id%25252525253D5%252525252526rex_ycom_auth_ref%25252525253D%252525252525252Findex.php%252525252525253Farticle_id%252525252525253D5%2525252525252526rex_ycom_auth_ref%252525252525253D%2525252525252525252Findex.php%2525252525252525253Farticle_id%2525252525252525253D5%25252525252525252526rex_ycom_auth_ref%2525252525252525253D%25252525252525252525252Findex.php%25252525252525252525253Farticle_id%25252525252525252525253D5%252525252525252525252526rex_ycom_auth_ref%25252525252525252525253D%252525252525252525252525252Findex.php%252525252525252525252525253Farticle_id%252525252525252525252525253D5%2525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525253D%2525252525252525252525252525252Findex.php%2525252525252525252525252525253Farticle_id%2525252525252525252525252525253D5%25252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525253D%25252525252525252525252525252525252Findex.php%25252525252525252525252525252525253Farticle_id%25252525252525252525252525252525253D5%252525252525252525252525252525252526rex_ycom_auth_ref%25252525252525252525252525252525253D%252525252525252525252525252525252525252Findex.php%252525252525252525252525252525252525253Farticle_id%252525252525252525252525252525252525253D5%2525252525252525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252Findex.php%2525252525252525252525252525252525252525253Farticle_id%2525252525252525252525252525252525252525253D5%25252525252525252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252Findex.php%25252525252525252525252525252525252525252525253Farticle_id%25252525252525252525252525252525252525252525253D5%252525252525252525252525252525252525252525252526rex_ycom_auth_ref%25252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252Findex.php%252525252525252525252525252525252525252525252525253Farticle_id%252525252525252525252525252525252525252525252525253D5%2525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252525252Findex.php%2525252525252525252525252525252525252525252525252525253Farticle_id%2525252525252525252525252525252525252525252525252525253D5%25252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252525252Findex.php%25252525252525252525252525252525252525252525252525252525253Farticle_id%25252525252525252525252525252525252525252525252525252525253D5%252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%25252525252525252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252525252525252Findex.php%252525252525252525252525252525252525252525252525252525252525253Farticle_id%252525252525252525252525252525252525252525252525252525252525253D5%2525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252525252525252525252Findex.php%2525252525252525252525252525252525252525252525252525252525252525253Farticle_id%2525252525252525252525252525252525252525252525252525252525252525253D5%25252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252525252525252525252Findex.php%25252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%25252525252525252525252525252525252525252525252525252525252525252525253D5%252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%25252525252525252525252525252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%252525252525252525252525252525252525252525252525252525252525252525252525253D5%2525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525252525252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%2525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%2525252525252525252525252525252525252525252525252525252525252525252525252525253D5%25252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525252525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%25252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%25252525252525252525252525252525252525252525252525252525252525252525252525252525253D5%252525252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%25252525252525252525252525252525252525252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%252525252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D5%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D5%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D5%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D5%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D5%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252526rex_ycom_auth_ref%2525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252Findex.php%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253Farticle_id%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525253D5

**Comment by DavidBruchmann** [comment]
Die Installation ist mit der Community-Demo, möglicherweise fehlerhafte Konfiguration ist dann aus dem Addon.

**Comment by polarpixel** [comment]
Hallo David, vielen Dank für Deine Issues und den PR!
Diese Fehler haben sich in die Demo eingeschlichen durch Updates von Yform- und Community-AddOn. Die Community-Demo muss deshalb leider überarbeitet werden, dies habe ich mir für die nächste Woche vorgenommen.

Magst Du vielleicht mit in den Slack-Channel kommen? (Lockeres Austauaschen von Redaxo-Entwicklern) Das könnte was für Dich sein ...

**Comment by DavidBruchmann** [comment]
Hi Peter, ich warte dort ....

**Comment by polarpixel** [comment]
Hi, ich sehe es gerade.

**Comment by dergel** [comment]
dürfte eigentlich so nciht mehr in der github ycom version sein .. wenn dem so ist bitte das issue schliessen

**Comment by DavidBruchmann** [comment]
Github version von ycom oder der demo?

**Comment by DavidBruchmann** [comment]
ycom von github installiert, cache gelöscht, leider keine Entwarnung.
Nach dem Login werde ich auf Article5 umgeleitet mit den obigen Endlos-Parametern in der URL.

**Comment by DavidBruchmann** [comment]
Nach dem Logout das gleiche mit index.php?article_id=14

**Comment by dergel** [comment]
hast du einen reinstall gemacht ? .. hast du die konfig nochmal geprüft nach dem update und reinstall ?

**Comment by DavidBruchmann** [comment]
was soll ich bei der Konfig prüfen?

**Comment by dergel** [comment]
ob auch nach dem Update alles richtig eingestellt ist, eventuell die Konfig einfach nochmal neu speichern..  und auch die Logik dahinter prüfen. also ob die logout Seite auch die richtigen Rechte hat.. oder die Loginseite. nicht, dass man dort gar nicht mit den aktuellen Rechten in der Situation zugreifen darf und deswegen die Weiterleitungen kommen

**Comment by DavidBruchmann** [comment]
Ja ich denke es ist ein Fehler in ycom-demo und nicht in ycom.
@polarpixel sollte daran arbeiten, z.B. daß die Logout-Bestätigung nicht innerhalb einer zugriffsgeschützen Seite liegt. Ich weiss nicht weshalb die Struktur so angelegt wurde oder sogar funktioiert hat, aber sie ist in der Demo unlogisch und die Weiterleitungen erscheinen zumindest erklärbar.
Ich schließe hier, da das Thema nicht zu ycom selbst gehört.
