### ISSUE TITLE
Notice group Plugin wenn kein User vorhanden ist

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_ycom#152]
`Notice: Trying to get property of non-object in \redaxo\src\addons\ycom\plugins\group\boot.php on line 48`
Wenn kein User eingeloggt ist, ist `$me` [in Zeile 48](https://github.com/yakamara/redaxo_ycom/blob/master/plugins/group/boot.php#L48) `null`.

**Comment by IngoWinter** [comment]
https://github.com/yakamara/redaxo_ycom/pull/153

**Comment by dergel** [comment]
vielen dank :)
