### ISSUE TITLE
Fehler bei Update von 2.1b2 auf 2.1b3 oder höher

### ISSUE THREAD

**Issue by rolandsee** [yakamara/redaxo_ycom#158]
Habe eben ein Update von 2.1b2 auf 2.1b3 gemacht mit folgendem Ergebnis:
Exception
DateTime::__construct() : Failed to parse time string (1491990671) at position 8 (7): Unexpected character
 
Mit update von 2.1b2 auf 2.1b4 das gleiche Ergebnis

![image](https://user-images.githubusercontent.com/4113894/32094853-7db6ab48-bb01-11e7-8061-480392d5944a.png)

**Comment by dergel** [comment]
kannst du auslesen was für ein Wert in last_login_time ist ?
eventuell einfach kurz diese Zeile umschreiben

```
dump($user->getValue('last_login_time'));
exit;

```

**Comment by rolandsee** [comment]
Hi, ich bin bisher noch nicht wieder an diese Stelle gekommen. Melde mich aber, sobald ich näheres weiß.

**Comment by rolandsee** [comment]
ah, schließen wollte ich das natürlich nicht...

**Comment by rolandsee** [comment]
Hmm, mittlerweile sehe ich keinerlei Regelmäßigkeiten mehr.
Ich habe es nun nach mehreren Install-Versuchen geschafft, auf die Version 2.1b3 upzugraden, ohne dass es beim Userlogin dann zu harten Fehlern kommt. Der Login funktioniert.
Nun dachte ich mir, dann gleich auf Version 2.1b4 updaten. Auch das ging ohne Fehler. Allerdings ist nun der Login nicht mehr möglich. Daher wieder zurück zu 2.1b3.
Echt schwierig, da - wie gesagt - keine Regelmäßigkeit zu erkennen ist. Auch gibt es keinen harten Fehler mehr.

**Comment by dergel** [comment]
Bitte prüfe unbedingt die YCom Settings. Z.T. sind da nun Optionen möglich, die bewusst hier und da ein Login erschweren (Thema: Login-Rules)..

**Comment by rolandsee** [comment]
Mittlerweile habe ich es erfolgreich geschafft, alle meine Projekte, in denen YForm und YCom läuft, jeweils auf die aktuellsten Versionen upzudaten. Wie oben schon erwähnt, kann ich keine Regelmäßigkeiten, wann welcher Fehler auftritt. Mit etwas Handarbeit, Reinstall's u.ä. hat es am Ende doch geklappt.
Ich schließe dieses Issue daher hiermit.
