### ISSUE TITLE
Editieren von Datensätzen nicht möglich

### ISSUE THREAD

**Issue by brt-tito** [yakamara/redaxo_ycom#159]
Mit der aktuellen Version gibt es ein Problem beim editieren eines Datensatzes (PHP 5.6): 

> ErrorException thrown with message "Call to private method rex_yform_manager_dataset::tableToModel() from context 'rex_ycom_user'"
> 
> Stacktrace:
> #0 ErrorException in .../redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php:99

**Comment by dergel** [comment]
hmm.. aber aktuelle redaxo version und aktuelle yform vorhanden, oder ? eventuell mal den cache löschen..

**Comment by brt-tito** [comment]
cache löschen ... ich komm mir vor wie bei Typo3 ;-)
Aber ja, hab ich gemacht. yForm ist 2.3-beta3 und yCom ist 2.1b4
Sobald ich in der Tabelle "User" oder "Gruppen" eine Datensatz bearbeiten will bekomme ich diese Meldung.

**Comment by dergel** [comment]
>cache löschen ... ich komm mir vor wie bei Typo3 ;-)
;)

schaus mir dir tage an

**Comment by dergel** [comment]
Ich kann es nicht nachvollziehen.. Bist du in redaxo.org/slack ? willst du mir einen Zugang geben, damit ich mir das ansehen kann ?

**Comment by brt-tito** [comment]
Hab den Webspace auf PHP 7 umgestellt und jetzt tritt der Fehler nicht mehr auf. Das Problem scheint nur bei PHP 5.6 aufzutreten. Für mich also erst mal in Ordnung.

**Comment by dergel** [comment]
yform problem.. ab 2.3-b5 behoben (kommt die tage)
