### ISSUE TITLE
Registrieren mit PHP 5.6

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_ycom#162]
Bei einer PHP-Version kleiner als 7 (getestet mit 5.6) erscheint nach dem Registrieren der Fehler:
`Call to private method rex_yform_manager_dataset::tableToModel() from context 'rex_ycom_user'`
Der User wird aber angelegt.

**Comment by olien** [comment]
uahhahha. hab gerade das gleiche problem in anderen yform tabellen
... kann ich das irgendwie (temporär) umgehen?

auf dem entwicklungsserver ist aktuell PHP 5.6.31-1~dotdeb+7.1

**Comment by olien** [comment]
Siehe auch #159

**Comment by dergel** [comment]
yform problem.. ab 2.3-b5 behoben (kommt die tage)
