### ISSUE TITLE
Passwortregeltroubles

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_ycom#164]
In der Beispiel-Formulardefinition für das Registrierungsformular fehlt eine Fehlermeldung und Passwortregeldefinition  in der Zeile
`ycom_auth_password|password|Ihr Passwort:*|`
Es werden ohne Wissen des Nutzers die Redaxo Passwortregeln angewendet und die leer rote Fehlerbox hilft nicht weiter...

**Comment by dergel** [comment]
ja das stimmt.. vielleicht wäre es wirklich besser wenn es keine default regeln hier gibt.

**Comment by georgkaser** [comment]
Hab auch grad den Fall - wie krieg ich die Regeln jetzt weg? Möchte ein "Passwort ändern" Formular zur Verfügung stellen...

**Comment by georgkaser** [comment]
Ah, habs gefunden! Für die, die auch das Problem haben: Man findet die Regeln im Feld der YForm Tabelle "rex_ycom_user" (Passwortregeln als JSON).

**Comment by georgkaser** [comment]
Hmm, es reicht aber scheinbar nicht nur die Regeln in dem Feld zu ändern. Passwort ändern funktioniert trotzdem nicht. Muss man da noch was ändern?

Folgende Passwortregel ist nun eingestellt: 

````
{"length":{"min":8},"letter":{"min":0},"lowercase":{"min":0},"uppercase":{"min":0},"digit":{"min":0},"symbol":{"min":0}}```

Folgendes Formular verwende ich um das Passwort zu ändern:

```
objparams|form_class|hide-label

ycom_auth_password|password|#placeholder:Neues Passwort*|Neues Passwort*|
password|password_2|#placeholder:Passwort wiederholen*|Passwort wiederholen*||no_db

validate|empty|password|Bitte gib ein Passwort ein.
validate|compare|password|password_2|!=|Bitte gib zweimal das gleiche Passwort ein

action|ycom_auth_db
```

**Comment by georgkaser** [comment]
Räusper - wieder selbst draufgekommen, Tablemanager sei Dank ;)

Formularfeld muss so lauten:
```
ycom_auth_password|password|#placeholder:Neues Passwort*|Neues Passwort*|{"length":{"min":8},"letter":{"min":0},"lowercase":{"min":0},"uppercase":{"min":0},"digit":{"min":0},"symbol":{"min":0}}|Passwort Rule Fehler|1|
```

**Comment by rolandsee** [comment]
Hi Georg,
ich habe eben die gleichen Probleme wie oben beschrieben.
Mir ist nicht ganz klar, wo genau die Passwortregeln zu finden sind:

> Man findet die Regeln im Feld der YForm Tabelle "rex_ycom_user" (Passwortregeln als JSON).

Welches Feld ist gemeint in welcher Tabelle?

**Comment by georgkaser** [comment]
Du musst die Tabelle "rex_ycom_user" im Tabellenmanager von YForm editieren. Dort gibt es ein Feld "ycom_auth_password" - da stehen die Regeln drin. Hier ein Screenshot, ich hoffe du verstehst was ich meine:

<img width="1339" alt="bildschirmfoto 2017-11-20 um 20 15 30" src="https://user-images.githubusercontent.com/6472869/33036807-db8dfb7c-ce2f-11e7-9d1f-5fd8015fb24c.png">

**Comment by rolandsee** [comment]
Hi Georg,
alles klar.
Danke dir :-)

**Comment by Hirbod** [comment]
Danke @georgkaser, hast mir die Nacht gerettet. @dergel bitte sowas doch irgendwie besser in den Installer-Changelogs dokumentieren. Bei mir war die auth-funktion jetzt einfach tagelang kaputt, ohne das ich es bemerkt habe.. Kunden haben darauf hingewiesen, dass da ein "roter Punkt" nur erscheint. Konnte dank Georgs Info das ganze anpassen.

**Comment by staabm** [comment]
wäre es nicht sinnvoll dass die default fehlermeldung nicht leer ist

**Comment by dergel** [comment]
wäre besser.. weil fehlermeldungen sollten schon auftauchen, wenn etwas falsch ist, aber dann vielleicht irgendein platzhalter der erklärt welcher fehlertext fehlt.. ganz allgemein und eben auch hier ..

**Comment by dergel** [comment]
wäre dann aber yform

**Comment by dergel** [comment]
*die passwortregeln werde nun besser erklärt - ist in der doku
* leere fehlermeldungen werden nun gekennzeichnet / yform 3.0
