### ISSUE TITLE
CSRF Troubles

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_ycom#167]
Bei der Registrierungsbestätigung musste ich über die objparams `csrf_protection` auf `false` setzen, sonst schlug die Registierung  fehl

**Comment by dergel** [comment]
genau.. das gehört in die doku und zur demo .. hier wird ja kein regisistrierungsprozess vorgegeben.. eigentlich wäre ein doku wie bei yform super.. lust dabei zu helfen ?

**Comment by IngoWinter** [comment]
Lust bedingt, Zeit aktuell leider gar nicht :)
Ich seh zu, dass ich nen PR für die Beispiele im Backend mache wenn ich wieder etwas Luft habe. Dann mach ich auch für die Demo was fertig https://github.com/FriendsOfREDAXO/demo_community/issues/24

**Comment by dergel** [comment]
am Rand.. im Moment ist die CSRF Implementierung von YForm selbt gemacht. Aber REDAXO bietet ab v5.5 das auch an und das werde ich dann übernehmen, so dass dies identisch ist. Aktuell kann es hin und wieder vorkommen das ein CSRF erkannt wird, obwohl keines da ist.. (in seltenen Fällen)

**Comment by skerbis** [comment]
Zum Thema:
https://redaxo.org/forum/addons-packages-r5-f43/ycom-ungueltiger-csrf-token-t22075.html

**Comment by alexplusde** [comment]
Bitte wieder aufmachen, sorgt durchaus für Verwirrung.
