### ISSUE TITLE
Manche Authentifizierungsregeln funktionieren nicht

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#169]
Ich habe hier ein frisch installiertes YCom am Start und bekomme beim Anmelden immer die Fehlermeldung, dass der Login nicht möglich ist.

Folgendes habe ich gemacht:
- YCom Version: 2.1b5 installiert. Beide Plugins sind aktiviert.
- Authentifizierung ist in den Einstellungen aktiviert und als Login-Feld ist "login" eingestellt.
- Ein Benutzer ist im Backend angelegt worden. Der Status ist "Zugang ist aktiv".
- Das Loginformular ist das YForm Formular, wie es in der Doku steht.

Irgend einen Tipp um die Sache zu debuggen?

**Comment by rolandsee** [comment]
Check mal in den Community Einstellungen die Authentifizierung. Hier insbesondere die Regeln, die rechts unten im DropDown gesetzt werden können.
![image](https://user-images.githubusercontent.com/4113894/33064361-b0dad35c-cea5-11e7-8695-f1d0ceeaebb1.png)
Probier da einige aus. Ich habe den Eindruck, dass nicht alle Regeln funktionieren. "User nach 10 Loginversuchen deaktivieren " funzt jedoch bei mir.

**Comment by TobiasKrais** [comment]
Roland, du bist mein Held! Das ist es. Folgende Punkte funktionieren nicht:
- User wird für 15 Minuten nach jeweils 5 Login-Versuchen gesperrt
- User wird für 15 Minuten nach jeweils 10 Login-Versuchen gesperrt

**Comment by polarpixel** [comment]
Ergänzende Info zu diesem Thema:
Bei der Wahl von "unendlich viele Versuche" kommt die notice:
`Notice: 
Undefined index: loginStay in .../redaxo/src/addons/ycom/plugins/auth/lib/ycom_auth.php on line 140 
Notice: Undefined index: loginStay in .../redaxo/src/addons/ycom/plugins/auth/lib/ycom_auth.php on line 198`

**Comment by IngoWinter** [comment]
https://github.com/yakamara/redaxo_ycom/pull/180

**Comment by dergel** [comment]
sollte mit dem PR von norbert gefixed sein .. Kann das jemand gegentesten ?

**Comment by TobiasKrais** [comment]
Getestet und funktioniert! Danke!
