### ISSUE TITLE
Deinstallation nicht sauber

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#170]
Wenn das YCom Addon deinstalliert wird bleiben im Backend die Tabellen übrig.

Wenn man dann YCom erneut installiert gibt es einen fatal error.

**Comment by TobiasKrais** [comment]
Mach es in einem Redaxo mal genau so wie oben beschrieben: Ycom installieren, deinstallieren und wieder installieren. Dann kommt das:
![bildschirmfoto von 2018-07-18 21-38-34](https://user-images.githubusercontent.com/4131072/42903760-2c82a662-8ad3-11e8-9e29-80d6e2b67131.png)

**Comment by dergel** [comment]
Den Fehler schaue ich mich an und sehe auch schon, dass die uninstall prozess nichts so 100%ig passen.. Aber bei den Usertabellen bin ich mir sehr unsicher ob die direkt wieder gelöscht werden sollten - ich denke nicht. Aber eine Info in der Doku wäre dennoch gut.

**Comment by dergel** [comment]
die user_tabelle wird bei deinstall gedropt..  hatte ich falsch im kopf .. dann lassen wir das so .. desinstalllieren heisst - alles was ycom ist wieder entfernen

**Comment by tbaddade** [comment]
> alles was ycom ist wieder entfernen

YForm-Datentabellen werden bisher nie gelöscht, wozu die User Tabelle der YCom auch gehört. Das widerspricht sich somit.

**Comment by dergel** [comment]
es gibt einen Unterschied ob man in der YForm Änderungen macht, oder ob ein AddOn macht. D.h. bisher wurden die ycom tabellen auch gelöscht und sofern das addon deinstalliert wird ist es meines erachtens auch richtig.. yform ist übergeordnet und kann das nicht für die ycom entscheiden. .passt für mich wie es war.

**Comment by dergel** [comment]
Ansonsten habe ich die Deinstallation nun verbessert. History und die einzelnen Felder werden nun gelöscht.

**Comment by TobiasKrais** [comment]
Danke! Das bedeutet, dass der eingangs erwähnte Fatal Error nicht mehr vorkommen kann, richtig?

**Comment by dergel** [comment]
so hatte ich es getestet: Ycom installieren, deinstallieren und wieder installieren.

**Comment by TobiasKrais** [comment]
Perfekt. Danke!

**Comment by dergel** [comment]
gerne gegentesten :)
