### ISSUE TITLE
E-Mailadresse wird bei fehlerhafem Login / Änderung Profildaten zerrissen

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#174]
Wenn ich mich mit meiner E-Mailadresse anmelde und ein falsches Passwort eingebe wird auf der Fehlerseite die E-Mailadresse wie folgt angezeigt: `ich<span class=unicorn><span>_at_</span></span>meinedomain.de`.

Das selbe Phänomen tritt beim Speichern der Änderung von Profildaten auf.

**Comment by dergel** [comment]
hast du einen replacer irgendwie drin, welcher emails anpasst ? ich glaube das kommt nicht von ycom

**Comment by TobiasKrais** [comment]
Hi Jan, stimmt. Das ist der emailobfuscator, der das nicht packt.
