### ISSUE TITLE
Beispielcode für Passwordänderung ändert Passwort nicht

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#175]
... und das obwohl angezeigt wird, dass das Passwort erfolgreich geändert wurde.

**Comment by rolandsee** [comment]
Im eingeloggten Bereich funzt der folgende Code bei mir, wenn ich das Passwort ändere:
```
objparams|form_class|hide-label

ycom_auth_password|password|#placeholder:Neues Passwort*|Neues Passwort*|{"length":{"min":8},"letter":{"min":0},"lowercase":{"min":0},"uppercase":{"min":0},"digit":{"min":0},"symbol":{"min":0}}|Passwort muss mind. 8 Zeichen lang sein|1|
password|password_2|Passwort bestätigen:*||no_db

validate|empty|password|Bitte geben Sie ein Passwort ein
objparams|values.password.placeholder|&nbsp;
validate|compare|password|password_2|!=|Bitte geben Sie zweimal das gleiche Passwort ein

submit|label|Abschicken|no_db|||btn btn-g loginbutton

action|ycom_auth_db
```

**Comment by TobiasKrais** [comment]
Roland, du bist schon wieder mein Held des Tages :-).

Hier der entsprechende Pull Request: https://github.com/yakamara/redaxo_ycom/pull/177

**Comment by rolandsee** [comment]
Hi Tobias,
ich muss aber ehrlicherweise sagen, dass ich mittlerweile schon zwei Tage an diesem System herumschustere. Anders kann ich es nicht ausdrücken.
Und wenn ich einen Fehler gelöst habe, tauchen zwei neue auf. Es scheint mir noch sehr sehr viele Ungereimtheiten zu geben.
Ich glaube, es wäre das beste, eine Art "feature freeze" für YCom und YForm zu machen, um erstmal den momentanen Stand ohne große Umstände zum Laufen zu bekommen.

**Comment by TobiasKrais** [comment]
Hi Roland, das Gefühl drängt sich mir auch auf. Gleiche Problematik hier. Lass uns mit dran arbeiten die Fehler klar einzugrenzen und zu melden, bzw. einen Pull Request zu machen. Dann bekommen wir da schon noch ein gutes Produkt hin.

**Comment by alexplusde** [comment]
@TobiasKrais @rolandsee seid ihr da schon weitergekommen? Wo hakt es aktuell?

**Comment by TobiasKrais** [comment]
@alexplusde Ich habe alle Bugs, die ich gefunden habe gemeldet. Und wenn ich eine Lösung gefunden habe auch gleich per pull request gesendet.

**Comment by alexplusde** [comment]
Dann ist dieses Issue hier obsolet?

**Comment by TobiasKrais** [comment]
Ja, stimmt. Da hatte ich ja den commit gemacht. Wird geschlossen. Danke!
