### ISSUE TITLE
E-Mail Validierung bei YCom Login

### ISSUE THREAD

**Issue by rolandsee** [yakamara/redaxo_ycom#176]
Die Validierung der E-Mail Adresse beim Login scheint nicht (mehr) zu funktionieren (ycom 2.1b5//yform 2.3-b5):
```
objparams|form_skin|bootstrap
objparams|form_class|hide-label

ycom_auth_form_info||Login|Benutzer wurde ausgeloggt|Login ist fehlgeschlagen|Benutzer wurde erfolgreich eingeloggt|

ycom_auth_form_login|email|E-Mail|Ihre E-Mail Adresse
ycom_auth_form_password|passwort|Passwort|Ihr Passwort

objparams|values.email.placeholder|Ihre E-Mail Adresse
objparams|values.email.required|required
objparams|values.passwort.placeholder|Ihr Passwort
objparams|values.passwort.required|required

validate|empty|email|Bitte eine E-Mail Adresse eingeben
validate|email|email|Bitte eine gültige E-Mail Adresse angeben
validate|empty|passwort|Bitte Passwort eingeben

#ycom_auth_form_stayactive|auth|eingeloggt bleiben|0

submit|label|und los...|no_db|||btn btn-block
```
Ich würde erwarten, dass die Meldung erscheint "Bitte eine gültige E-Mail Adresse angeben".

Der Loginvorgang rauscht jedoch durch und ergibt folgendes Bild:

![image](https://user-images.githubusercontent.com/4113894/33121674-c73bdd5a-cf75-11e7-9acc-83de747392c8.png)

**Comment by alexplusde** [comment]
Darf `ycom_auth_form_info|` an der Stelle überhaupt stehen?

**Comment by alexplusde** [comment]
Es müsste jetzt sowieso eine type-email-Validierung sein und nicht mehr eine email-Validierung (deprecated)

https://github.com/yakamara/redaxo_yform/commit/5513f38715b07d950d094ee303ec8a38a7d8872e

Geht es mit einer type-Validierung? @rolandsee

**Comment by dergel** [comment]
die neue Form erlaubt es, weil es keine eigenen Login und Psw Felder gibt, d.h. man verwendet die typischen und normalen Felder und nur die Validierung nutzt dann die ycom und loggt den user ein.

```
validate|ycom_auth|login|psw|stayfield|warning_message_enterloginpsw|warning_message_login_failed

text|login|Login
password|psw|Passwort
checkbox|stayfield|Eingeloggt bleiben
ycom_auth_returnto|returnTo|https://redaxo.localhost,https://www.yakamara.de|http://www.redaxo.org/meinespezielleweiterleitung

```
