### ISSUE TITLE
YCom füllt YForm-Felder `name`, `email` usw. aus.

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#184]
Auch, wenn man den Wert im Eingabefeld überschreibt, wird er wieder zugewiesen und bspw. über eine Action in die Datenbank geschrieben.

**Comment by dergel** [comment]
d.h. egal bei welchen Formular ? das wäre ja schräg.. bei der github version, oder letztes release ?

**Comment by steri-rex** [comment]
bei mir ist das auch so - selbst wenn ich eine andere email adresse in das email feld eintrage (also die vorausgefüllte email vom login lösche) - wird trozdem  immer die email adresse vom login in der DB gepeichert 
ich verwende ycom | 2.1b5 und rex 5.5.1

**Comment by dergel** [comment]
Ist das immer noch so ? Ich kann es nicht nachvollziehen, aber mir wäre, als hätte ich es irgendwann mal auch erlebt..

**Comment by skerbis** [comment]
Kann es unter 2.1 nicht reproduzieren

**Comment by alexplusde** [comment]
Kann es weiterhin reproduzieren
YCom: 2.1, YForm 2.3

```
objparams|form_name|table-rex_ycom_group
objparams|form_ytemplate|bootstrap
objparams|form_showformafterupdate|1
objparams|real_field_names|true
text|email|Test||no_db|
```
Absenden und schauen, was im Textfeld steht.

**Comment by skerbis** [comment]
aaah jetzt verstehe ich.  Da steht automatisch **die Adresse des aktuell angemeldeten Users**. Mir war nicht klar, dass sich das auf das Frontend bezieht.

**Comment by alexplusde** [comment]
Anm.: Nicht nur die Adresse, sondern jegliches Feld, das zum Benutzer existiert.

**Comment by dergel** [comment]
Problem besteht auch noch bei 3.0

**Comment by dergel** [comment]
ist nun unschön von mir hier gelöst, aber da es eigentlich ein YForm Bug ist, geht es hier nur so.
Sobald es in der YForm wieder passt, kommt dieser Workaround hier raus..

**Comment by alexplusde** [comment]
Ok, danke fürs fixen...
