### ISSUE TITLE
Login, Debug-Modus: Aktiv - keine Debug-Ausgabe

### ISSUE THREAD

**Issue by Goldfischpeter** [yakamara/redaxo_ycom#187]
Login-Code in Formbuilder, Debug-Modus auf Aktiv bringt keine Debug-Meldung.

**Comment by alexplusde** [comment]
Der Debug-Modus setzt nur dann an, wenn tatsächlich etwas passiert ist. Wenn kein Query erfolgt, wird man auch nicht darauf aufmerksam gemacht.

**Comment by dergel** [comment]
leider gibt es an der Stelle auch nichts zu debuggen. Oder anders. Was für eine Info hättest du gerne ?
