### ISSUE TITLE
Passwort ändern / Daten ändern erkennt nicht aktuelle clang_id

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#189]
In meinem Loginbereich gibt es ein Formular um das Passwort zu ändern und eines um den Namen des Benutzers zu ändern. Diese Formulare sind in der ersten Sprache definiert (Englisch, clang_id = 1). In der zweiten Sprache (Deutsch, clang_id = 2) möchte ich genau das gleiche Formular verwenden und übernehme daher den Artikel aus Sprache 1.

Die Folge ist, dass das deutsche Formular (clang_id = 2) im <form> Tag als action die URL der Sprache 1 angibt (sollte aber Sprache 2 sein). Noch schlimmer: Durch den Sprachwechsel werden die Änderungen nicht gespeichert.

**Comment by dergel** [comment]
kannst du das beispiel hier rein legen ? dann teste ich das

**Comment by TobiasKrais** [comment]
```
ycom_auth_password|password|#placeholder:{{ ycom_password_new }}|{{ ycom_password_new }}|{"length":{"min":8},"letter":{"min":0},"lowercase":{"min":0},"uppercase":{"min":1},"digit":{"min":1},"symbol":{"min":0}}|{{ ycom_failure_password_rule }}|1|
password|password_2|{{ ycom_password_repeat }}||no_db

validate|empty|password|{{ ycom_failure_password_empty }}
validate|compare|password|password_2|!=|{{ ycom_failure_password_different }}

submit|label|{{ yform-ycom_send }}|no_db|||btn btn-g loginbutton

action|showtext|<div class="alert alert-success">{{ ycom_password_set }}</div>|||1
action|ycom_auth_db
```

**Comment by TobiasKrais** [comment]
Hier der Code vom Modul, das Inhalte aus einer anderen Sprache übernimmt: https://github.com/TobiasKrais/d2u_helper/blob/master/modules/05/2/output.php

**Comment by dergel** [comment]
ach so .. jetzt verstehe ich erst das problem.. das geht so leider nicht.. wenn du den inhalt einfach übernimmst, dann übernimmt der natürlich die dortige Sprache, da das Formular ja bereits generiert ist.

Ich mache das immer so, dass ich das identische Formular mehrfach manuell einsetze. Formulare setzt man eh nur selten. 

Im Moment weiss ich keinen sinnvollen anderen Rat. Du könntest höchstens über die DB die Formbuilderinfos holen und das Formular dann neu generieren.

**Comment by TobiasKrais** [comment]
Geht klar. Danke Jan!

**Comment by skerbis** [comment]
Alternativ per outputfilter die url des Formulars überschreiben?

**Comment by TobiasKrais** [comment]
Ne danke. Ich habe es so wie von Jan vorgeschlagen gelöst.

**Comment by skerbis** [comment]
War nur ne Idee 💡 😀
