### ISSUE TITLE
Logout Link wird in rex_ycom_auth_ref übertragen

### ISSUE THREAD

**Issue by Dollique** [yakamara/redaxo_ycom#191]
Wenn man auf den Logout Link (?rex_ycom_auth_logout=1) klickt wird genau dieser GET Request auch auf 'rex_ycom_auth_ref' übertragen.

Der Link sieht dann z. B. so aus:
https://example.com/login?rex_ycom_auth_ref=%252Ftest%252F%253Frex_ycom_auth_logout%253D1

Problem hierbei ist, dass bei erneutem Login das 'rex_ycom_auth_ref' übergangen bzw. ignoriert wird und man auf der Startseite landet.

Mir fällt kein Szenario ein, wo es gewünscht sein könnte, dass der Logout Parameter auch in übernommen wird.

Bitte wenn möglich aus 'rex_ycom_auth_ref' entfernen.

**Comment by dergel** [comment]
sollte nun passen. Wird rausgefiltert.
