### ISSUE TITLE
Ycom whoopsed die Seite

### ISSUE THREAD

**Issue by Pixeldaniel** [yakamara/redaxo_ycom#194]
Wenn ich Ycom installiere bricht meine Seite (im Frontend) zusammen.

YCom Version 2.1
Redaxo Version 5.6

Der Fehler der kommt :

InvalidArgumentException
Scalar expected for $needle in arrayKeyCast()!

9
InvalidArgumentException 
…/redaxo/src/core/lib/request.php183
8
rex_request arrayKeyCast
…/redaxo/src/core/lib/request.php49
7
rex_request request
…/redaxo/src/core/functions/function_rex_globals.php36
6
 rex_request
…/redaxo/src/addons/ycom/plugins/auth/lib/ycom_auth.php17
5
rex_ycom_auth init
…/redaxo/src/addons/ycom/plugins/auth/boot.php11
4
rex_package {closure}
…/redaxo/src/core/lib/extension.php45
3
rex_extension registerPoint
…/redaxo/src/core/packages.php29
2
 include_once
…/redaxo/src/core/frontend.php12
1
 require
…/redaxo/src/core/boot.php136
0
 require
…/index.php9

**Comment by gharlan** [comment]
Das wurde in R5.6.1 gefixt.
