### ISSUE TITLE
Captcha geht nicht in Password zurücksetzen Beispiel

### ISSUE THREAD

**Issue by Dollique** [yakamara/redaxo_ycom#195]
Hallo Zusammen

Ich habe von der YCOM Anleitung/Beispiele das Formular "Password zurücksetzen" übernommen.
Das Captcha liefert bei mir immer einen Fehler, auch wenn es richtig eingegeben wurde.
Ausserdem wird, wenn es richtig eingegeben wurde das E-Mail verschickt aber die DB nicht aktualisiert.

Wenn ich den Captcha rauslösche funktioniert alles wie gewünscht.

**Code**
```
generate_key|activation_key
text|email|E-Mail:|

captcha|Bitte geben Sie den entsprechenden Sicherheitscode ein. Sollten Sie den Code nicht lesen können klicken Sie bitte auf die Grafik, um einen neuen Code zu generieren.|Sie haben den Sicherheitscode falsch eingegeben.

validate|email|email|Bitte geben Sie die E-Mail ein.
validate|empty|email|Bitte geben Sie Ihre E-Mail ein.

action|db_query|UPDATE rex_ycom_user SET activation_key = ? WHERE email = ?|activation_key,email
action|tpl2email|resetpassword_de|email|
```

PS: Den Teil `action|copy_value|email|login` habe ich entfernt und direkt das richtige Feld bei db_query angegeben.

Danke und Gruss
Toby

**Comment by dergel** [comment]
sollte nun in der Doku besser beschrieben sein
