### ISSUE TITLE
PasswordCreator Troubles 

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_ycom#197]
Bei Erstellen eines Accounts Nutzers kann der Admin sich ein Passwort generieren lassen. Leider ist diese Funktion an die Passwortregeln gekoppelt.
Wenn ich nun keine Regeln ausser einer minimalen Passwortlänge einstelle, bekomme ich extrem schwache Passworte vorgeschlagen (exakt die minimale Länge, nur Buchstaben).
Ich muss also meinen Nutzern irre Passwortrestriktionen vorgegeben, damit ein sicheres Passwort generiert wird.
Sinnvoller wäre es, für den Passwortgenerator eigene Regeln erstellen zu können.

**Comment by alexplusde** [comment]
Passwort-Regeln sollte man im YCom-Backend festlegen können (und dann notfalls im Formular überschreibbar machen). Es sollte eindeutige Fehlermeldeungen geben, wenn Passwortregeln nicht eingehalten wurden. 

Manchmal kommt sogar die Meldung "Passwort wurde aktualisiert." Da tappt man als Entwickler im Dunkeln.

**Comment by dergel** [comment]
@alexplusde Deine Punkte sind andere Aspekte die wir auch diskutieren können.

@IngoWinter die Generierung ist in der Tat ein Problem. Wahrscheinlich nur so lösbar wie du schreibst. Muss es mir noch genauer ansehen.

**Comment by alexplusde** [comment]
Sorry, kannte den Passwort-creator gar nicht.

Chrome schlägt inzwischen auch Passwörter vor. Benötigt man das Feature grundsätzlich?

**Comment by dergel** [comment]
gut ist das schon, weil man ja eigene Regeln hat und diese dann auch sicher direkt passen. Ich weiss nur nicht ob ein extra eigenes Regelpaket das ganze überfrachtet und man nicht eine eigene Logik finden kann. z.B. dass man die Mindestlänge des Passwortes einfach verdoppelt. Dann sollte es ja bereits in den allermeisten Fällen gut klappen, denke ich. @IngoWinter Was meinst du ?

**Comment by IngoWinter** [comment]
Gute Idee. Man könnte die einzelnen Passwortrestriktionen durchgehen und für jede Restriktion einen Defaultwert setzen, so dass auch ohne Regeln immer ein sicheres Passwort generiert wird:
```
$mindestLaenge = $mindestLaenge > 15 ? $mindestLaenge : 16;
$anzahlGrossbuchstaben = $anzahlGrossbuchstaben ?: 1;
$anzahlKleinbuchstaben = $anzahlKleinbuchstaben ?: 1;
$anzahlSonderzeichen = $anzahlSonderzeichen ?: 1;
$anzahlZahlen = $anzahlZahlen ?: 1;
```
