### ISSUE TITLE
 Registrierungsbestätigung: Formularcode in Anleitung falsch

### ISSUE THREAD

**Issue by godsdog** [yakamara/redaxo_ycom#198]
Das Beispiel in der Anleitung für die Registrierungsbestätigung ist nicht korrekt:

`validate|ycom_auth_login|activation_key=rex_ycom_activation_key,id=rex_ycom_id|status=0|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status`

Muss lauten: (email statt id)

`validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=0|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status`

#199

**Comment by ynamite** [comment]
FYI in der Doku heisst es zudem `status=1`, was falsch ist.

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_ycom/edit/master/plugins/docs/docs/de_de/main.register.md
