### ISSUE TITLE
Passwort vergessen - yform doppelt abgeschickt

### ISSUE THREAD

**Issue by Dollique** [yakamara/redaxo_ycom#200]
Hallo Zusammen

Ich bin etwas unsicher, ob das Problem von yform oder ycom ist.

Mein Passwort-Vergessen Formular (Kopiert von der ycom Dokumentation) wird doppelt ausgeführt.

Mein Code ist wie folgt:
```
generate_key|activation_key

text|email|E-Mail:|
validate|email|email|Bitte geben Sie die E-Mail ein.
validate|empty|email|Bitte geben Sie Ihre E-Mail ein.

text|login|Benutzername:|
validate|empty|login|Bitte geben Sie Ihren Benutzernamen ein.

validate|existintable|login,email|rex_ycom_user|login,email|Es besteht kein Login mit diesen Angaben.|status=1

action|db_query|UPDATE rex_ycom_user SET activation_key = ? WHERE email = ?|activation_key,email
action|tpl2email|resetpassword_de|email|
```

Das E-Mail geht doppelt raus mit zwei verschiedenen Activation Keys. Dies bedeutet, dass das Formular zweimal ausgeführt wird.

Mache ich etwas falsch? Ist es ein yform oder ycom Problem?

Danke und Gruss
Toby

**Comment by dergel** [comment]
Wahrscheinlich wird der Artikel 2 mal ausgeführt. Das kann passieren wenn man den Inhalt z.B. ausliest und zu sehen ob etwas drin ist.. Ich denke, da liegt das Problem, hat nichts mit YCom oder YForm zu tun.

**Comment by georgkaser** [comment]
Ich hab hier das Problem, dass das Formular im Backend immer zum Logout führt (wenn ich es bearbeiten möchte). Wenn ich mich dann gleich wieder einlogge, bekomme ich einen "CSRF-Token ungültig" Fehler. Irgendwas passt da noch nicht so ganz :)

**Comment by alexplusde** [comment]
Anderes Problem, eigenes issue bitte
