### ISSUE TITLE
Loginseite, Registerseite, Fehlerseite unterschiedlich für eingeloggt und nicht eingeloggt unterscheiden

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#201]

**Comment by alexplusde** [comment]
Eine bei uns durchaus öfter vorhandener Anwendungsfall wäre sogar die Unterscheidung auf Gruppenebene. Evtl. gleich dorthin verschieben?

**Comment by dergel** [comment]
Dieses Issue erschließt sich mir nicht mehr ... Wenn eingeloggt, wird Log-in und Register, sofern richtig eingestellt, als nicht zugreifbar angezeigt und es sollte die Fehlerseite kommen (da kein Zugriff erlaubt). Sofern man dort unterschiedliche Meldungen machen will, kann man dies machen, indem man eingeloggt und nicht eingeloggt unterscheidet.

**Comment by alxndr-w** [comment]
Ich könnte mir vorstellen, dass man pro Gruppe oder im Multidomain-Kontext je nachdem, auf welchen Bereich man zugreifen wollte, eine unterschiedliche Fehlerseite / Loginseite präsentiert bekommt.
