### ISSUE TITLE
Passwort zurücksetzen Formular

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#203]
m.E. fehlt ein Redirect zum Artikel

`action|redirect|20||`

vollständig:
```
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0

validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=1|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status
action|ycom_auth_db|update
action|redirect|20||
```

**Comment by dergel** [comment]
```
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0

validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=1|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status

action|ycom_auth_db|update
action|html|<b>Sie sind eingeloggt. Das Passwort kann nun geändert werden.</b>
```

so siehts eigentlich aus, in der aktuellen Doku. und hier wird eine passende Meldung ausgegeben, gerne aber in der Doku ergänzen. Ist nun auch netter aufbereitet :)

**Comment by alexplusde** [comment]
Das von dir hat bei mir zu einer Weiterleitungsschleife geführt, ohne expliziten redirect.

Welche Einstellungen müssen ggf. in der Konfigurationsseite vorgenommen sein?

**Comment by alexplusde** [comment]
Das wird bisher nicht klar und ist auch komplex. Viele setzen doch als Ziel wieder die Login-Seite, nicht eine separate logout-Seite.

Vor allem geht es hier aber um die Passwort-zurücksetzen-Seite?!

**Comment by fietstouring** [comment]
Versuche gerade das laut Douk zu implementieren, allerdings kommt bei mir immer die Fehlermeldung "Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen", was mache ich falsch? Die Seite hat Zugriff für Alle.

**Comment by fietstouring** [comment]
https://github.com/yakamara/redaxo_ycom/blob/d68e901a3107bc4f0322f48ddb57129b2640f75f/plugins/auth/lib/ycom_auth.php#L437

Wenn ich das hier auskommentiere dann funktioniert der Login mit activation_key
