### ISSUE TITLE
Redirect auf article_id_jump_logout geht nicht

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_ycom#204]
Der Redirect bei `$login_status == 3` wird nicht ausgeführt, weil `$params['redirect']` schon einen Wert hat.

**Comment by dergel** [comment]
kannst du mir genauer sagen an welcher Stelle ich da nachschauen muss ?

**Comment by dergel** [comment]
gerne nochmal mit der aktuellen github version gegenprüfen. Es wird geprüft ob der referer direkt aufs logout geht und entsprechend entfernt.. und nur wenn man zur aktuellen seite keine permission hat, dann wird ein referer gesetzt.
