### ISSUE TITLE
Login-Einstellungen unplausibel => führt zu Fehler

### ISSUE THREAD

**Issue by dpf-dd** [yakamara/redaxo_ycom#205]
betrifft Version: yCom 3.0dev

In den Einstellungen gibt es ein Feld "Login", mit dessen Hilfe man die Login-Referenz einstellen kann (also Frontend-Login per Email-Adresse, per Login-Name etc. pp)
Standardmäßig steht die Auswahl nach dem Installieren des AddOns auf "html1" - aber es gibt keine SQL-Spalte "html1" - deswegen folgt dann beim Frontend-Login eines angelegten yCom-Users ein Whoop-Error:
```"Error while executing statement "SELECT `rex_ycom_user`.* FROM `rex_ycom_user` WHERE `` = :p1 AND status > 0 ORDER BY `login` DESC" using params {"p1":"Stefan"}! SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause'```

Nach Umstellung auf "Login" hat alles geklappt und der Fehler trat nicht mehr auf. Die einzig sinnvolle zweite Auswahl wäre "Email", dann muss sich jeder User im Frontend eben mit Email statt Login-Name einloggen. Alle anderen Auswahloptionen sind eigentlich überflüssig und sollten irgendwann da verschwinden (aber Jan arbeitet auch gerade an dem AddOn)

Außerdem wäre es schön, wenn auch die Einstellungsseite eine kleine Doku/Hilfe bekommt, da sich der Sinn einiger Einstellungen nicht unbedingt von selbst ergibt.
Ansonsten aber natürlich GROSSES DANKE für das AddOn, es gefällt mir sehr sehr sehr gut... :)

**Comment by dergel** [comment]
habs bereits angepasst. es gibt nun nur noch die auswahl nach login oder email und das wird auch default gesetzt beim installieren.
