### ISSUE TITLE
URL-Parameter nach erfolgreichem Redirect entfernen

### ISSUE THREAD

**Issue by dpf-dd** [yakamara/redaxo_ycom#206]
Wenn ich mich erfolgreich ausgeloggt habe, bleibt in der eingestellten Redirect-URL immer "?rex_ycom_auth_ref=" an der URL hängen...
Es wäre schön, wenn leere GET-Variablen nicht übergeben werden, sodass ich eine saubere URL im Browser stehen habe :)

EDIT/Korrektur:
Ich hab da was verwechselt. Der "Fehler" tritt nicht erfolgreichem Logout auf, sondern bei einem fehlgeschlagenem Login...

Vielen Dank! :)

**Comment by dergel** [comment]
Das Prinzip ist nun anders und das Feld wird in das Formular übergeben. Sollte nun funktionieren. ich schliesse einfach mal .. bei Problemen bitte melden. Achtung, ein Update zieht noch ein paar Änderungen mit sich. Wird noch dokumentiert
