### ISSUE TITLE
Neues media auth - PlugIn - Kategorien schützen

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#207]
Ich würde es begrüßen komplette Kategorien schützen zu können, anstelle dies einzeln über das Medium zu regeln.  Das hat sich als sehr praktikabel bei meinen Kunden erwiesen und ist auch für den Admin übersichtlicher.

**Comment by dergel** [comment]
wird leider nicht gemacht werden, da sich auch im medienpool einiges ändern wird und kategorien nicht mehr der primäre aufhänger ist.

**Comment by skerbis** [comment]
Ok, danke
