### ISSUE TITLE
Problem im Beispiel-Code der Doku

### ISSUE THREAD

**Issue by dpf-dd** [yakamara/redaxo_ycom#209]
Im Beispiel-Code im Reiter Dokumentation ist bei dem Punkt "Registrierung" keine Checkbox für die Nutzungsbedingungen in der Pipe-Notation enthalten.

Wenn man das also 1:1 so verwendet, dann funktioniert zwar das Anlegen eines Users, aber in der User-Tabelle wird die Checkbox "Nutzungsbedingungen akzeptiert" **NICHT** angehakt sein.
Wenn dann bei den Community-Einstellungen bei den Weiterleitungen das optionale Feld "wenn Nutzungsbedingungen noch nicht bestätigt wurden" ausgefüllt ist, dann werden die angeklickten Links eines eingeloggten Users IMMER auf die hinterlegte Seite umgeleitet.

**Das Verhalten an sich ist logisch und korrekt**, aber dann ist das im Beispiel-Code etwas irreführend.
Entweder man nimmt die Checkbox mit den Nutzungsbedingungen mit in die Beispiel-Pipes des Registrierungsformulars - oder man übergibt die "1" mit einem hidden-Feld ``````hidden|termofuse_accepted|1```.

Nur so wäre sichergestellt, dass ein Anwender der den Beispielcode als Basis nutzt und alle Einstellungen ordnungsgemäß ausfüllt keine Probleme bekommt...

**Comment by dergel** [comment]
sollte aber nur zum Problem führen, wenn in den YCom Einstellungen auch ein Link zu den Nutzungsbedingungen drin ist.. Wenn der nicht existiert, dann sollte es passen, wenn der gesetzt ist, muss im Registrierungsformular das entsprechend mit einer Checkbox abgefragt werden. Gerne in die Doku aufnehmen
