### ISSUE TITLE
Neues auth_media plugin schützt Dateien nicht wirklich

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#211]
Ich habe das neue Plugin in Redaxo 5.6 mit den nötigen Änderungen am Start. In den Einstellungen des auth_media Plugins ist die Authentifizierung aktiviert und "Header 'Permission denied' ausgewählt". Wenn ich nun die Datei direkt aufrufe, z.B.  www.meinserver.de/media/geschuetzteDatei.pdf, kann ich diese Problemlos aufrufen obwohl im Medienpool die Option Zugriffsrechte auf "Zugriff für eingeloggte User" gesetzt ist und Gruppenrechte auf "Für alle, egal welche Gruppe. Kann es sein, dass hier noch einen .htaccess Datei im /media/ Ordner fehlt?

**Comment by skerbis** [comment]
Ist yrewrite installiert?

**Comment by TobiasKrais** [comment]
Ja. Version 2.3. Die .htaccess Datei ist gesetzt.

**Comment by skerbis** [comment]
ich sollte besser lesen... Redaxo 5.6 ist das problem, du brauchst 5.7

**Comment by skerbis** [comment]
siehe Titel des commits: https://github.com/yakamara/redaxo_ycom/commit/e455f001d05116f3c4b82a2909cc81a3357d9b62

**Comment by dergel** [comment]
Vorraussetzungen
- REDAXO 5.7 oder die ExtensionPoint im media_manager nachgerüstet
- YRewrite mi Standard htaccess welches jeden direkten Aufruf einer media-Datei über den media_manager_schleift
- Rechte auf Datei passend gelegt.

**Comment by TobiasKrais** [comment]
Ich melde mich in ein paar Tagen nochmals. Danke für die Hinweise!

**Comment by dergel** [comment]
achtung .. wenn du im Backend eingeloggt bist, hast du automatisch zugriff auf die Datei.. als da erstmal ausloggen - sonst ist das Ergebnis verfälscht

**Comment by dergel** [comment]
ich schliess das hier

**Comment by TobiasKrais** [comment]
Doch funktioniert wirklich. Auf meinem Live Server geht es, nur auf meinem Testserver nicht. Das muss  also am Server liegen.

Was wirklich blöd ist: meine CSS Dateien werden nicht als CSS ausgeliefert. Bisher habe ich in der .htaccess die fragliche Zeile entfernt, aber das geht jetzt nicht mehr, da ich sie wegen der geschützten Dateien brauche. :-(
