### ISSUE TITLE
YCom-Identität wechseln

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#212]
Es wäre super, als Entwickler die Identität eines YCom-Nutzers annehmen zu können, um Dinge im Frontend zu testen - analog zur REDAXO-Backend-Seite für Benutzer.

**Comment by skerbis** [comment]
Entspricht: 
https://github.com/yakamara/redaxo_ycom/issues/91

**Comment by dergel** [comment]
stimmt.. schliesse ich hier .. ist aber eingeplant
