### ISSUE TITLE
Wording YCom / Community, User

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#215]
Wäre es möglich, `User` in Benutzer zu ändern und `Community-Addon` Frontend-Authentifizierung? Bei User sehe ich keine Notwendigkeit fürs Englische, und Community-Addon finde ich nicht so treffend, da eine Community ja nur ein Anwendungsfall von vielen für so einen geschützten Bereich ist.

**Comment by dergel** [comment]
Verstehe deinen Ansatz.. Und User vs REDAXO-User fände ich noch schwierig.. und Community AddOn stimme ich zu .. aber Frontend-Authentifizierung finde ich keine richtigen Namen.. Klingt eher wir eine Funktion.. aber insgesamt bin ich da offen. Vielleicht finden wir was passenderes

**Comment by alexplusde** [comment]
Bringe hier noch `Frontend-Login` als Vorschlag. `Kundenbereich`, `geschützter Bereich` oder `Mitgliederbereich` finde ich auch sehr treffend. Bei Mitglieder / Kunden hätte man dann auch gleich das Wording für die User, die sich mit einem REDAXO-Backend-User dann auch nicht in die Quere kommen.

**Comment by dergel** [comment]
Ich schließe es wieder. Das muss man mal so bei einem Treffen diskutieren.
