### ISSUE TITLE
Einstellungen: Beschriftung verbessern, Layout

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#219]
![image](https://user-images.githubusercontent.com/3855487/48131884-e4b4f580-e291-11e8-850b-6cba7739ed88.png)

Hier würde ich die Beschriftung aufsplitten in Label und Notice (mit Erläuterungen und Beispiel-Code für den Zugriff auf den Wert), statt so viel Text zu schreiben.

Außerdem würde ich empfehlen, analog zu PHPMailer hier zweispaltig zu arbeiten. Niemand benötigt hier die volle Breite für die Eingabefelder.

@dergel könntest du das vorbereiten, dann würde ich mich um die Textänderungen kümmern.

**Comment by dergel** [comment]
Hier möchte ich eigentlich keinen Beispielcode reinsetzen. was aber auch schwer zu verstehen finde, sind die ConfigIDs für die Nutzung und auch was es bedeutet wenn man die Passwortseite festlegt, oder die Nutzungbedingungen, weil ab dem Moment ist es wichtig was der User bei sich angehakt hat, weil man als Frontenduser ansonsten gezwungen wird, zunächst ein neues Passwort zu setzen oder die (neuen) Nutzungsbedingungen abzuhaken,

**Comment by alexplusde** [comment]
Deswegen bitte zumindest ein Notice-Feld zur Verfügung stellen, ich kümmere mich um einen verständlichen Text dort und in der Doku

**Comment by alexplusde** [comment]
In #231 habe ich versucht, entsprechende Beschreibungen einzufügen. Diese könnten in der Doku entfallen, wenn man sie als Notice hinzufügt.

**Comment by alexplusde** [comment]
Habe letzte Woche meinen Kollegen - YCom-unerfahren - alles mal ausprobieren lassen und bin selbst darüber gestolpert, dass nicht klar war, was die Einstellungsseiten bewirken. Insb. bei Passwort zurücksetzen. 

Haben gerade ein Projekt, bei dem wir alles brauchen. Ich würde die Einstellungsseite gerne direkt umbauen in ein rex_config_form und anschließend die Labels/Notices verbessern. Wärst du damit d'Accord @dergel?

**Comment by dergel** [comment]
ich muss wahrscheinlich an der Seite was erweitern, deswegen im Moment lieber noch nicht.. Die Notices und Co. kannst du natürlich dennoch seehr gerne machen. Würde mich freuen..

**Comment by dergel** [comment]
Ich glaube die Zeit fehlt dir und mir. Ich verlagere das so: wenn jemand ein Problem mit einer Beschreibung hat, gerne melden, und ich schaue wir man das umformuliert (oder lasse mir auch gerne einen Text zukommen)
