### ISSUE TITLE
Kleiner Trick: Wenn nach Aktivierungslink Klick direkt wieder ausgeloggt werden soll.

### ISSUE THREAD

**Issue by godsdog** [yakamara/redaxo_ycom#221]
Einfach im Formular auf der Bestätigungsseite:
`action|ycom_auth_db|update`
`action|ycom_auth_db|logout`

Kunde wollte nicht, dass der User sofort eingeloggt ist.

**Comment by dergel** [comment]
gerne in die doku aufnehmen

**Comment by alexplusde** [comment]
In #231 geschlossen.
