### ISSUE TITLE
Große Dateien werden nicht ausgeliefert

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#223]
Ein Kunde von mir hat viele MP4 Videos, TIF und andere Dateien die durch den Redirect auf die Redaxo Rechteprüfung nicht ausgeliefert werden können. Warum? Die maximale Speichergrenze wird überschritten.

**Comment by TobiasKrais** [comment]
Eine Methode wäre die Authentifizierung über Cookies zu machen. Das habe ich jetzt noch nicht fertig gedacht, aber auf einer Nicht Redaxo Seite habe ich das so gelöst:
<IfModule mod_rewrite.c> RewriteEngine On RewriteBase / RewriteCond %{REQUEST_URI} ^.*media/.* RewriteCond %{HTTP_COOKIE} !^.*ycom_is_authorized.*$ [NC] RewriteRule \.(.*)$ - [F] </IfModule>

**Comment by alexplusde** [comment]
Das ist meines Wissens kein zentrales YCom-Problem, sondern ein YRewrite/Core-Problem und wird gerade gelöst, oder? @dergel @skerbis @staabm

**Comment by staabm** [comment]
Sollte mit 5.7-beta behoben sein. Kann das jmd bestätigten?

**Comment by TobiasKrais** [comment]
Habs gerade mit der 5.7-beta1 getestet. Funktioniert hervorragend. Herzlichen Dank!
