### ISSUE TITLE
Fehler Class wird nicht durchgereicht

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#224]
In den folgenden Zeilen müsste `$this->params['error_class']` als `value` notiert werden.

https://github.com/yakamara/redaxo_ycom/blob/bf7087cd88bd4edfe36158d7bdb89c0057dccd3a/plugins/auth/lib/yform/validate/ycom_auth_login.php#L29
https://github.com/yakamara/redaxo_ycom/blob/bf7087cd88bd4edfe36158d7bdb89c0057dccd3a/plugins/auth/lib/yform/validate/ycom_auth.php#L24
https://github.com/yakamara/redaxo_ycom/blob/bf7087cd88bd4edfe36158d7bdb89c0057dccd3a/plugins/auth/lib/yform/validate/ycom_auth.php#L47
https://github.com/yakamara/redaxo_ycom/blob/bf7087cd88bd4edfe36158d7bdb89c0057dccd3a/plugins/auth/lib/yform/validate/ycom_auth_password.php#L12
https://github.com/yakamara/redaxo_ycom/blob/bf7087cd88bd4edfe36158d7bdb89c0057dccd3a/plugins/auth/lib/yform/validate/ycom_auth_password.php#L20

**Comment by dergel** [comment]
ist nun gemacht ..
 Bei redaxo_ycom/plugins/auth/lib/yform/validate/ycom_auth_login.php ist es nicht nötig, da kein Feld dafür vorhanden ist, und daher die error_class sowieso nicht greift.
