### ISSUE TITLE
Feld "termofuse_accepted" sollte "termsofuse_accepted" heißen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#232]
Da es die "Terms of Use" sind, nicht "Term of Use"

**Comment by dergel** [comment]
nerviges Thema aber natürlich richtig .. ist nun angepasst, auch mit update des entsprechenden Feldes.

**Comment by alexplusde** [comment]
Super. Auch in der readme und im Change log angepasst?

**Comment by dergel** [comment]
nein .. mache ich immer erst beim release
