### ISSUE TITLE
rex_ycom_navigation entfernen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#233]
Da im Prinzip unnötig, wenn man weiss wie man die normale rex_navigation ergänzen muss.. Im Zuge des Aufräumens finde ich das sinnvoll.
@alexplusde Kannst du das in der Doku anpassen ?

```
$nav = rex_navigation::factory();
$nav->addCallback('rex_ycom_auth::checkPerm');
$nav->show();
```

**Comment by alexplusde** [comment]
Dann bitte deprecated drin lassen, dass Zeit zum migrieren bleibt. 

Kannst du hier auf Github Doku-Labels an mich zuweisen? (Ich darf bisher nicht)

**Comment by alexplusde** [comment]
Danke! Dir auch :)

**Comment by dergel** [comment]
ich werde die direkt entfernen.. das ist eine miniänderung und ist ein major release..

**Comment by alexplusde** [comment]
Wäre es sinnvoll, wenn die Klasse als Rückgabewert nicht null hat, sondern das rex_navigation-Objekt, um das ganze zu kürzen?

Vorschlag:
```
$nav = rex_navigation::factory()->addCallback('rex_ycom_auth::checkPerm');
$nav->show();
```

Oder gibt es einen Grund, warum addCallback hier null zurückwirft?

**Comment by dergel** [comment]
wäre sinnvoll.. issue bei redaxo

**Comment by dergel** [comment]
ich habe die doku angepasst.. falls du was ergänzen willst, @alexplusde gerne :)

**Comment by alexplusde** [comment]
Ich wollte noch Warten wegen des Callbacks, aber passt soweit.

**Comment by skerbis** [comment]
Ich kann den Hinweis zur Navigation in der Doku nicht entdecken.
