### ISSUE TITLE
Rgeistrierungsbestätigung: {{ csrf.error }}

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#237]
meine Registrierungsbestätigung sieht so aus*

```
hidden|status|0
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|false
 
validate|ycom_auth_login|activation_key=activation_key,email=email|status=-1|Die Registrierung konnte nicht bestätigt werden. Wurde sie vielleicht schon bestätigt? |id,status,activation_key,email

action|ycom_auth_db|update
hidden|status|1

action|html|<div class="alert alert-success alert-dismissible" role="alert"><h2>Vielen Dank!</h2><p>Die E-Mail wurde bestätigt.</p></div>
```

Trotz `objparams|csrf_protection|false` kommt immer nur die Ausgabe von `{{ csrf.error }}` sofern der Benutzer die Registrierung bestätigen möchte.

Kann ich das irgendwie mit den vorhanenden Versionen fixen? Ein Update möchte ich Ohne Dev Umgebung nicht machen. Selbe wenn. Wäre der Fehler dann gefixt?

- REDAXO  5.6.4
- PHP     7.2.10-0ubuntu0.18.04.1 
- yform   2.3
- ycom    2.1

LG
Oliver

**Comment by alexplusde** [comment]
Ist es möglich, dass du YForm 3 und YCom 3 einsetzt und schaust, ob das Problem da behoben ist? Bzw. du kannst es auch mal mit der aktuellen Doku abgleichen. CSRF sollte ja eigentlich an bleiben.

**Comment by olien** [comment]
Ok. Ich habe jetzt (fast) alle Updates gemacht (ausser den Core).

 REDAXO 5.6.47  | PHP 7.2.10-0ubuntu0.18.04.1
 yform   3.0-beta7 
 ycom  3.0-beta4

Die Registrierung und die Registrierungsbestätigungen funktionieren jetzt.
Was nicht mehr Funktioniert ist die Anmeldung (Komisch. Ist nicht mein erstes Formular)

Egal wie ich die Felder ausfülle erhalte ich:

_{{ Bitte geben Sie die E-Mail ein }}
{{ Bitte geben Sie ein Passwort ein }}
{{ Login ist fehlgeschlagen }}_

--
Auch wenn ich das Formular mit dem yForm Modul aus der Doku nutze funktioniert der Login nicht.

Anscheinend greifen die Validierenden so gar nicht...

--

Das Formular sieht so aus:

```<?php


$ycom_user = rex_ycom_auth::getUser();

$formular = '';
$yform = new rex_yform();
$form_data = '

objparams|form_id|login
objparams|form_name|login
objparams|form_skin|bootstrap
objparams|submit_btn_show|0

ycom_auth_form_info|label||{{ Benutzer wurde ausgeloggt }}|{{ Login ist fehlgeschlagen }}|{{ Benutzer wurde erfolgreich eingeloggt }}|

html||<div class="row">
html||<div class="large-6 medium-4 columns">
  
  ycom_auth_form_login|email| {{ E-Mail }} |
  validate|empty|email| {{ Bitte geben Sie die E-Mail ein }} 

html||</div>
html||<div class="large-6 medium-4 columns">

  ycom_auth_form_password|passwort|{{ Passwort }} |
  validate|empty|passwort| {{ Bitte geben Sie ein Passwort ein }}   

html||</div>
html||<div class="large-12 medium-12 columns">
html||<input type="submit" class="button" value=" {{ Login }} ">
html||</div>
html||</div>
';

$yform->setFormData($form_data);

$url = rex_getUrl($this->getArticleId());
$yform->setObjectparams("form_action", $url);

if(!rex::isBackend()) {

if (!$ycom_user) {
  echo $yform->getForm();
} 

} else {
 echo 'Das Formular wird ausgegeben.';
} 

```


Hat jemand vielleicht eine Idee??

LG
Oliver

**Comment by dergel** [comment]
Leider kann ich das nicht nachvollziehen.. sowas lieber im Slack .. Ich glaube es liegt kein Fehler vor.
