### ISSUE TITLE
cookie path auf "/" setzen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#238]
oder in der config.yml als info rein

**Comment by dergel** [comment]
das nicht cookies auf irgendwelchen unterordnern liegen, die man nicht so ohne weiteres erkennt und eventuell sogar problematisch sind und sich gegenseitig überschreiben

**Comment by dergel** [comment]
ist nun default auf / gesetzt

**Comment by alexplusde** [comment]
vermutlich Ursache für #259 #250 und weitere...
