### ISSUE TITLE
Einloggen über Drittanbieter

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#240]
* Facebook
* SAML
* OpenAuth
* LinkedIn

Allgemeinen Weg überlegen.

**Comment by dergel** [comment]
SAML ist bereits drin und müsste noch in die Doku.

**Comment by alexplusde** [comment]
Stark! Habe leider keine Ahnung davon, kannst du mir nochmal etwas schreiben dazu?

(Wäre das nicht auch was für den Core)?

**Comment by dergel** [comment]
SAML Doku ist nun auch drin.

**Comment by alexplusde** [comment]
Warum wird die SAML-Config-Datei in den project-data-Addon-Ordner kopiert und nicht ins data-Verzeichnis von YCom?

**Comment by dergel** [comment]
aehh .. stimmt. Keine Ahnung warum

**Comment by dergel** [comment]
done

**Comment by alexplusde** [comment]
Close?

**Comment by skerbis** [comment]
Wieso da fehlen doch noch ein paar. Oder sehe ich das falsch?

**Comment by dergel** [comment]
genau.. bisher ist nur SAML drin

**Comment by alexplusde** [comment]
Hatte ich missverstanden, weil hier closed steht:
![image](https://user-images.githubusercontent.com/3855487/69443662-2dc9d180-0d4f-11ea-8475-ade574a021db.png)

**Comment by alexplusde** [comment]
> LinkedIn ist SAML 2.0-zertifiziert, jedoch besteht derzeit keine Unterstützung für OAuth2.0 oder OpenID.

https://www.linkedin.com/help/linkedin/answer/102009/einrichten-von-single-sign-on-sso-fur-linkedin-produkte-uberblick?lang=de

**Comment by dergel** [comment]
LinkedIn könnte man wirklich mal testen. Bisher haben wir

- cas
- saml2
- oauth

das sind die quasi standards und sollten alles nötige abdecken. Ich nehme gerne weitere Dinge entgegen. für mich reicht das aber.

**Comment by skerbis** [comment]
👍
