### ISSUE TITLE
Doku: Funktion "eingeloggt bleiben" besser erklären

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#242]
Trotz erfolgreichen Logouts und einem `null` als Rückgabewert von `rex_ycom_auth::getUser();` bin ich sofort wieder eingeloggt, wenn ich auf einen geschützten Artikel gehe. Hier wird die SESSION scheinbar nicht richtig entfernt. Wie kann das sein?

Test-Zugang kann ich geben.

**Comment by alexplusde** [comment]
It's not a Bug, it's a feature.

Das Verhalten mit dem Mustercode "eingeloggt bleiben" Muss in der Doku besser erklärt werden.

**Comment by dergel** [comment]
ja.. das kann sogar ein Problem sein.. Es wird ein Cookie abgelegt, aber je nach Config in redaxo, kann der Cookie in / liegen, oder in dem Ordner wo auch das Login auftaucht.. und wenn der 2. Fall auftritt, braucht es schon Mühe zu erkennen, dass es dort einen Cookie gibt, weil dieser nicht direkt ersichtlich ist.

**Comment by alexplusde** [comment]
Sollte ein Logout nicht trotzdem ein erneutes versehentlich anmelden verhindern?

**Comment by dergel** [comment]
ja, tut er das nicht ?.. die aktuelle github version verwendet ?

**Comment by alexplusde** [comment]
Aktuelle Installer-Version und da tut es nicht. Habe da auch keinen FTP-Zugriff, kann es also nicht direkt dort testen.

**Comment by skerbis** [comment]
Zipinstaller könnte da helfen 👆

**Comment by dergel** [comment]
Sollte es mittlerweile tun. Einerseits weil beim Cookiesetzen jetzt immer der Pfad / verwendet wird. Zusätzlich werden nun auch die YCom Variablen in der Session wie auch der YCom Cookie gelöscht

**Comment by alexplusde** [comment]
(für die Doku offen lassen)

**Comment by dergel** [comment]
Ich finde gerade keine info, die so in der Doku nicht mehr stimmt. Das ganze Teil ist umgebaut und jeder Login bekommt seinen einen Sessiondatensatz. D.h. es werden mehrere Sessions erfasst und auch eingeloggt bleiben wird dort erfasst. Eingeloggt bleiben, bleibt eigentlich "unendlich" und man müsste diese Sessions im Backend manuell löschen oder einen Cronjob schreiben, der diese nach einer gewissen Zeit zwangslöscht. Sofern jemand was dazu ergänzen will, gerne - aber das issue hier schließe ich.

**Comment by alxndr-w** [comment]
Ist `unendlich` hier sinnvoll? Sollte nicht ein Cronjob bspw. nach einer festgelegten Zeit dadurch auch Leute zwangs-ausloggen können? Werden SESSION-Cookies nicht eh ggf. clientseitig gelöscht und wovon ist das abhängig?

Ich finde das ziemlich unklar.

**Comment by dergel** [comment]
Eingeloggt bleiben setzt einen eigenen Cookie, der dann nichts mit einer PHP Session zu tun hat. D.h. beim client wäre eine Cookielaufzeit möglich, dann würde aber dieses "Eingeloggt bleiben" Session noch im System bleiben - und ist dort dann auch sichtbar und löschbar. Einen Cronjob könnte man sich immer nach belieben anlegen, der dann noch offene Sessions löschen kann.

Im Prinzip ist das ein Abbild, der in REDAXO 5.15 neuen Form der Sessionverwaltung

**Comment by fietstouring** [comment]
ich hab das ganze genauer getestet. Der Cookie welcher gesetzt wird wenn das "stayfield" aktiviert ist beim Login hat eine Laufzeit von 1 Jahr. Die Einstellung im Backend scheint nicht zu greifen. **Ich nehme die sollte das Ablaufdatum setzen, oder nicht?** (bin in der Version 4.2) In der function setStayLoggedInCookie(string $cookiekey) wird der auf 1 Jahr gesetzt. Sollte da nicht das Setting **auth_cookie_ttl** verwendet werden?

Die Browser führen die letzte Session auch ohne Cookie weiter wenn man ihn neu startet. Wenn man will dass die Session endet bei einem Browserrestart muss man eine andere Lösung einbauen. Wofür session_max_overall_duration und session_duration aus den YCom Settings verwendet werden habe ich nicht ganz gecheckt.
