### ISSUE TITLE
Umbau Loginprozess / Logout

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#243]
Im Moment kann man sich auf jeder Seite einloggen. 
Sollte so sein, dass man sich nur auf der Loginseite einloggen kann, am besten so wie bei Logout auch, rein über die YForm Felder eintragbar. Eventuell muss nur der automatisierte Prozess geändert werden.

**Comment by alexplusde** [comment]
Finde ich nicht gut. Was ist, wenn man auf jeder Seite ein Login-Formular zur Verfügung stellen möchte?

**Comment by skerbis** [comment]
Was @alexplusde sagt. Evtl. möchte man das LogIn ja z.B. als Modal anbieten.

**Comment by dergel** [comment]
Modul und eigene Loginseiten sind dann immernoch möglich.. Nur die Technik dahinter dann geordneter. Man kann auch unterschiedliche Loginseiten bauen. Nur über jede Seite sich einloggen zu können (über die URL) ist keine gute dauerhafte Lösung. Darum geht es mir in diesem Issue

**Comment by dergel** [comment]
Ist nun umgebaut. Hat diverse Gründe, aber vor allem, dass es überschaubarer ist und man auch andere Authentifizierungsmethoden leichter einbauen kann.

- es ist nun nicht mehr möglich sich auf jeder Seite "einfach so" einzuloggen. 
- die ganzen rex_ycom_auth_login/passwort/stay.. Variablen entfallen. Loginformular muss man selbst erstellen und auch nur da wird man authentifiziert (Erklärung in der Doku kommt noch)
