### ISSUE TITLE
Registrierung: Reload nach Bestätigung

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#245]
action|html|<b>Vielen Dank, Sie sind nun eingeloggt und haben Ihre E-Mail bestätigt</b>

Diese Meldung wird ausgegeben, wenn der Nutzer auf den Bestätigungs-Link geklickt hat. Eigentlich müsste jetzt noch ein reload/redirect erfolgen, damit der eingeloggt-Status in der gesamten Seite sichtbar ist. Denn wenn davor schon Code ausgegeben wurde (z.B. die Navi), dann ist der Login-Vorgang dort noch nicht berücksichtigt worden.

**Comment by dergel** [comment]
du meinst bei der Registrierungsbestätigung ? .. das könntest du dann ja als action einbauen.. Ist aber eher eine Frage was man will. Bestätigung ohne direkt eingeloggt sein ist meines Erachtens üblicher .. Aber das darf man selbst entscheiden und wäre vielleicht sogar eher ein Thema für die Doku, oder ?

**Comment by alexplusde** [comment]
Im Moment ist man immer direkt eingeloggt. Wie verhindere ich das?

**Comment by dergel** [comment]
es gibt soweit ich weiss eine logout action

**Comment by alexplusde** [comment]
Ach, na klar.

Ich update die Doku dahingehend. Bitte offen lassen.
