### ISSUE TITLE
Einstellungen: Artikel-ID des Profils

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#246]
Wenn man für Login/Logut-Seiten etc. einzelne Artikel-IDs definieren kann, sollte man auch den Profil-Artikel definieren können.

**Comment by dergel** [comment]
das ist nicht nötig.. Login und Logout haben einen technischen Grund, weil sie Sonderfälle sind.. Profilseite nicht.. ist im Prinzip nur einen geschützte Seite

**Comment by alexplusde** [comment]
Verstehe, ich greife das in einem anderen Issue nochmal auf...
