### ISSUE TITLE
Passwort zurücksetzen - E-Mail nur rausschicken, wenn der Nutzer existiert

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#247]
Mit dem Muster-Code der Doku ist es möglich, dass man über "Passwort zurücksetzen" eine Mail bekommt, obwohl man eine E-Mail-Adresse angegeben hat, die gar keinen Benutzer hat.

Wie unterbindet man solche toten Mails am geschicktesten?

**Comment by SSSLarsen** [comment]
Hab das so gelöst, scheint zu unkionieren:
`validate|in_table|email|rex_ycom_user|email|Für die angegebene E-Mail-Adresse existiert kein Nutzer.|`

**Comment by alexplusde** [comment]
Perfekt, kannst du die Doku dahingehend ergänzen?
