### ISSUE TITLE
 ycom 3.0-beta4: logout funktioniert nicht

### ISSUE THREAD

**Issue by Goldfischpeter** [yakamara/redaxo_ycom#250]
Logout wie in Doku beschrieben, loggt den User nicht aus. User bleibt eingeloggt.

**Comment by Pixeldaniel** [comment]
Manchmal wirkt der Logout-Prozess, als würde er sich aufhängen. Die Seite reagiert dann für Minuten nicht. Man wird manchmal auch aus dem REDAXO Backend geschmissen. Es macht einen Unterschied dabei, ob der Cache von REDAXO schon generiert war oder noch nicht. Ansonsten vollkommen willkürlich.

**Comment by alexplusde** [comment]
@pixeldaniel könnte ein lokales Problem sein. Bitte Bescheid geben, wenn du es mal getestet hast.

**Comment by IngoWinter** [comment]
Bin gerade drüber gestolpert. Umgebung Windows/PHP7.2
Beim Logout wird hier: https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/ycom_auth.php#L402 der ycom Cookie geplättet. Allerdings ist `$sessionConfig['frontend']['cookie']['path']` bei mir leer, der Cookie hat aber als Pfad `/login/`. Der Cookie wird wegen des unterschiedlichen Pfades nicht gelöscht, der User ist weiterhin eingeloggt. Eine Lösung habe ich ob der späten Stunde in Kombination mit einer nicht unerheblichen Menge an Weissweinschorle nicht zu bieten - das Problem habe ich mit `setcookie('rex_ycom', null, -1, '/login/');` umgangen :)

**Comment by alexplusde** [comment]
Das nächste Mal mit Rotwein? @dergel kannst du da was fixen nach so einer schönen Fehlerdiagnose von @IngoWinter ?

**Comment by hillepeter** [comment]
Hallo zusammen,

wir es für dieses Problem noch einen Fix geben?

Gruß
Daniel

**Comment by dergel** [comment]
das sind zwei Probleme gleichzeitig. Das mit dem Cookie in einem Unterordner kann man am besten lösen, und sollte man auch so machen, indem man in der redaxo config den cookie path auf '/' setzt. Das es manchmal so aussieht als ob alles hängt liegt an

`rex_response::setHeader('Clear-Site-Data', '"cache", "cookies", "storage", "executionContexts"');
`

Diese Zeile löscht den kompletten Cache des Browser der Webseite. Und das ist dann manchmal schon einiges, so dass es einfach dauert, bis der Browser durch ist. Wird aber in der nächsten Version nicht mehr so sein.

https://github.com/yakamara/redaxo_ycom/blob/d33f4f42375ab370782384bb9672720adc152ed1/plugins/auth/lib/ycom_auth.php#L381

**Comment by IngoWinter** [comment]
Also Redaxo setzt keinen Standard Pfad für Cookies, YCom ist aber auf einen Standard Pfad angewiesen, weil die Cookies sonst mit dem Pfad des Login Formulares gesetzt werden und dann der Logout evt. nicht funktioniert. Imho sollte dieses Verhalten prominent in der YCom Readme dokumentiert sein oder Redaxo sollte per Default `/` als Pfad setzen oder YCom sollte per Default `/` als Pfad nutzen. Wobei ich einen Standardpfad in der Redaxo Config vorziehen würde.

**Comment by alexplusde** [comment]
Und wie mache ich das mit dem Standard-Pfad?

**Comment by IngoWinter** [comment]
Ich denke mal hier (bzw. in unter /redaxo/data/core/config.yml): https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/default.config.yml#L28

**Comment by dergel** [comment]
Cookie Pfad ist nun immer automatisch auf "/" gesetzt, überschreibt quasi den REDAXO Frontend Cookie Pfad.
Weiterhin ist sowieso einiges umgebaut, so dass auch 'Clear-Site-Data' nicht mehr genutzt wird, sondern die YCom sessionvariablen direkt gelöscht werden.

Bitte nicht die aktuelle github Version nutzen. Es ist noch einiges mehr umgebaut worde, was erst noch dokumentiert werden muss.
