### ISSUE TITLE
Doku: Navigation

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_ycom#253]
Hey,

mir ist eben aufgefallen, dass unter dem Menüpunkt Erste Schritte in der Doku noch der Hinweis auf `rex_ycom_navigation::factory();` steht. Unter Navigation anpassen kommt dann der Hinweis, dass es ´rex_ycom_navigation::factory();´ seit Version 3 nicht mehr gibt.

**Comment by alexplusde** [comment]
Kannst du direkt einen PR dazu einreichen?

**Comment by alexplusde** [comment]
Kannst du direkt einen PR dazu einreichen?

**Comment by pschuchmann** [comment]
Ist drin, #254
