### ISSUE TITLE
Passwortregel Beispiel mit in den Hilfstext

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_ycom#256]
zB minimal-Setup {"length":{"min":10}}
Siehe auch https://github.com/FriendsOfREDAXO/demo_community/issues/24 

ycom_auth_password|password|Dein Passwort*|{"length":{"min":10}}|Das Passwort muss mindestens 10 Zeichen lang sein!|

**Comment by Geri2017** [comment]
Die Regel gibt es schon.
https://github.com/yakamara/redaxo_ycom/blob/master/plugins/docs/docs/de_de/main.password_rules.md
