### ISSUE TITLE
Berechtigung: wenn im Backend eingeloggt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#258]
Optional einem Artikel, User oder Gruppe zuweisen können, dass er mit einer Backend-Login-Session auch eine gesperrte Seite sehen kann.

Oder alternativ, einen Backend-Nutzer einen Frontend-Nutzer zuweisen können.

Ist total praktisch, wenn man eh im Backend eingeloggt ist und dann vom Backend aus auf was geschütztes im Frontend verlinken will.

Kann das Szenario bei Bedarf gerne ausführen.

**Comment by skerbis** [comment]
Duplikat von: https://github.com/yakamara/redaxo_ycom/issues/91

**Comment by alexplusde** [comment]
Stimmt schon irgendwie, sind ähnliche Ansätze...
