### ISSUE TITLE
"Passwort zurücksetzen" Formular führt im Backend zum Logout

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_ycom#259]
Das in der Doku angegebene Formular zum zurücksetzen des Passwortes, führt bei mir im Backend jedes Mal zum Logout. Eine Bearbeitung ist nach dem Speichern nur noch über Adminer direkt in der Datenbank möglich.

Addon Version: 3.0-beta4

Folgendes Formular:
```
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0

validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=1|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status

action|ycom_auth_db|update
action|html|<b>Sie sind eingeloggt. Das Passwort kann nun geändert werden.</b>
```

**Comment by alexplusde** [comment]
Könnte das hier sein: https://github.com/redaxo/redaxo/issues/2744

**Comment by georgkaser** [comment]
Denk ich nicht - hab grad auf "Lax" umgestellt, ändert nix.

**Comment by alexplusde** [comment]
Auf Lax umgestellt und dann Mal komplett den Cache gelöscht im Browser, frisch eingeloggt und alles?

**Comment by georgkaser** [comment]
Jap. Mir is grad aufgefallen, dass es bei der Registrierungsbestätigung auch so ist. Scheint also jedenfalls was mit diesen speziellen Formularen zu tun zu haben. 

```
hidden|status|1
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0

validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=0|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status

action|ycom_auth_db|update
action|html|<b>Vielen Dank, Sie sind nun eingeloggt und haben Ihre E-Mail bestätigt</b>
```

**Comment by rolandsee** [comment]
Puh, das ist wirklich eine krasse Sache. Bin jetzt auch gerade an dem Punkt, wo es mich immer wieder raushaut, wenn ich im Backend editieren möchte. Es scheint an der "validate|ycom_auth_login..." Zeile zu liegen. Damit lässt sich nun kaum noch sinnvoll arbeiten. Kennt jemand einen Workaround?

**Comment by alexplusde** [comment]
Ist sichergestellt, dass ihr im Frontend/Backend nicht aus Versehen das Protokoll wechselt oder verschieden (mit / ohne www.) im Frontend/Backend arbeitet.

**Comment by rolandsee** [comment]
Ich arbeite im Frontend und Backend unter https://localhost bzw. auf dem DEV System unter einer Subdomain (z.B. https://kunde.meinserver.de). Das Protokoll ändert sich nicht, ist immer https. "www" kommt weder am localhost noch auf DEV vor.
Der Vollständigkeit halber: Ich arbeite mit YForm 3.1.1 und YCom 3.0-beta4. Hat jemand mit diesen Versionen ein Modul "Passwort zurücksetzen" erfolgreich am laufen?
Ich habe im Modulcode Zeile für Zeile einkommentiert. Man fliegt tatsächlich raus, sobald die "validate|ycom_auth_login..." Zeile einkommentiert ist und den Block mit dem entsprechenden Modul editieren will.

**Comment by dergel** [comment]
Bitte mal folgendes probieren. in redaxo config.yml bei cookie path / eintragen und lax
und in der ycom_auth.php im lib ordner 

`rex_response::setHeader('Clear-Site-Data', '"cache", "cookies", "storage", "executionContexts"');
`
diese Zeile entfernen.

**Comment by alexplusde** [comment]
@rolandsee falls die Einträge in der `config.yml` nicht existieren, musst du zunächst die Einträge aus einer aktuellen REDAXO-5.8-Konfigurationsdatei holen:

https://github.com/redaxo/redaxo/blob/ac51f37fa5a4e2d6f85c4b61c1c557db799fa7de/redaxo/src/core/default.config.yml#L16-L32

Dies sollte in der Doku unbedingt erwähnt werden, wenn man bspw. von REDAXO 5.3 hochupdated stehen solche Konfigurationen noch nicht in der Datei.

**Comment by dergel** [comment]
Damit sollte es ziemlich sicher gehen. Da nun nicht mehr mehr die kompletten Daten der Domain gelöscht werden. die ycom_auth_login sollte nun auch direkt im Backend die Fehler ausgeben und daher auch gar nicht so weit kommen. Ich denke das issue sollte durch sein. Bitte beim Update daran denken, dass, dass sich noch ein paar andere Dinge, die noch dokumentiert werden, geändert haben

**Comment by georgkaser** [comment]
Schau ich mir dann beim nächsten Projekt auch noch an. Danke für den Hinweis.
