### ISSUE TITLE
Passwort zurücksetzen: Captcha meldet Fehler. Email wird trotzdem verschickt.

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_ycom#260]
Der Fehler tritt bei mir nur beim Passwort zurücksetzen Formular auf:

```
generate_key|activation_key

text|email|E-Mail:|

captcha|Bitte geben Sie den entsprechenden Sicherheitscode ein. Sollten Sie den Code nicht lesen können klicken Sie bitte auf die Grafik, um einen neuen Code zu generieren.|Sie haben den Sicherheitscode falsch eingegeben.

validate|email|email|Bitte geben Sie die E-Mail ein.
validate|empty|email|Bitte geben Sie Ihre E-Mail ein.

action|db_query|update rex_ycom_user set activation_key = ? where email = ?|activation_key,email
action|tpl2email|resetpassword_de|email|
```
Trotz korrekt ausgefülltem Captcha gibt es einen "Sie haben den Sicherheitscode falsch eingegeben." Fehler. E-Mail wird trotzdem verschickt.
Beim Registrierungsformular funktioniert es problemlos und ohne Fehler.

**Comment by paddle07** [comment]
Hi, ich habe das gleiche Problem. Bei mir kommt die Fehlermeldung aber auch bei der Registrierung, sowie die Meldung, dass die E-Mail bereits registriert wurde (was nicht der Fall ist). Die Mail wird trotzdem verschickt und der Datenbankeintrag ist auch richtig. 
Bei der Link-Bestätigung das gleiche Problem... es kommt die Meldung Fehler bereits bestätigt, der Datenbankeintrag ist aber richtig. Verwende PIPE von Doku.

**Comment by paddle07** [comment]
Habe zum testen mal Captcha und Validierung "unique mail" entfernt und sehe nun, dass beim Submit ein doppelter Eintrag in der DB erfasst wird, sprich, bei der Bestätigung, doppelt bestätigt wird...

**Comment by alexplusde** [comment]
Das bedeutet, dass ein anderer Fehler vorliegt - nämlich, dass REX_ARTICLE[] 2x ausgegeben wurde.

**Comment by paddle07** [comment]
Ja, genau das war's! Hatte noch einen vergessenen ...getArticle() im Header drin... DANKE!

**Comment by georgkaser** [comment]
Du, mein Bug ist aber sicher nicht behoben. Bitte wieder öffnen.

**Comment by dergel** [comment]
@georgkaser hattest du geprüft ob der Artikel auch wirklich nicht 2mal ausgeführt wird ?

**Comment by dergel** [comment]
Ich schliesse das mal, weil ich es nicht nachvollziehen kann und der Fehler ziemlich auf das doppelte Ausführen von getArticle oder REX_ARTICLE hinweist

**Comment by georgkaser** [comment]
Hmm, ich hab jetzt nochmal nachgesehen - die Inhalte sind ganz normal über REX_ARTICLE[ctype=1] eingebunden. Wir haben diese Funktionalität aber dann weggelassen, nachdem es nicht funktioniert hatte. Ich mach sicher bald wieder was mit dem Communtity Addon und da teste ich das dann nochmal, okay? Gegebenenfalls öffne ich den Bug dann nochmal.
