### ISSUE TITLE
Doku: xcom-Passwörter umwandeln

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#267]
https://github.com/yakamara/yconverter/issues/49

Vorschlag: rehash ausführen, wenn es sich um alte Passwörter mit sha1() handelt.

Noch besser: Button zum rehashen, sodass auch von Benutzern, die sich nicht einloggen, der Passwort-Hash auf sha256(sha1()) ändert.

`$neuerhash = rex_login::passwordHash($alterhash, true);`

**Comment by dergel** [comment]
xcom unterstütze ich nicht mehr.. wenn dann gerne in die doku damit - oder auch nicht :)

**Comment by alexplusde** [comment]
Wurde in Slack oft gefragt, ich lass es mal offen

**Comment by dergel** [comment]
können wir das nicht irgendwie in tricks packen.. für dich ok @alexplusde ?

**Comment by alexplusde** [comment]
Ich finde es nach erneuter Überlegung in der Doku ganz passend, denn: Es geht ja nicht nur um xcom sondern auch darum, wie man vlt. anhand vorhandener Passwort-Listen oder Hashs diese in die db codiert bekommt.

Tatsächlich habe ich sowas mal für einen Endkundenbereich benötigt. Ich würde den Aufbau der Passwörter und das Selbsthashen (auf eigene Gefahr) gerne schildern.

**Comment by dergel** [comment]
oder ein Link auf die Tricks ?
