### ISSUE TITLE
yForm Aktivierungscheck killt jede Session

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_ycom#270]
https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/validate/ycom_auth_login.php#L25

Damit ist das debuggen praktisch sowohl im Front als auch im Backend unmöglich (um z.B die Ausgabe zu stylen), weil man sowohl im Front als auch im Backend IMMER ausgeloggt wird, sobald man den Artikel aufruft. Das muss anders gehen...

**Comment by Hirbod** [comment]
Sieht so aus, als würde die Funktion den Header `clear-site-data` senden, was imho overkill ist. yCom sollte sich nur um seine eigenen Sessions kümmern und nicht der ganzen Website mitteilen, alle Daten zu löschen.

**Comment by alexplusde** [comment]
Du kannst alternativ den Nutzer sowieso nach der Aktivierung direkt eingeloggt lassen. 

In der Kopiervorlage hatten wir das hier mal hinzugefügt:
https://github.com/yakamara/redaxo_ycom/issues/221

**Comment by alexplusde** [comment]
Vielleicht kannst du in der Action oder dem Validate, das zum Logout führt, ein `rex::isFrontend()` hinzufügen?

**Comment by Hirbod** [comment]
Ändert nix am oben beschriebenen Problem. Ein Fremdanbieter (hier AddOn) sollte nicht ungefragt Sessions löschen, die nicht ihm gehören.

**Comment by alexplusde** [comment]
Achso, stimmt, im Frontend ausgeführt wirst du ja im Backend ausgeloggt - Denkfehler. Dann weiß ich für den Moment auch nicht weiter. Vielleicht prüfen, ob man im Backend als Admin eingeloggt ist?

**Comment by alexplusde** [comment]
Ich meine, hier kommt es nochmal: https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/validate/ycom_auth_login.php#L31 

vielleicht ist das oben drüber auch überflüssig?

**Comment by dergel** [comment]
Clear-Site-Data sollte nun entfernt sein und ist so umgebaut, dass nur die YCom Session Variablen entfernt werden. BItte kein Update aus github direkt machen. Es hat sich von der Logik auch einiges geändert und das muss erst in der Doku nach oder umgeändert werden.

**Comment by alexplusde** [comment]
Ich würde empfehlen, eine neue Major-Version daraus machen, wenn sich so viel geändert hat und es inkompatibel zur Vorversion ist.

**Comment by dergel** [comment]
es gab nie eine 3.0 .. waren alles immer nur betas.

**Comment by alexplusde** [comment]
Ich kann jetzt schon sagen, dass viele die aktuelle beta verwenden und das zu Irritationen kommen wird, wenn man mal eben auf die 3.0 final updatet. So eine 4. beta hat ja beinahe was von einem Release Candidate.

**Comment by skerbis** [comment]
@dergel da muss ich @alexplusde hier Recht geben. Denn ich habe z.B. aufgrund der beta schon Einiges angepasst weil ich bei einer Beta eigentlich immer davon ausgehe dass sich grundlegende Dinge nicht mehr ändern. 
Die Version auf 4.0-beta anzuheben, wenn sie feature-complete ist, würde ich begrüßen.

**Comment by tbaddade** [comment]
> weil ich bei einer Beta eigentlich immer davon ausgehe dass sich grundlegende Dinge nicht mehr dramatisch ändern.

Ich sehe eine Beta als Testversion die vor dem ReleaseCandidate erscheint. Und wenn sich da beim testen Dinge ergeben die angepasst werden müssen, sollten diese angepasst werden. Eine weitere Beta zum Gegentesten sollte dann aber nochmals erstellt werden.

Aktuell sehe ich keinen Grund das als 4.x herauszugeben.

**Comment by skerbis** [comment]
Gut, nur dass es bei REDAXO-Projekten eigentlich keine (mir nicht bekannt) RCs gab. Ist aber auch nicht so schlimm. Da ich egal wie die Version lauten wird, diese auch verwenden werde und will.

**Comment by alexplusde** [comment]
Das Vorgehen könnte ich in einer Alpha verstehen, nicht in einer beta.

Ich finde es nicht gut, dass ohne Augenmaß und Rücksicht auf Entwickler hier auf die formelle Richtigkeit gepocht wird. Das können dann hilfsbereite Menschen in Slack wieder ausbaden.

Ein Grund wurde selbstverständlich genannt, dieser wird schlichtweg ignoriert und nicht anerkannt.

**Comment by skerbis** [comment]
@alexplusde Na ja, es ist ne Beta und es ist nicht für den produktiven Einsatz gedacht. Das sollte jeder der es verwendet auch bedenken. Dass sich große Änderungen ergeben in weiteren Betas hätte ich nicht erwartet, aber gut sie machen YCOM ja jetzt noch besser.  @dergel Danke. 
Die o.g. Anpassungen beziehen sich auf ein aktuelles nicht-live Projekt und daher bei mir alles ok.

**Comment by dergel** [comment]
An Versionsnummern soll das alles nicht hängen. Die Anpassungen sollten überschaubar sein.
