### ISSUE TITLE
Mehrere User mit gleicher E-Mail-Adresse ermöglichen

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#271]
Aktuell darf sich ein User mit der gleichen E-Mail-Adresse nur einmal anmelden. Kann man diesen Check abstellen?

**Comment by alexplusde** [comment]
Würde mich auch interessieren. Notfalls an die E-Mail-Adresse einen Tag und ein `+`-Zeichen packen, z.B. `mail+benutzer1@domain.de` (geht an mail@domain.de) https://will.koffel.org/post/2014/using-email-plus-addressing/

(Die eindeutige Kennung könnte bspw. der Benutzer sein.)

**Comment by skerbis** [comment]
Ist ein Kundenwunsch. Der Kunde hat User die unterschiedliche Logins erhalten sollen aber die gleiche Emailadresse nutzen. Es sind Personen einer Einrichtung mit zentraler Emailadresse. Die Adresse wird nur benötigt um die Einrichtung über Neuigkeiten zu informieren

**Comment by alexplusde** [comment]
(Würde ich im Adminer reinhauen und hoffen, dass niemand das Passwort zurücksetzen will)

**Comment by skerbis** [comment]
Passwort zurücksetzen wird nicht angeboten

**Comment by dergel** [comment]
@skerbis  Dann als Kennung das Login nehmen. die E-Mail Unique Validierung musst du dann einfach raushauen. Und wohl dann leider auch immer wenn es ein Update gibt, aber das sollte es dann auch gewesen sein.

**Comment by skerbis** [comment]
danke, so klappt es :-)
