### ISSUE TITLE
Doku Version 3.1

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#272]
Änderungen aufnehmen.

Es fallen Klassen weg. es gibt nun keine eigene Login/Password/Stayonline YCom Klasse mehr, sondern es sind normale Felder text/password/checkbox und nur noch eine Validierung die dann auch den Login macht

```
validate|ycom_auth|login|psw|stayfield|warning_message_enterloginpsw|warning_message_login_failed

text|login|Login
password|psw|Passwort
checkbox|stayfield|Eingeloggt bleiben
ycom_auth_returnto|returnTo|https://redaxo.localhost,https://www.yakamara.de|http://www.redaxo.org
```

Zusätzlich sollte eine Action rein, die dann auch die Weiterleitung regelt, d.h. hier mann man auch eine eigene feste Weiterleitung rein, oder eine über den request-Parameter "returnTo" welcher dann noch über definierte Domains geprüft wird (also ob diese Domain überhaupt erlaubt ist).

**Comment by dergel** [comment]
Alle request Felder wie rex_ycom_auth_xxx fallen weg. Man kann sich nicht mehr auf jeder Seite einloggen. 

Cookie wird default auf '/' gesetzt, d.h. da fallen auch schon einige bisherige Probleme weg.

**Comment by dergel** [comment]
es gab eine rex_ycom_auth::checkArticlePerm (oder so ähnlich) welche man nutzen musste, um zu prüfen ob im Frontend die Rechte vorhanden sind. Das ist nun anders. Und zwar wird die von redaxo für Frontend gedachte Methode isPermitted() verwendet... D.h. um die Rechte zu prüfen, muss $article->isPermitted() verwendet werden. YCom hakt sich da rein. rex_navigation müsste entsprechend angepasst werden.

**Comment by alexplusde** [comment]
> Man kann sich nicht mehr auf jeder Seite einloggen.

Was, wenn man sich auf jeder Seite einloggen möchte? Oder muss nur das Formular an eine bestimmte Seite zeigen?

**Comment by dergel** [comment]
man kann auf jeder Seite ein Formular anzeigen, muss dann aber auf eine Loginseite gehen und sich von dort dann weiterleiten lassen

**Comment by dergel** [comment]
meines Erachtens sollte die Doku bereits passen. Ich habe noch die SAML DOku ergänzt. Sollte noch etwas fehlen - gerne als neues Issue
