### ISSUE TITLE
article_id_jump_not_ok redirect funktioniert nicht?

### ISSUE THREAD

**Issue by eaCe** [yakamara/redaxo_ycom#273]
Hallo,

ich habe das Problem (version 3.0.4) das der redirect auf `article_id_jump_not_ok` nicht funktioniert.
Sobald ich die Zeile wieder einkommentiere funktioniert das ganze wieder:
https://github.com/yakamara/redaxo_ycom/blob/1aab280dac3d82b08ec2d43de07077ebe5c7dd7a/plugins/auth/lib/ycom_auth.php#L90

Kann ich die Zeile bedenkenlos nutzen? Oder gibt es hier irgendwelche tiefere Problem?

**Comment by dergel** [comment]
ich denke, dass kannst du so ändern. Waren irgendwelche EdgeCases, die ich nicht mehr weiss.. Aber, ich baue einiges hier um, so dass es dann sowieso anders funktioniert und diese Probleme nicht mehr auftauchen sollten. Keine Sorge, Änderungen muss man zwar machen, sind aber meines Erachtens überschaubar.
