### ISSUE TITLE
Session Handling optimieren

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#275]
Überprüfen wie es im Moment ist und eventuell anpassen.

**Comment by dergel** [comment]
Auch wenn ein Passwort geändert wird, sollten die Sessions gelöscht werden, damit keine "alten" User Zugriff haben. Nur so kann man garantieren, dass eine Session nicht ewig am Leben gehalten werden kann.

**Comment by dergel** [comment]
Anbieten können, aktive Session löschen zu können

**Comment by alexplusde** [comment]
`php_value session.gc_maxlifetime 6000` gibt es noch einen anderen Weg, als die Dauer der Session zu begrenzen?

**Comment by dergel** [comment]
Session auf Geräte beschränken und killbar machen. Nicht nur User-Id speichern, sondern auch session id und abgleichen. Auf IP beschränkbar machen

**Comment by dergel** [comment]
Cookie/Session Laufzeit definieren können. Cookie StayOnline mit dem Sessionhandling zusammenlegen

**Comment by alxndr-w** [comment]
In #317 entdeckt: Besser nicht die Session-id selbst speichern, da das gleichzeitig ein Angriffsszenario sein soll.

**Comment by dergel** [comment]
ach so .. nein - das ist ist nur ein platzhalter für das Thema an sich
