### ISSUE TITLE
Redirect auf ursprüngliche Seite

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_ycom#283]
Hey zusammen,

ich hatte gestern im Slack nachgefragt, wie man auf die vorherige Seite umleitet nach erfolgreichem Login. Beim Blick in die Klasse fiel mir auf, dass dort Vorbereitungen für genau diesen Fall vorhanden sind, wenn ich das richtig gelesen habe @dergel . 

In der **YCom 3.0-beta4** war der Weg nun Folgender:

Im Template/Modul:
```php 
rex_getUrl($id_login_article, rex_clang::getCurrentId(), ['rex_ycom_auth_ref' => $this->getValue('article_id')])
```

Auf der Loginseite muss der Parameter ausgelesen werden und per Hidden Value übergeben werden:
```php

$url   = rex_request('rex_ycom_auth_ref', 'string');

...
$yform->setValueField('hidden', ['rex_ycom_auth_ref', $url, 'GET']);
...
```

Analog den Beispielen zu unterschiedlichen Zielseiten für Nutzergruppen, muss dann ein Artikel mit einem Login Template angelegt werden:

```php
<?php

$ycom_user = rex_ycom_auth::getUser();

if ($ycom_user) {
    $referer = rex_server('HTTP_REFERER', 'string');

    parse_str(parse_url($referer, PHP_URL_QUERY), $queries);
    $target_id = $queries['rex_ycom_auth_ref'];

    if ($target_id) {
        rex_redirect($target_id);
    } else {
        rex_redirect(rex_article::getSiteStartArticleId());
    }
} else {
    // System-Start-Artikel
    rex_redirect(rex_article::getSiteStartArticleId());
    // Alternativ: YRewrite-Domain-Startartikel
    // rex_redirect(rex_yrewrite::getCurrentDomain()->getStartId());
}
```
Vielleicht ist das was für die Doku @alexplusde

**Comment by dergel** [comment]
Ohne das ich das von dir nachvollzogen habe, bitte ich dich die aktuelle Variante dir anzusheen.

es gibt ein Feld returnoTo was du als Action verwenden kannst. Damit kann du z.B. eine Überprüfung auf die referer DOmain durchführen oder feste Weiterleitungen erzwingen. Ich denke, dass sollte deinen Fall lösen. `rex_ycom_auth_ref` gibt es nicht mehr.

**Comment by pschuchmann** [comment]
In YCom 4 ist das Verhalten nun standardmäßig so. Glaube damit hat sich das hier dann erledigt, aber vielleicht ist es noch interessant für Leute, die nicht auf die Version 4 updaten.

**Comment by alexplusde** [comment]
In YCom 4 ist es also so:

1. Nutzer klickt auf einen geschützten Artikel A
2. Nutzer wird zum Login-Formular weitergeleitet
3. Nutzer loggt sich ein und wird zum geschützten Artikel A zurückgeleitet

Ein Update von YCom "genügt", man muss dabei nichts konfigruieren oder ändern?

Sehe ich das richtig?

**Comment by pschuchmann** [comment]
Nicht ganz. Im Form Builder auf der Login Seite muss eine weitere Action hinzugefügt werden (aus der neuen Doku):

`ycom_auth_returnto|returnTo|`

**Comment by alexplusde** [comment]
Was muss bei returnTo hinterlegt werden? Nichts? Eine URL? Eine Artikel-ID?

https://github.com/yakamara/redaxo_ycom/blob/master/plugins/docs/docs/de_de/main.login.md#login

**Comment by dergel** [comment]
genau . es muss nichts hinterlegt werden. aber man kann auch externe weiterleitungen erlauben und z.B. auf Domains beschränken, oder eine fest Weiterleitung eintragen

**Comment by alexplusde** [comment]
dann finde ich den Keynamen ungünstig gewählt. eher `ycom_auth_return_to_origin|return_to_origin` - ich schätze mal, die Doppelung muss sein wegen `value|name`

**Comment by dergel** [comment]
das ein allgemeines feld .. das ist so gewollt.. kann man auch sonst nutzen und hat noch filter auf domains etc.

**Comment by alexplusde** [comment]
> das ein allgemeines feld .. das ist so gewollt.. kann man auch sonst nutzen und hat noch filter auf domains etc.

Was heißt das im Konkreten?

**Comment by dergel** [comment]
returnTo ist eine Action die einen redirect macht.
Als erlaubt DOmains, ist immer die eigene vorhanden. Diese kann man mit einen erweitern, 1. Parameter mit kommaseparierten Domains, und man kann als 2. Parameter eine feste Weiterleitung eintragen.
Wenn nichts eingetragen ist, werden die entsprechend der Einstellungen in ycom genommen.

**Comment by alexplusde** [comment]
Sorry, ich versteh's nicht.

Konkret dann also:

`ycom_auth_returnto|returnTo|domainid|`
`ycom_auth_returnto|returnTo||url`

z.B.
`ycom_auth_returnto|returnTo|3|`
`ycom_auth_returnto|returnTo||https://www.example.org/article`

**Comment by dergel** [comment]
nicht domainid .. sondern die domains, die erlaubt sein sollen..

angenommen du hast sowas ..

https://www.yakamara.de/login/?returnTo=https://meineseite/irgendwas

willst aber nicht, dass die weiterleitung nach meineseite erlaubt ist, dann kannst du die erlaubten domains dort eintragen. Die internen DOmains sind sowieso erlaubt und du kannst du mir anderen erweitern

**Comment by alexplusde** [comment]
Jetzt wird es klarer. Bitte offen lassen, bis es dokumentiert ist. Das scheint mir erklärungsbedürftig zu sein.

**Comment by dergel** [comment]
habe drin .. wenns doof klingt, gerne korrigiere. auf der login docs seite
