### ISSUE TITLE
Medienzugriff mit unterschiedlichen Usergruppen

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_ycom#284]
Hi,

beim Durchtesten ist eben aufgefallen, dass bei einem Zugriff auf ein geschütztes Medium mit eingeloggtem User, der nicht auf das Medium zugreifen darf, eine weiße Seite zurück kommt. 

Vielleicht etwas verständlicher als Beispiel:

- Bild im Medienpool, Zugriff ist nur für Gruppe 1 erlaubt
- Ruft ein User mit Gruppe 2 die Url auf, bleibt die Seite weiß

Macht man das gleiche mit einem Artikel, wird auf den Artikel umgeleitet, der unter `article_id_jump_denied` hinterlegt ist.

**Comment by dergel** [comment]
das scheint mir richtig zu sein. Im Moment wird dann ein 401 Unauthorized Error: error geschickt. Habe es aber um eine media_auth-Rule ergänzt, bei der du deine Option auswählen kannst.

**Comment by pschuchmann** [comment]
Cool, danke!
