### ISSUE TITLE
Docs. Grafiken sind zu breit.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#285]
ist wohl ein allgemeines redaxo problem, dennoch hier im speziellen lösen.

**Comment by marcohanke** [comment]
Ich habs bisher nur in der ycom gesehen. ckeditor z.b. zeigt de Grafiken Korrekt an.

**Comment by alexplusde** [comment]
Müsste das nicht hier mal gelöst worden sein? (Auch wenn nicht docs)
https://github.com/redaxo/redaxo/pull/1181
https://github.com/redaxo/redaxo/issues/739
https://github.com/redaxo/redaxo/issues/1405
