### ISSUE TITLE
Logout ohne YFORM funktioniert nicht mehr wie gehabt

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#287]
Version: 4.0beta3

Ich habe für den LogOut immer folgenden Code verwendet. Leider funktioniert dieser nicht mehr. 
Ich möchte gerne auf YForm verzichten in diesem Fall. 

```PHP 
rex_redirect(rex_plugin::get('ycom', 'auth')->getConfig('article_id_jump_logout'), 'REX_CLANG_ID', array("rex_ycom_auth_logout" => 1)); 
```

Gibt's ne Alternative?

**Comment by alexplusde** [comment]
Was ist das Ziel? Nach dem Logout auf eine spezifische Seite weitergeleitet zu werden? #283

**Comment by skerbis** [comment]
Es macht eigentlich das gleiche wie die dämliche Pipe-Definition im YForm-Modul denke ich

**Comment by dergel** [comment]
man kann sich nicht mehr überall ausloggen indem man einfach den Parameter "rex_ycom_auth_logout" verwendet, sonder muss dafür einen Artikel anlegen, oder es selbst programmieren. Das ist so gewollt und soll helfen, mehr Kontrolle über diese Abläufe zu haben. Vor allem bei angedockten Authentifizierungen ist es nicht unwichtig, klare URLs zu haben

**Comment by skerbis** [comment]
dann ist der Code in dieser Doku obsolet? https://github.com/yakamara/redaxo_ycom/blob/b8febdc5066951af4922da8b52ed546762eb37f1/plugins/docs/docs/de_de/main.navigation.md

**Comment by dergel** [comment]
genau .. danke für den Hinweis. Habe es korrigiert.
