### ISSUE TITLE
Update von 3-beta4 auf 4.0 ändert Nutzerrechte der Artikel

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#290]
Beim Update werden die Felder in der Tabelle `rex_article` die Felder `ycom_auth_type` und `ycom_group_type` auf den Typ INT geändert. Bei mir waren es vorher Felder vom Typ ENUM. Durch die Änderung wird der Wert der Benutzerrechte um 1 erhöht. Also aus 1 wird 2, ... 

Die Tabelle `rex_media` ist nicht betroffen, da dort - zumindest bei mir -  in einer alten Version keine ENUM Felder drin waren.

**Comment by tbaddade** [comment]
Ist hier auch eben passiert, sodass alle Artikel erst einmal gesperrt sind.

https://dev.mysql.com/doc/refman/8.0/en/enum.html
> The elements listed in the column specification are assigned index numbers, beginning with 1.
> If you retrieve an ENUM value in a numeric context, the column value's index is returned

**Comment by skerbis** [comment]
Danke. Ist mir auch heute passiert.

**Comment by alexplusde** [comment]
Den Query ausführen bedeutet aber, dass alle fortan ungeschützt sind, oder?

**Comment by skerbis** [comment]
@alexplusde -1

**Comment by tbaddade** [comment]
@alexplusde Was @skerbis meint ist, dass alles so bleibt wie es vorher war. Das Problem liegt am ENUM und dessen Index. Das Feld wurde auf integer angepasst, sodass alle 0 Werte den Index 1 vom ENUM 0 bekamen. Siehe Link weiter oben.

**Comment by godsdog** [comment]
Ist mir auch gerade bei einem Update von 2.3 auf 4.0.1 passiert.

**Comment by dergel** [comment]
Gerne prüfen mit der aktuellen github Version. Sollte nun passen
