### ISSUE TITLE
Offline-Kategorien werden angezeigt

### ISSUE THREAD

**Issue by engel4u** [yakamara/redaxo_ycom#292]
Das Navi-Template soll lt. Doku so angelegt werden:

$nav = rex_navigation::factory();
$nav->addCallback('rex_ycom_auth::checkPerm');
$nav->show();

Seit der neuesten Version werden dabei aber auch Kategorien angezeigt, die offline sind. 
Redaxo-Version 5.8.1, YCom Version 4.0

**Comment by alexplusde** [comment]
Kann ich bestätigen

**Comment by skerbis** [comment]
Das ist nur ein Beispiel 
Habt ihr es mit den anderen Parametern probiert ?
https://redaxo.org/doku/master/navigationen

**Comment by engel4u** [comment]
Danke, so geht es:
$nav->show(0, 1, TRUE, TRUE);

**Comment by skerbis** [comment]
👍

**Comment by skerbis** [comment]
@alexplusde bitte auf die Factory Doku verweisen

**Comment by engel4u** [comment]
Ich habe es in der YCom-Doku ergänzt.

**Comment by alexplusde** [comment]
> Ich habe es in der YCom-Doku ergänzt.

Sehe ich nirgends. PR gemacht?

**Comment by engel4u** [comment]
Siehst Du jetzt was?

**Comment by skerbis** [comment]
@alexplusde https://github.com/yakamara/redaxo_ycom/pull/293

**Comment by alexplusde** [comment]
Jetzt ist es da.
