### ISSUE TITLE
Lebensdauer Cookie: Änderung des Wertes in der Datei install.php zeigt keine Wirkung

### ISSUE THREAD

**Issue by engel4u** [yakamara/redaxo_ycom#299]
In der Datei install.php steht in Zeile 4:

rex_config::set('ycom', 'auth_cookie_ttl', '14');

Wenn ich den Wert von 14 auf einen anderen Wert ändere zeigt das keine Wirkung. 

Warum?

Weil in der Datei ycom_auth.php weder die Einstellung aus der Datei install.php noch aus der Datenbank (Tabelle rex_config, Zeile: auth_cookie_ttl) verwendet werden. In der Datei ycom_auth.php ist sowohl in der Zeile 217 als auch Zeile 233 die Lebensdauer auf 14 Tage fest hinterlegt. 

Statt 14 fest zu hinterlegen sollte der Wert aus der install.php bzw. der Wert aus der DB genommen werden. Noch besser wäre es, wenn man in den Einstellungen von YCom die TTL für das Cookie ändern könnte.

**Comment by alexplusde** [comment]
Valider Punkt. Möchtest du einen PR dazu erstellen?
