### ISSUE TITLE
Weiterleitung funktioniert nicht (article_id_jump_not_ok)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#302]
Diese Einstellung verstehe ich so, dass wenn ich mich fehlerhaft einlogge auf die angegebene Seite weitergeleitet werde... tut es nicht. Ich bleibe auf der Login Seite.

![image](https://user-images.githubusercontent.com/330516/73356255-359b7a00-429a-11ea-9021-181feb2411c3.png)

**Comment by dergel** [comment]
die Erklärung ist nicht eindeutig. wenn man sich fslsch einloggt sprint man immer auf die Login sein, man bleibt dort. Dieser article_id_jump_not_ok Artikel wird nur bei einer SAML Authentifizierung verwendet, also wenn man sich extern anmeldet und es fehlgeschlagen ist

**Comment by alexplusde** [comment]
closed in #313
