### ISSUE TITLE
Weiterleitung: Register-Seite [article_id_register] funktioniert nicht

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#303]

**Comment by alexplusde** [comment]
Was heißt "funktioniert nicht"? Von wo leitest du weiter? Was ist eingestellt?

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/73726815-7e3ab380-4730-11ea-83c0-e0a0d8c4f023.png)
![image](https://user-images.githubusercontent.com/330516/73726836-885cb200-4730-11ea-98b5-c59d481477e6.png)

ergibt

![image](https://user-images.githubusercontent.com/330516/73726885-a2969000-4730-11ea-84ea-c10d09b856f1.png)

**Comment by alexplusde** [comment]
Und was steht in $register_article_id ?

**Comment by olien** [comment]
eine **1**

**Comment by alexplusde** [comment]
Wie kommt die zustande? Ist das die ID der Startseite?

**Comment by olien** [comment]
jupp

**Comment by alexplusde** [comment]
Ja, dann ist doch kein Wunder, dass du auf der Startseite rauskommst.

**Comment by alexplusde** [comment]
Missverständnis, per Slack geklärt.
