### ISSUE TITLE
Error: Call to undefined method rex_ycom_user::checkPerm()

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#304]
![image](https://user-images.githubusercontent.com/330516/73722766-94904180-4727-11ea-95b5-c55b85e8d404.png)

**Comment by alexplusde** [comment]
Ich glaube, du erhältst nur ein Objekt, wenn der User überhaupt eingeloggt ist. `$ycom_user` auf null prüfen. Ist das Beispiel so aus der Doku?

**Comment by olien** [comment]
Ja. Das ist das Beispiel aus der Doku. Auch wenn der User eingeloggt ist kommt der Fehler.

**Comment by alexplusde** [comment]
Was kommt raus bei `dump($ycom_user)`? Bisschen mehr Infos auch bei dem anderen Problem wären nützlich.

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/73729011-99a7bd80-4734-11ea-9f90-997daff7b2fe.png)

**Comment by alexplusde** [comment]
Hier hat sich etwas geändert und muss in der Doku aktualisiert werden. Hilft dir das hier weiter? https://github.com/yakamara/redaxo_ycom/commit/ff70d4d0a999bb87627f354363ed0b5995acdd51

probier mal `isPermitted()`

**Comment by dergel** [comment]
ich sehe gerade keine Fehler. @olien melde dich gerne bei mir per DM und ich schaue nach

**Comment by alexplusde** [comment]
@dergel hat sich der Methodenname geändert und das wurde in der Doku noch nicht korrigiert?
