### ISSUE TITLE
Link zu "Profil ändern" in den Einstellungen fehlt

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#305]
![image](https://user-images.githubusercontent.com/330516/73723376-32d0d700-4729-11ea-8461-b5c6756f3f23.png)

**Comment by alexplusde** [comment]
Jo, das stimmt. Ist die Frage, ob's das braucht. Im Endeffekt setzt man ja nur einen Link oder erstellt die Seite als Kategorie.

@dergel Einstellungen korrigieren oder Doku korrigieren?

**Comment by olien** [comment]
Wäre mir egal. Nur so ist es verwirrend

**Comment by dergel** [comment]
Doku korrigieren. Es besteht keine technische Relevanz, dass in den Einstellungen zu haben
