### ISSUE TITLE
Fehler im Log vermeiden

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_ycom#306]
https://github.com/yakamara/redaxo_ycom/blob/1aab280dac3d82b08ec2d43de07077ebe5c7dd7a/plugins/auth/lib/yform/value/ycom_auth_returnto.php#L35-L37

muss geändert werden analog zu hier:

https://github.com/yakamara/redaxo_yform/commit/873e49e06f3896c83805e24003e5c34cc5814de8#diff-eba0de48fa246cd09291749ff2c26fdc

Danke @gharlan in Slack, @engel4u für das Melden.

**Comment by elricco** [comment]
Bei mir scheint es das Problem zu lösen. Mit verschiedenen Accounts im FE eingeloggt und es entstehen keine Fehlermeldungen mehr im Systemlog. Aber gerne nochmal prüfen @engel4u :)
