### ISSUE TITLE
Neues Passwort muss gesetzt werden

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_ycom#309]
Habe gemäß Doku eine Seite mit dem Formular "Passwort ändern" erstellt.
Das funktioniert auch. 

Setzte ich das Häkchen im Backend beim User (Feld new_password_required), wird man nach dem Login auf diese Seite weitergeleitet. Auch die Änderung des Passworts ist möglich. Allerdings wird nach der Änderung weiterhin nach dem Login auf diese Seite weitergeleitet, d.h. ich komme nicht mehr auf den Inhalt den ich eigentlich sehen will. Das Häkchen bleibt im Backend angehakt. das Feld sollte wohl geändert werden, nachdem man das Passwort geändert hat.

**Comment by alexplusde** [comment]
Diese Änderung in der Doku beachten
https://github.com/yakamara/redaxo_ycom/pull/296
