### ISSUE TITLE
article_id_jump_denied unklar

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#312]
article_id_jump_denied greift nur bei eingeloggten Benutzern mit falscher Berechtigung. Nicht eingeloggte Benutzer landen automatisch auf der Loginseite.
Ich weiß nicht ob ich das gut finde. Ich würde den nicht eingeloggten Besuchern auch gerne mitteilen dass sie eben hier keinen Zugriff haben und sich dafür registrieren müssen, das ist aktuell nicht möglich.

**Comment by alexplusde** [comment]
ich finde es gut und würde es schließen. Als nicht eingeloggter User soll man nicht die Chance haben, etwas über den Login-Bereich herauszufinden.

Dass man sich registrieren muss für den Bereich kann ja auch eine Info der Login-Seite sein und ein Link dorthin geboten werden.

**Comment by marcohanke** [comment]
Würde ich nicht so sehen. Dadurch dass du auf die Loginseite weitergeleitet wirst weißt du dass es einen Artikel gibt der im Login-Bereich ist. Ist also nichts anderes. Wenn ich einen eigenen Aritkel dazu setzen kann, kann ich in manchen Anwendungsfällen konkret für eine Registrierung werben. Und selbst wenn es so bleibt, ist das Wording doof.

**Comment by dergel** [comment]
ich habe das in der Notice besser erklärt. Das Verhalten wie es ist finde ich richtig. Man hat keinen Zugriff/Rechte, dann einloggen und schauen ob man dann Rechte hat, und dann erst auf den denied Artikel mit der Erklärung leiten.
