### ISSUE TITLE
last_action_time wird vor dem Aufruf der Module aktualisiert

### ISSUE THREAD

**Issue by LuxusMEDIA** [yakamara/redaxo_ycom#318]
Ich möchte in einem Projekt die last_action_time aufrufen, um immer nur die neusten Artikel seit dem letzten Aufruf anzuzeigen, diese wird aber immer schon aktualisiert, bevor ich sie im Modul abfragen kann, weshalb dann nur das aktuelle Datum und Zeit ausgegeben wird. Die last_login_time kann ich nicht nehmen, weil manche Benutzer ja auch eingeloggt bleiben verwenden. So ist wahrscheinlich auch die Funktion der last_action_time nicht erfüllt.

**Comment by dergel** [comment]
das müsstest du selbst lösen und zwar mit einem eigenen Feld was du immer setzt, wenn die Artikelliste aufgerufen wird.. Dafür ist last_action_time nicht gedacht. Die ist eher dafür geeignet, alte User zu löschen, oder neu anzufragen oder ähnliches.
