### ISSUE TITLE
Fehlermeldung erscheint doppelt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#320]
**YCom:** 4.0.1
**YForm:** 3.3.1

Ich lasse die Fehlermeldungen via php Value ausgeben.  Dabei ist mir aufgefallen, dass die Meldung von der `ycom_auth` Validierung `warning_message_enterloginpsw` doppelt erscheint.

**Builder - entscheidende Zeilen**

```
objparams|hide_top_warning_messages|true

php|error|<?php if(isset($this->params['warning_messages']) && count($this->params['warning_messages'])) { echo '<div class="alert alert-danger">'.implode('', $this->params['warning_messages']).'</div>'; } ?>

validate|ycom_auth|login|psw|stayactive|warning_message_enterloginpsw|{{ login.user.login.failed }}

```

Zu sehen ist es [hier im Code](https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/validate/ycom_auth.php#L31). Falls Login und Passwort leer sind, kommt die Meldung doppelt in das Array.

Lässt man die Fehlerausgabe wie es von YForm vorgesehen ist, dann passiert das nicht. Denn die [Übersetzungen werden dort als Key gespeichert](https://github.com/yakamara/redaxo_yform/blob/master/ytemplates/bootstrap/errors.tpl.php#L21). Damit wird die doppelte Ausgabe vermieden.

**Comment by dergel** [comment]
das ist richtig, da der Array alle Meldungen sammelt die auftauchen. Wenn z.B. in diesem validate nach login UND passwort geprüft wird, so gibt es zu diesen beiden Feldern Meldungen, in diesem Fall halt die gleiche Meldung, in der Ausgabe wird das dann in z.B. rote Felder verwandelt.

deswegen hier am besten, wenn das so gewünscht ist, mit array_unique( arbeiten und die doppelten Meldungen damit entfernen
