### ISSUE TITLE
Redirect nach Login falsch

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#321]
**Aufruf des Loginformualrs via**
`https://project.localhost:3002`

**Nach erfolgreichen Login geht der redirect auf**
`https://project.localhost:3002//project.localhost:3002/[article_id_jump_ok]/`

Rufe ich die Seite ohne Port auf, geht der redirect korrekt auf
`https://project.localhost/[article_id_jump_ok]/`

**Comment by godsdog** [comment]
Gibt es hier schon was neues? Habe in einer Unterordner Installation das gleiche Problem, dass der Unterordner doppelt in die URL gehängt wird.

yCom 4.0.3 und Redaxo 5.12.0

**Comment by dergel** [comment]
das sind 2 verschiedene Sachen .. Beim Thomas oben wird der Port falsch verarbeitet. D.h. dort ist wohl ein Problem mit dem Port. Bei die @godsdog ist das wohl eher die Installation von REDAXO in einem Unterordner. @godsdog kannst du darauf ein eigenes Issue machen ?

**Comment by godsdog** [comment]
Ist auf gemacht: https://github.com/yakamara/redaxo_ycom/issues/356

**Comment by Hardy74** [comment]
Der Bug existiert offenbar immernoch, in Version 4.0.6.
Stellt man als Seite nach erfolgreichem Login eine Seite ein, die einen Login benötigt, bricht der Firefox mit der Meldung ab, dass die Webseite die Anfrage so weiterleiten würde, dass diese nie beendet werden könnte.

**Comment by dergel** [comment]
@tbaddade lange ists her .. aber sollte eigentlich gehen. In YRewrite muss natürlich auch der Port drin sein. In meinem Fall hat es funktioniert.

**Comment by tbaddade** [comment]
> In meinem Fall hat es funktioniert.

Dann schließe ich.
