### ISSUE TITLE
REDAXO Table-Prefix beachten

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#322]
rex_ ist vorgegeben im JSON

**Comment by dergel** [comment]
was meinst du ? Kannst du mir die Stelle markieren ?

**Comment by skerbis** [comment]
In der JSON Datei 
https://github.com/yakamara/redaxo_ycom/blob/master/install/tablesets/yform_user.json
ist rex_ycom_user z.B. fest hinterlegt. 

Es wäre schön würde das Prefix beachtet werden. Vielleicht findet sich ja auch eine allgemeine Lösung für den Export und Import von Tableset-Dateien? 

Wir haben das im neuen Domainsettings-Addon anders realisiert: 
https://github.com/FriendsOfREDAXO/yrewrite_domain_settings/blob/956165ce74f3c6fd9c7c1468dfc07ea1fc71c130/install.php#L1

**Comment by tbaddade** [comment]
Kann man hier nicht den Platzhalter `%TABLE_PREFIX%` nutzen?

**Comment by skerbis** [comment]
Weiß nicht 🤔

**Comment by alexplusde** [comment]
Selbst dann bräuchte es einen Prozess, bei dem man beim Exportieren eines Tablesets den Tabellennamen-Präfix in einen Platzhalter überführen kann.

**Comment by alxndr-w** [comment]
@skerbis Im Table Manager müsste man eine Suchen-Ersetzen-Regex-Regel schreiben, die beim Import/Export des Sets hier `"%TABLE_PREFIX%_` sucht und durch `rex_` ersetzt und vice versa. (Der Präfix taucht ja nicht nur im Tabellennamen auf, sondern auch in den be_relation_manager-Feldern.

Ich sehe das konkret als Teil von https://github.com/yakamara/redaxo_yform

**Comment by skerbis** [comment]
oder das Tableset wie oben angegeben per PHP übergeben
