### ISSUE TITLE
Update von 4.0.1 auf 4.0.2 schlägt fehl

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#329]
![image](https://user-images.githubusercontent.com/330516/87904587-e96a0f00-ca5e-11ea-98f6-2a9a044037bd.png)

**Comment by iceman-fx** [comment]
Kann ich bestätigen.
Kommt auch beim Update von 4.0.0 auf 4.0.2

**Comment by thielpeter** [comment]
+1

**Comment by tyrant88** [comment]
alter table .. drop if exists ... gibt es nur in MariaDB.
Müsste nicht eigentlich das Feld nur umbenannt werden? Verliert man da nicht Daten?

**Comment by TobiasKrais** [comment]
Bin auch betroffen...
