### ISSUE TITLE
Fehler bei Nutzungsbedingungen bestätigt

### ISSUE THREAD

**Issue by aeberhard** [yakamara/redaxo_ycom#331]
ycom Version 4.0.3
REDAXO Version 5.11.0

Wenn _Nutzungsbedingungen bestätigt_ nicht angehakelt ist und in den Einstellungen ein Artikel dafür gesetzt ist
wird dieser zwar korrekt aufgerufen... 
Man kann in diesem Artikel auch noch einen Link zu den Nutzungsbedingungen (Text) setzen. Aber bei Klick wird
statt der Text-Seite wieder der Artikel zum bestätigen der Nutzungsbedingungen aufgerufen :(

**Comment by aeberhard** [comment]
Ach ja, der Artikel mit dem Text hat _Zugriff für alle Benutzer_ und liegt im öffentlichen Bereich

**Comment by aeberhard** [comment]
Mann kann gar keine andere Seite mehr aufrufen. Nicht die Startseite noch sonstige. Es kommt immer der Artikel für die Einstellung der Nutzungsbedingungen. Wenn die "akzeptiert" werden dann kann man alle Seiten wieder wie gewünscht aufrufen.
Cache löschen usw. auch ausprobiert.

**Comment by dergel** [comment]
diese Nutzungsbedingungen müssen dann auf dieser Seite bestätigt von dem User bestätigt werden. 
sowas in der Art:

```
objparams|form_showformafterupdate|0
ycom_auth_load_user|userinfo|email,firstname,name,termsofuse_accepted
hidden|termsofuse_accepted|1
php|termofusecheck|phplabel|<?php if (!rex::isBackend() && rex_ycom_auth::getUser()->getValue('termsofuse_accepted') == 1) { rex_redirect(16); exit; } ?>
html|termofuse_info|Hier stehet die Nutzungsbedingungen drin {{ termsandconditions  }}
action|showtext|<div class="alert alert-success">{{ termofuse_accepted }}</div>|||1
action|ycom_auth_db
```

Steht nicht in der Doku. Wenn es klappt, kannst du das in der Doku ergänzen ? Das wäre super

**Comment by aeberhard** [comment]
Ja das stimmt und ich habe auch einen Artikel zum bestätigen drin mit folgendem

```
objparams|form_name|table-rex_ycom_user
objparams|form_ytemplate|bootstrap
objparams|form_showformafterupdate|1
objparams|submit_btn_show|0
objparams|real_field_names|true

ycom_auth_load_user|userinfo|termsofuse_accepted

checkbox|termsofuse_accepted|{{text.AkzeptiereNutzungsbedingungen}}|0|0|
submit|rex_yform_submit|{{btn.Save}}|1|0||btn-bs-primary

action|ycom_auth_db

action|showtext|{{message.ok.DataSaved}}|<div class="alert alert-success"><i class="fa fa-check pr-2"></i>|</div>|1
```

Das Problem ist dass ich auf keine andere Seite mehr gehen kann innerhalb der Webseite.
z.b. sind in diesem Artikel auch auch die Nutzungsbedingungen verlinkt ... aber nicht mehr aufrufbar da immer
das Formular oben erscheint. Erst wenn das Hakerl gesetzt ist kann wieder jede Seite aufgerufen werden.

Ist auch beim Passwort neu setzen so.

Besser fände ich wenn die beiden Funktionen (Nutzungsbedingungen bestätigen + Passwort neu setzen)
nur erscheinen wenn man sich eingeloggt hat ... oder wenn man auf eine geschützte Seite zugreifen will.

Alle "öffentlichen" Seiten sollten dann ganz normal angezeigt werden.

Hoffe Du verstehst was ich meine Jan :)

**Comment by aeberhard** [comment]
Der User will ja vielleicht die Nutzungsbedingungen lesen bevor er sie akzeptiert.
So nicht mehr möglich da die auf einer anderen (öffentlichen) Seite stehen :)

**Comment by dergel** [comment]
das sollte eigentlich sowieso nur passieren wenn man eingeloggt ist. Nur dann kann geprüft werden ob ein User diese bestätigt hat. Habe ich was falsch verstanden ?

>oder wenn man auf eine geschützte Seite zugreifen will.
Hatte kurz überlegt und fand das auch erstmal gut.. Aber dann doch nicht, weil es darum geht, dass man garantiert bekommt, dass jemand nur eingeloggt unterwegs sein darf, wenn die Person diese Nutzungsbedingungen akzeptiert (weil z.B. der User getrackt wird oder ähnliches) ..

D.h in deinem Fall würde ich in den YCom Einstellungen einfach die Nutzungsbedingungen nicht verlinken und was eigenes bauen.
