### ISSUE TITLE
ycom_auth - redirect nach Login und Download

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_ycom#333]
Nach click auf eine geschützte Datei, landet man auf der Login-Seite und gibt die richtigen Login-Daten ein. Die Datei wird heruntergeladen. Es bleibt weiterhin die Login-Seite sichtbar. Ist es auch möglich, die Datei herunterzuladen plus Weiterleitung auf die Login-erfolgreich-Seite?
Ingo merkt noch an, dass auch ein Redirect auf die Ursprungsseite sinnvoll sein kann, von der aus der Download ausgelöst wurde.

**Comment by dergel** [comment]
Finde die Idee gut. weiss nur leider nicht wie man das umsetzen soll.. Ich befürchte, dass man das individuell umsetzen muss. Oder hast du eine Idee wie ?

**Comment by dtpop** [comment]
Ich habe auch über die Architektur gehirnt und keine Lösung gefunden (nicht einmal eine individuelle).
