### ISSUE TITLE
Versionsbeschreibung für 4.0.3 im Installer falsch

### ISSUE THREAD

**Issue by tyrant88** [yakamara/redaxo_ycom#334]
Versionsnummer und Datum sind falsch und auch der Text ist (fast) derselbe wie bei 4.0.2
![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/92623215-3d0e1180-f2c6-11ea-878b-970cdf82b807.jpg)

**Comment by dergel** [comment]
Danke für die Info .. ist korrigiert.

**Comment by tyrant88** [comment]
thx
