### ISSUE TITLE
Klick auf Link in Registrierungsmail schlägt immer fehl

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#347]
In der Doku steht folgendes Form für die Registrierungsbestätigung:

```
hidden|status|1
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0

validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=1|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status

action|ycom_auth_db|update
action|html|<b>Vielen Dank, Sie sind nun eingeloggt und haben Ihre E-Mail bestätigt</b>
```

Damit funktioniert es nicht.

wenn ich den `status=0` setze funktioniert es.

```
validate|ycom_auth_login|activation_key=rex_ycom_activation_key,email=rex_ycom_id|status=0|Zugang wurde bereits bestätigt oder ist schon fehlgeschlagen|status
```

Ist an dieser Stelle die Doku falsch oder mache ich etwas falsch?

**Comment by olien** [comment]
OK. Nach einem Telefonat mit Jan

es muß **status>0** heissen.

Danke Jan :-)

**Comment by dergel** [comment]
bin mir gerade unsicher.. wenn es 0 ist klappt es bei dir .. bei status > 0 klappt es wahrscheinlich nicht. Testest du es nochmal bitte ?

**Comment by olien** [comment]
status>=0 und status=0  funktioniert.

**Comment by dergel** [comment]
passt mittlerweile
