### ISSUE TITLE
Ausgabe CSS und JavaScript im Backend optimieren

### ISSUE THREAD

**Issue by aeberhard** [yakamara/redaxo_ycom#350]
Im Backend wird auf allen Seiten CSS+JavaScript für YCom geladen.
Sollte nur bei den notwendigen Seiten geladen werden!

**Comment by alxndr-w** [comment]
Es sieht nicht so aus, als wäre dies der Fall
https://github.com/yakamara/redaxo_ycom/blob/5b7a4b35b8f4053a9694f3064887611898d9aeef/boot.php#L26-L28

https://github.com/yakamara/redaxo_ycom/blob/5b7a4b35b8f4053a9694f3064887611898d9aeef/plugins/auth/boot.php#L53

Im Übrigen braucht es das vermutlich auch überall, weil ja Teile von YCom (Berechtigungen) auch in der Struktur und in YForm-Tabellen verankert sind, oder diese über eine Addons-Seite referenziert werden. (Bspw. YForm-Tabellen innerhalb eines Addons)

Ich meine, das muss so bleiben und kann zu.

**Comment by dergel** [comment]
Denke auch, dass es passt.
