### ISSUE TITLE
Zwischen Benutzern und Gruppen m:n ermöglichen / mind. 1:n normalisieren

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#357]
Da die 4.0 noch aktuell beta ist, wäre es evtl. möglich, in dem Zuge m:n-Beziehungen zwischen Benutzer und Gruppen zu ermöglichen?

Mindestens sollte es möglich sein, über 1:n-Beziehung nicht nur Nutzer eine Gruppe zuzuordnen, sondern umgekehrt auch einer Gruppe mehrere Nutzer zuzuweisen.

Dazu wäre eine Relationstabelle unumgänglich

**Comment by alxndr-w** [comment]
@dergel ich würde dazu einen PR mit Änderungen an den Tabellen vorbereiten, wenn das erwünscht wäre.

**Comment by dergel** [comment]
Sehe ich nicht als Prio, weiß auch nicht, ob ich das überhaupt will. Im Moment würde ich das ungern einbauen, weil es relativ viele Änderungen und Updates, Tests von mir  braucht und andere Dinge wichtiger für mich sind. Danke für den Vorschlag.
