### ISSUE TITLE
Doku: YOrm für YCom-Gruppen 

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#358]
Es gibt datasets für ycom-User, jedoch keine für Gruppen. Darf ich hierzu einen PR machen?

- [ ] getUsers
- [ ] getName

**Comment by alxndr-w** [comment]
Ist im Plugin, gerade erst gesehen. Steht nicht in der Doku

**Comment by dergel** [comment]
+ in Doku ergänzen
