### ISSUE TITLE
Stayfield wird ohne 3. Parameter in der Checkbox nicht ausgewertet

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#359]
Slack-Unterhaltung vom 19.05.2021

@ynamite 
>ycom: die Cookie-Laufzeit für "eingeloggt bleiben", funktioniert die korrekt oder hat jemand andere Erfahrungen gemacht? Ich >meine bei mir funktioniert die gar nicht, aber vermutlich mache ich etwas falsch
>
>Im Backend auf 30 Tage eingestellt und im Login-Formular sieht das so aus:
>`$yform->setValueField('checkbox',  ["stayfield", "angemeldet bleiben?"] );`
>muss mich trotzdem täglich neu anmelden (ohne Browser zu schliessen bzw. Cookies zu löschen)

Michael G.
> `$yform->setValueField('checkbox', array("stayfield","angemeldet bleiben?","0"));`
> gib mal noch den dritten Parameter "0" mit .. eventuell macht das etwas aus.

Das hat wohl das Problem gelöst.

An diesen Stellen und davor sieht aber für mich alles richtig aus.

https://github.com/yakamara/redaxo_ycom/blob/1608473e958598dd4d86ff5a93f2de84b438b9a1/plugins/auth/lib/yform/validate/ycom_auth.php#L49

https://github.com/yakamara/redaxo_ycom/blob/1608473e958598dd4d86ff5a93f2de84b438b9a1/plugins/auth/lib/ycom_auth.php#L173

**Comment by ynamite** [comment]
Könnte daran liegen das `0 != null` ist?
P.S. danke für das Issue!

**Comment by alxndr-w** [comment]
Es wird eig. abgefragt und false übergeben. Du könntest im Zweifel ja Mal schauen, ob man null durch 0 ersetzen müsste.

**Comment by ynamite** [comment]
Vielleicht weiss Jan da mehr. Ich dachte wenn ein Param in der Feld-Definition nicht mitgegeben ist, der automatisch `null` ist. Deswegen die Vermutung das null nicht gleich 0 ist. 
Ich teste mal ob's einen Unterschied macht mit `null` ...

**Comment by ynamite** [comment]
Getestet: mit `null` klappt's genauso wie mit `0`.

**Comment by dergel** [comment]
Welche YForm Version .. oder ist das egal ?

**Comment by ynamite** [comment]
In meinem  Fall mit 3.4.2 aber denke es wird auch 4 betreffen.

**Comment by dergel** [comment]
Und wie prüfst du das? Ob ein Cookie gesetzt wird?

**Comment by ynamite** [comment]
Einerseits über die Firefox Dev-Konsole und andererseits auch, weil ich nach kurzer Zeit nicht mehr eingeloggt war.

**Comment by dergel** [comment]
Gerade noch mal getestet. Mit der aktuellen YForm 4 aus github kann ich das nicht nachvollziehen, da scheint es zu klappen. Kann das jemand testen, ob es da auch so ist? Das wäre lieb, habe gerade nicht so viel Zeit. Gerne mich auch in Slack ansprechen.

**Comment by alxndr-w** [comment]
Ich hatte das Verhalten selbst nie beobachtet und kann's daher leider nicht testen, aber @ynamite, du hast es offenkundig noch auf dem Schirm? Könntest du das übernehmen?

**Comment by ynamite** [comment]
Leider gerade extrem unter Druck, werde die nächsten Wochen leider auch kaum dazu kommen.
Wie man's testet ist offensichtlich, gerne jemand anders. Danke.

**Comment by dergel** [comment]
ich schiebe das issue, weil ich das nicht nachvollziehen kann und auch bei anderen bisher nicht. Gerne aber weitermachen, am besten so, dass ich das Szenario nachbauen kann.

**Comment by ynamite** [comment]
Komisch, ich dachte wir hätten damals verifiziert, dass es tatsächlich ein Bug ist (auch seitens Alex, darum hatte er damals auch das Issue eröffnet, statt ich selber. So hab ich das zumindest in Erinnerung).

Leider ist die Unterhaltung nicht mehr auffindbar, da zu lange her ... tja.

**Comment by dergel** [comment]
wir lassen das hier laufen und schauen :)
