### ISSUE TITLE
Passwort vergessen wird verschlüsselt gesendet

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_ycom#36]
Demo Community: Passwort vergessen - sendet per email das verschlüsselte passwort anstelle des unverschlüsselten

**Comment by dergel** [comment]
sollte sowieso nie verschlüsselt versendet werden .. in r5 werden passwörter mit der aktuellen php verschlüsseln gesichert. Passwörter werden incht mehr unverschlüsselt versendet werden können
