### ISSUE TITLE
Nur PHP 8: Umleitungsfehler nach Login

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#360]
Wenn ich meine Installation auf PHP 8 umstelle, erhalte ich nach erfolgreichem YCom Login eine Umleitungsschleife auf den Artikel article_id_jump_ok. 
![Bildschirmfoto von 2021-05-21 08-41-50](https://user-images.githubusercontent.com/4131072/119093871-9101f600-ba10-11eb-893f-44279dcdb6d1.png)
Ändere ich die PHP Version zurück auf 7.4 funktioniert die Umleitung nach erfolgreichem Login auf article_id_jump_ok korrekt.

Der Fehler tritt in allen Browsern auf.

<details>
<summary>System report (REDAXO 5.12.0, PHP 8.0.6, MySQL 5.7.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.6     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.34 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/88.0 |
|      Protocol | HTTP/2.0     |
|         HTTPS | yes          |

| Packages                                         |             |
| -----------------------------------------------: | :---------- |
|                                     accessdenied | 1.0.6       |
|                                         be_style | 2.12.0      |
|                              be_style/customizer | 2.12.0      |
|                                  be_style/redaxo | 2.12.0      |
|                                  consent_manager | 3.0.0beta7  |
|                                          cronjob | 2.8.0       |
|                                      d2u_address | 1.1.3       |
|                                       d2u_helper | 1.8.4       |
|                    d2u_helper/translation_helper | 1.8.4       |
|                                      d2u_history | 1.0.1       |
|                                         d2u_jobs | 1.2.0       |
|                           d2u_jobs/hr4you_import | 1.2.0       |
|                                      d2u_linkbox | 1.2.4       |
|                                    d2u_machinery | 1.3.5       |
|                   d2u_machinery/industry_sectors | 1.3.5       |
|         d2u_machinery/machine_features_extension | 1.3.5       |
| d2u_machinery/machine_steel_processing_extension | 1.3.5       |
|                      d2u_machinery/used_machines | 1.3.5       |
|                                         d2u_news | 1.1.4       |
|                                   d2u_news/fairs | 1.1.4       |
|                                      d2u_partner | 1.0         |
|                                   d2u_references | 1.0.8       |
|                                        d2u_staff | 1.0.3       |
|                                       d2u_videos | 1.1.0       |
|                                          install | 2.9.0       |
|                                    media_manager | 2.11.0      |
|                        media_manager_autorewrite | 2.0.1       |
|                                        mediapool | 2.10.0      |
|                                         metainfo | 2.8.0       |
|                                  multinewsletter | 3.2.7       |
|                                         osmproxy | 1.5.0       |
|                                        phpmailer | 2.10.1      |
|                                        search_it | 6.7.3       |
|                           search_it/autocomplete | 6.7.3       |
|                          search_it/documentation | 6.7.3       |
|                              search_it/plaintext | 6.7.3       |
|                                  search_it/stats | 6.7.3       |
|                                            sprog | 1.2.0       |
|                                        structure | 2.12.0      |
|                                structure/content | 2.12.0      |
|                                         tinymce4 | 1.2.1       |
|                                         uploader | 2.2.2       |
|                                              url | 2.0.0-beta3 |
|                                            users | 2.8.0       |
|                                             ycom | 4.0.3       |
|                                        ycom/auth | 4.0.3       |
|                                        ycom/docs | 4.0.3       |
|                                       ycom/group | 4.0.3       |
|                                  ycom/media_auth | 4.0.3       |
|                                            yform | 3.4.1       |
|                                       yform/docs | 3.3.1       |
|                                      yform/email | 3.4.1       |
|                                    yform/manager | 3.4.1       |
|                            yform_spam_protection | 1.1.0       |
|                                         yrewrite | 2.7         |
|                                  yrewrite_scheme | 3.4.0       |

</details>

**Comment by alxndr-w** [comment]
Der Systemreport passt zu PHP 7.4, außer der Versionsnummer ändert sich da aber im Bericht nichts, oder? (OPCache etc.).

Gibt's was im Log? Kannst du noch in der Browser-Console unter Netzwerk folgende Schritte ausführen (einmal mit PHP 7.4, einmal mit 8.0)

![image](https://user-images.githubusercontent.com/3855487/119100368-294fa900-ba18-11eb-86c7-3324fed69729.png)

1. / 2. aktivieren
3. nur nach Dokumenten filtern
4. bei der initialen Logout-Seite und nach dem 1. Redirect die Header hier reinkopieren, damit wir sie vergleichen können. 

d.h. hier landen dann 4 Header:
7.4 Logout-Ziel, 7.4 Seite nach Redirect,  8.0 Logout-Ziel, 8.0 Seite nach Redirect,

**Comment by TobiasKrais** [comment]
> Der Systemreport passt zu PHP 7.4, außer der Versionsnummer ändert sich da aber im Bericht nichts, oder? (OPCache etc.).

Oh, da hatte ich einen Kopierfehler drin. Ist korrigiert. Es ändert sich nur die Versionsnummer, sonst nichts.

> Gibt's was im Log?

Nein. Leider gähnende Leere.

**Comment by TobiasKrais** [comment]
Hier die Header wenn PHP 8. Zuerst die normale, unausgefüllte Login Seite:
![php8_1-loginseite](https://user-images.githubusercontent.com/4131072/119106623-d0cfda00-ba1e-11eb-9f60-0b5eeb340af8.png)
Jetzt die Header nachdem das Loginformular abgeschickt wurde:
![php8_2-nach_login](https://user-images.githubusercontent.com/4131072/119106637-d2999d80-ba1e-11eb-9f9b-55d35c47daef.png)
Hier haben wir die Weiterleitungsschleife:
![php8_3-schleife](https://user-images.githubusercontent.com/4131072/119106647-d4636100-ba1e-11eb-8aef-ec965f20631b.png)

**Comment by TobiasKrais** [comment]
Hier die Header wenn PHP 7.4. Zuerst die normale, unausgefüllte Login Seite:
![php74_1-loginseite](https://user-images.githubusercontent.com/4131072/119109380-68362c80-ba21-11eb-906c-f626bc9180d4.png)
Jetzt die Header nachdem das Loginformular abgeschickt wurde:
![php74_2-nach_login](https://user-images.githubusercontent.com/4131072/119109428-72582b00-ba21-11eb-95e8-68d704e39f68.png)
Und hier der korrekte Artikel article_id_jump_ok
![php74_3-schleife](https://user-images.githubusercontent.com/4131072/119109438-7421ee80-ba21-11eb-8120-1055c9fdab19.png)

**Comment by alxndr-w** [comment]
Man sieht auf jeden Fall, dass bei PHP8 im Response-Header weiterhin `location;` gesezt ist und es einen 302er als Status zurück gibt.

**Comment by alxndr-w** [comment]
@TobiasKrais hattest du den Fehler weiterhin noch? Könnte es sein, das beim Hoster auf `http` / `https` bzw. `www.` / `non-www` und zurück versucht wird weiterzuleiten?

**Comment by TobiasKrais** [comment]
Ja, der Fehler existiert weiterhin, aber nur unter PHP 8. PHP 7.4 funktioniert alles. Daher denke ich, dass man eine Weiterleitung von Seitens des Hosters ausschließen kann. Anhand des ersten Screenshots kannst du ja sehen, dass das Weiterleitungsziel korrekt wäre, also HTTPS und WWW sind im Weiterleitungsziel korrekt gesetzt.

**Comment by alxndr-w** [comment]
Es gäbe noch die Möglichkeit, den Debug-Modus zu starten in REDAXO (Seite darf nicht live sein) und dann zu schauen, ob bei der Weiterleitung irgendwo eine Notice entsteht. Dazu in der config.yml noch throw_always_exception aktivieren, damit man dadurch der Sache vlt. auf die Spur kommt.

**Comment by TobiasKrais** [comment]
Habs probiert. Leider keine Einträge im Log oder beim Aufruf der Seite.

**Comment by alxndr-w** [comment]
Ich passe, da muss doch noch ein Profi ran.

**Comment by TobiasKrais** [comment]
Danke dir für den Versuch!

**Comment by dergel** [comment]
Ohne es genau zu wissen würde ich dich bitten das noch mal mit der aktuellen Githubversion zu testen. Es gab ein paar falsche Parameter, die eine Schleife verursachen könnten. Das mit den PHP Version ignoriere ich gerade mal. Würde nur gerne wissen, ob sich bei dir mit dieser Version was verändert. Bitte unbedingt bei den Einstellungen auch die Logoutseite eintragen. Die wird nun bei returnTo korrekt ausgeschlossen und sollte keine Schleife mehr bilden.

**Comment by TobiasKrais** [comment]
Leider tritt der Fehler auch in der aktuellen Git Version auf. In den Einstellungen ist die Logout Seite eingetragen.

**Comment by dergel** [comment]
Gerne damit noch mal testen.

**Comment by TobiasKrais** [comment]
Du hast es gelöst! Keine Endlosweiterleitung mehr. Heute bist du mein Held des Tages! Vielen Dank!
