### ISSUE TITLE
Community Seitenrechte werden nicht richtig angezeigt (yform4)

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#362]
Bei den yCom Seitenreichten werden die Felder nicht angezeigt. 
Stattdessen ist die Zeile  `ycom_auth_typeycom_group_typeycom_groups`  zu sehen
Die Felder sind noch Selectfelder die in Choice geändert werden müssen. Gibts schon einen develop Branch dafür? ;-)

Gleiches Problem wie hier:
https://github.com/yakamara/redaxo_yrewrite/issues/415

**Comment by alxndr-w** [comment]
Einfach forken, es braucht dazu keinen devlop-Branch.

1. Forken
2. Lokal eigene branch anlegen
3. Diese branch als PR einreichen

**Comment by marcohanke** [comment]
Natürlich macht ein deploy branch Sinn. Wir stricken jetzt an einer yform4 Optimierung rum und was machen wir wenn es zwischendruch noch einen patch für die aktuelle Version geben soll/kann/muss? Dann hoffen wir das alles läuft, oder zerpflücken den code, oder machen einfach keinen Patch den man einfach machen könnte.
Jan weiß schon für was der Wink gedacht ist

**Comment by alxndr-w** [comment]
> was machen wir wenn es zwischendruch noch einen patch für die aktuelle Version geben soll/kann/muss? 

Das Choice-Feld gibt es nicht erst seit YForm Version 4. Wo ist das Problem?

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_ycom/blob/5b7a4b35b8f4053a9694f3064887611898d9aeef/plugins/auth/pages/content.ycom_auth.php#L23

**Comment by alxndr-w** [comment]
@marcohanke kannst du da auch noch einen PR machen?

**Comment by marcohanke** [comment]
Es bleibt dir unbenommen das selber zu machen. Geht ja bekanntlich schneller als ewig kommentieren

**Comment by alxndr-w** [comment]
Ich bin dir mit #365 entgegengekommen.

**Comment by marcohanke** [comment]
Zu gütig

**Comment by dergel** [comment]
ist hiermit erledigt

https://github.com/yakamara/redaxo_ycom/commit/b7645d6e0e717a74e4e7a4c4d76347dcc8327371

gerne schliessen wenn es passt
