### ISSUE TITLE
ycom_auth_password lässt keine eigenen Rechte zu.

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#363]
Passt man die Rechte an funktioniert zwar das anlegen im Backend, beim Login im Frontend wird aber auf PASSWORD_POLICY_DEFAULT_RULES geprüft. Ich hab hier eine alte DB mit kurzen Passwörtern, die können sich jetzt zwar einloggen bekommen aber trotzdem den Fehler dass das Passwort nicht passt.

**Comment by dergel** [comment]
Wo passt du die Rechte wie an? Möchte das noch besser verstehen

**Comment by marcohanke** [comment]
Ich muss heute sowieso noch eine neue Community installieren und gebe dir dann noch mal ausführlicher Feedback dazu

**Comment by marcohanke** [comment]
Okay, ich glaube ich hab's. Rechte müssen im Frontend und im Backend definiert werden (wie du es gesagt hast) dazu müssen dann natürlich auch die Fehlermeldungen angepasst werden. Verwirrend ist dass:
ycom_validate_password_policy_rules_error = Bitte die Standardregeln beachten mind. 1 Buchstabe groß und klein, mind. 8 Zeichen ist.
An der Stelle weiß ich nicht, ob die Übersetzung über die lang Sinn macht. Ich hatte nämlich eigene Regeln definiert aber trotzdem die Standard Fehlermeldung bekommen.

**Comment by dergel** [comment]
Die Logik sollte passen

- Im Backend kann man eigene Regeln sonst kommen die Defaultregeln
- Im Frontend genauso. Frontend weiß nichts vom Backend, deswegen kann man das nicht übernehmen
- Message gibt es als Defaultübersetzung, sollte man aber immer im Frontend ersetzen, weil clang != Backendlang

Für mich passt alles. Nur in der Doku könnte das noch verständlicher erklärt werden

**Comment by marcohanke** [comment]
Doku übernehme ich.
Ich hätte in dem Fall trotzdem eine Fehlermeldung wie "Fehlermeldung bitte den Passwortregeln anpassen" besser gefunden, komm' aber so auch mit klar.
