### ISSUE TITLE
copy_value nicht mit key=>value möglich

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#367]
Wenn ich das richtig sehe, kann ich hier die Daten nicht  wie gewünscht übergeben weil keine Keys definiert sind.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/issues/372

**Comment by marcohanke** [comment]
Ja man, nachdem du das Repo endlich mal gepushed hast ;-)
