### ISSUE TITLE
Actions auch mit in den Manager übernehmen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#372]
und somit den actions auch definitiojnen geben

tpl2email nicht mit key=>value möglich #370 
db nicht mit key=>value möglich #369 
copy_value #367

**Comment by alxndr-w** [comment]
Mich wundert, dass das bei YCom drin ist. 

Wenn das gerade entscheidend in der Umsetzung ist: Gibt es dann auch eine Möglichkeit, die Action nur fürs Frontend zu aktivieren/definieren.

**Comment by dergel** [comment]
Du hast Recht - habe das verwechselt - gehört zu YForm
