### ISSUE TITLE
Status "Zugang wurde bestätigt und ist aktiv" falsch?

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#373]
Servus, ist der Status tatsächlich so gewünscht?
Wo ist der Unerschied zu "Zugang ist aktiv".

In meinen Augen müsste es eher heißen: "Zugang wurde bestätigt und ist nicht aktiv"
Ich benötige dass für Registrierungen die vom Admin bestätigt werden müssen.
Registrierung wird angefragt = 0
E-Mail wird bestätigt und Mail an admin geht raus = 1
Admin bestätigt den Zugang und Nutzer ist aktiv = 2

Wie setze ich sowas um? Wenn ich es richtig verstehe wird im Moment alles zugelassen was einen Positiven Status hat?

**Comment by dergel** [comment]
Das Vorhandene ist meines Erachtens stimmig. Es gibt nur "unklar/angefragt" mit Status 0 und darüber hat der User nur Zugriff

Willst du den unklaren Status erweitern, musst du eine eigene Checkbox noch nicht reinnehmen und so was wie, E-Mail ist bestätigt ergänzen und deine eigene Logik dazu einbauen.
