### ISSUE TITLE
Seite Einstellungen sollte Authentifizierung->Einstellung aufrufen

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#375]
Aktuell landet man beim Aufrufen der Einstellung auf der Doku.
Dort wird häufig von Einstellungen geschrieben, klickt man im Menü auf Einstellungen landet man auf Doku/Einstellungen.

Schlüssiger wäre als Startseite direkt Auth/Einstellungen aufzurufen.

**Comment by alxndr-w** [comment]
duplicate #376 #398
