### ISSUE TITLE
Benutzer können nur mit Recht ycom[] auf Usertabelle zugreifen

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#379]
Die aktuelle Version 4.0.6 hat ein Rechteproblem: früher habe ich Benutzern die Userverwaltung ermöglicht, indem ich in den Rolleneinstellungen die Usertabelle ausgewählt habe. Aber seit dem letzten Update muss ich zusätzlich das Recht yvom[] geben. Dann kann der Benutzer auch die Einstellungen editieren, was nicht erwünscht ist.

**Comment by alxndr-w** [comment]
Das Problem gibt es auch mit anderen Addons, wo die Tabelle nicht über den Menüpunkt YForm aufgerufen wird.

**Comment by isospin** [comment]
+1

quickfix:
```
if (( rex::isBackend() ) && ( !rex::getUser()->isAdmin()) ) {
    rex_extension::register('PAGES_PREPARED', function (rex_extension_point $ep) {
        $page = rex_be_controller::getPageObject('ycom');
        $page->setHidden(true);
    });
}
```

**Comment by dergel** [comment]
Ich habe das nun anders gelöst. Zunächst kommt nun jeder User mit den Tabellenrechten auch an die Tabellen ran. + ycom[] Perm habe ich entfernt und das nur für den admin[] erlaubt, weil es übergreifende systemrelevante Einstellungen sind.
