### ISSUE TITLE
Comment-Plugin bei mehrsprachigen Webseiten

### ISSUE THREAD

**Issue by d-cz** [yakamara/redaxo_ycom#38]
Das Comment-Plugin unterscheidet im Kommentarschlüssel nur zwischen Seiten-IDs, nicht aber zwischen Sprach-IDs. Das hat bei mehrsprachigen Webseiten zur Folge, daß immer alle Kommentare in sämtlichen Sprachen unter Artikeln mit gleicher Seiten-ID angezeigt werden. 
Deshalb wäre es toll das Plugin so einzurichten, daß der Kommentarschlüssel nicht nur Seiten-IDs, sondern auch Sprach-IDs berücksichtigt. Danke im Vorraus!

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/wiki
