### ISSUE TITLE
ycom_auth_load_user ist zerhackt ;-)

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#380]
Wenn ich ycom_auth_load_user mit Pipes aufrufe werden die Daten zwar geladen,
dumpe ich aber die Klasse, sind die abgefragen values als Label gespeichert uns das label als Klasse
![Bildschirmfoto 2021-09-08 um 11 53 21](https://user-images.githubusercontent.com/2425981/132488219-481e2c4b-4e74-4e04-8c82-92777c750558.png)

**Comment by tyrant88** [comment]
Ersteres ist wohl bei allen yform-values so, die den zweiten Parameter nicht als label nutzen. Weil das hier

**Comment by alxndr-w** [comment]
Ich sehe hier auch kein Label als Klasse.

Hier ist nix zerhackt, nur ein Fleißbienchen-Stempel gäbe es vermutlich dafür, wenn nicht der 2. Parameter, sondern der 3. Parameter hier ausgelesen würde.

https://github.com/yakamara/redaxo_ycom/blob/d5b10b1b155038589cc6d3a7ec7defd7e2a20fc5/plugins/auth/lib/yform/value/ycom_auth_load_user.php#L8-L13

Das wäre dann nicht rückwärtskompatibel und man müsste einen leeren Pipe-Parameter hinzufügen - ich wüsste nicht, ob das ein Gewinn wäre.

M.E. kann man hier zumachen.

**Comment by dergel** [comment]
sieht für mich auch ok aus.
