### ISSUE TITLE
Bei der Installation werden charsets von fremden Tabellen angepasst.

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#381]
Ich bekomme bei der Installation folgenden Fehler:
```
AddOn ycom konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_yf_jobs_activities` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;": SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'BLABLABLA' for key 'activity'
```
Das ist eine Tabelle die nichts mit ycom zu tun hat und sie steht bewusst auf ci weil es dort Texte in Groß und Kleinbuchstaben gibt.

**Comment by dergel** [comment]
sehr sehr seltsam.. Kann ich fast nicht glauben. Ich denke wenn die YCom die eigenen Tabellen importiert und dann die YForm aufgerufen wird, dass dies dann ein allgemeines YForm Tabellen Update durchzieht und das irgendwo bei dir in den Tabellen steht.. Kannst du das mit der neuen YForm nachvollziehen? Mach mal ein allgemeines Tableupdate in YForm und schau mal ob dort das Gleiche passiert. Bis dahin schliesse ich das hier und gerne dann bei YForm aufmachen wenn ich Rechte habe
