### ISSUE TITLE
media_auth Fehler bei Bildern außerhalb des Medienmanagers

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#387]
Ich hab ein Bildtyp mit dem MM-Effekt "Pfad Anpassen". Wenn Media_Auth aktiviert ist, lassen sich die Dateien genau einmal aufrufen, danach habe ich returnTo= im Bildpfad.
Dateien außerhalb des Medienpools sollten also entweder perse aufrufbar sein, oder es sollte irgendwo ein Setting dafür geben um das freizugeben.

**Comment by dergel** [comment]
Da war bisher nicht möglich, da der Herkunftsort in der Medienausgabe nicht mehr erkennbar war. Das ist hier behoben. https://github.com/redaxo/redaxo/pull/5415 Sobald das im REDAXO Core ist, kann man dein obiges Problem so lösen.

```
rex_extension::register(['MEDIA_MANAGER_BEFORE_SEND'], function (rex_extension_point $ep) {
    /** @var rex_media_manager $mm */
    $mm = $ep->getSubject();
    $originalMediaPath = dirname($mm->getMedia()->getSourcePath());
    $deinPfad = '/abcde/';
    if (trim($deinPfad,'/') == trim($originalMediaPath,'/')) {
        $ep->setParam('ycom_ignore', true);        // Wenn alle Dateien für jeden Zugriff haben
       // Ansonsten eigene Logik einbauen.
    }
    return;
}, rex_extension::EARLY);
```

@marcohanke kannst du mir das in der Doku ergönzen + Hinweis, dass dies erst ab wahrscheinlich ab REDAXO 5.15 möglich ist.

**Comment by dergel** [comment]
In der YCom wird nun überprüft, ob der Pfad sich geändert hat und dann wird die YCom Media Auth Überprüfung ausgeschaltet. + in der Doku steht nun, wir man dann seine eigene Authentifizierung einbauen kann.
