### ISSUE TITLE
Fehler beim YCom installieren

### ISSUE THREAD

**Issue by Matze202** [yakamara/redaxo_ycom#391]
Bei der Installation wurde mir folgende Fehlermeldung:
`ErrorException thrown with message "Declaration of rex_yform_value_ycom_auth_password::getDescription() must be compatible with rex_yform_base_abstract::getDescription(): string"

Stacktrace:
#1 ErrorException in /*/redaxo/src/addons/ycom/plugins/auth/lib/yform/value/ycom_auth_password.php:57
#0 rex_error_handler:shutdown in [internal]:0`

Nach der Installation entdeckte ich in der dabei angelegten Tabelle, dass die Spalte 9 doppelt angelegt wurde.

![Fehler-Installation-ycom_auth_password](https://user-images.githubusercontent.com/12160986/147416554-bcec293b-b2dc-4262-9bb2-c100d8fa228f.png)

**Comment by eaCe** [comment]
Welche yForm Version ist denn installiert @Matze202 ? 
yCom ist _noch_ nicht kompatibel mit yForm >4, siehe: https://github.com/yakamara/redaxo_ycom/pull/388

Das Problem mit dem Passwort klingt nach https://github.com/yakamara/redaxo_ycom/issues/364

**Comment by Matze202** [comment]
@eaCe Danke Dir.
Sorry, yForm ist die 4.0.0 Beta7 und yCom 4.0.6
Ich schließe mich da dem anderen von Dir zu letzt gelinkten Issue an, denn es betrifft annähernd das gleiche Problem.

**Comment by clausbde** [comment]
Ich habe bei einer frischen Redaxo-Installation (5.13.2) und ycom 4.0.6 mit 
yform 4.0.2 das gleiche Problem - eigentlich sollte das ja laut Hilfe kompatibel sein.

Declaration of rex_yform_value_ycom_auth_password::getDescription() must be compatible with rex_yform_base_abstract::getDescription(): string

**Comment by eaCe** [comment]
@clausbde bitte die aktuelle Version hier aus Github nutzen.

**Comment by dergel** [comment]
Release ist draussen
