### ISSUE TITLE
YCom - Doku - Anpassungen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#393]
Ein Issue zum sammeln diverser möglicher Anpassungen

-- 

### Datei
`03_login_logout_profile_register.md`

### Abschnitt

**Registrierungs-Formular**

### Anmerkung
Widerspruch:
```
ycom_auth_password|password|Ihr Passwort:*|{"length":{"min":6},"letter":{"min":1},"lowercase":{"min":0},"uppercase":{"min":0},"digit":{"min":1},"symbol":{"min":0}}|Das Passwort muss mindestens 6 Zeichen lang sein und mindestens eine Ziffer enthalten
password|password_2|Passwort bestätigen:*||no_db
```

```
validate|password_policy|password|Passwort muss mindestens 8 Zeichen lang sein und sowohl Gross- als auch Kleinbuchstaben enthalten|
```

-- 

### Datei
`05_passwords.md`

### Abschnitt

**Passwort-Zurücksetzen-Formular**

### Anmerkung

1. 
Die Validierung müsste auf type|email geändert werden.
```
validate|email|email|Bitte geben Sie die E-Mail ein.
```

2.
`pw_change_article_id` ist auf der Seite Authentifizierung im Backend nicht zu finden
```
// bei pw_change_article_id die Id der Passwort-ändern-Seite eintragen
action|redirect|pw_change_article_id
```

**Comment by alxndr-w** [comment]
Wenn es darum geht, würde ich ohnehin andere Standard-Passwörterregeln vorschlagen. Keine Gängelung mit Groß/Kleinschreibung, dafür längere. https://xkcd.com/936/

**Comment by tbaddade** [comment]
> Wenn es darum geht, würde ich ohnehin andere Standard-Passwörterregeln vorschlagen.

Es ging darum, dass im Beispiel des Registrierungsformular der Doku auf zwei Passwortregeln geprüft wird. 

Entweder die Regel bei `ycom_auth_password` löschen oder eben die Validierung auf `password_policy`.

**Comment by lkohlfuerst** [comment]
Eine Ergänzung dazu:

### Datei
`03_login_logout_profile_register.md`

### Abschnitt
**Registrierungs-Formular**

### Anmerkung

`text|email_2|E-Mail bestätigen:*|`

Die Zeile sollte mit einem no_db ergänzt werden, da das Formular sonst einen Fehler wirft:

`text|email_2|E-Mail bestätigen:*||no_db`

**Comment by alxndr-w** [comment]
Siehe PRs

**Comment by dergel** [comment]
Danke @alxndr-w passt alles
