### ISSUE TITLE
Auth : Fehlermeldungen werden nicht angezeigt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#395]
Im Loginformular

```
validate|ycom_auth|login|password|stayfield|warning_message_enterloginpsw|warning_message_login_failed
```

Beispiel findet man in der Doku
https://github.com/yakamara/redaxo_ycom/blob/master/docs/03_login_logout_profile_register.md#login

**Comment by alxndr-w** [comment]
Ist das noch so? Gemäß https://github.com/yakamara/redaxo_ycom/blob/master/plugins/auth/lib/yform/validate/ycom_auth.php sieht's plausibel aus (5. und 6. Parameter, if-Bedingung wirkt logisch)

**Comment by dergel** [comment]
sieht für mich auch schlüssig aus.. Datei wurde auch bereits ein paar Mal seit dem angepasst.
