### ISSUE TITLE
Klick auf Einstellungen öffnet die Doku. 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#398]
Hier erwartet man direkt auf eine Einstellungsseite zu gelangen.

**Comment by alxndr-w** [comment]
@skerbis das Problem wird sein, dass die Einstellungsseite zum Plugin "auth" gehört, die docs aber zum Addon.

Ich habe das Problem auch in einem eigenen Addon und würde mir wünschen, zu erfahren, wie man bei einem installierten Plugin forcieren kann, auf dessen Einstellungsseite zu landen statt auf der vom Eltern-Addon.

**Comment by hirbod** [comment]
Gibt es hierzu einen Workaround? Ich weiss gerade nicht wie ich in die Einstellungen komme

**Comment by hirbod** [comment]
Ok, ich hab die Docs deaktiviert, damit hats geklappt!

**Comment by alxndr-w** [comment]
Duplikat #376
