### ISSUE TITLE
Bitte aktuellen Stand releasen

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#400]
Es häufen Sie Meldungen zu Problemen mit dem aktuellen Release, die hier in der GitHub-Version bereits gelöst sind.

**Comment by alxndr-w** [comment]
Kann ich bestätigen.

**Comment by ascky-thorben** [comment]
+1 ich fange die Issues im REDAXO Repo hierzu ab ;)

**Comment by eaCe** [comment]
Im REDAXO Repo wird auch immer wieder ein Issue erstellt, das würde dem natürlich entgegenwirken ;) 
https://github.com/redaxo/redaxo/issues/4990, https://github.com/redaxo/redaxo/issues/5043, https://github.com/redaxo/redaxo/issues/5088, https://github.com/redaxo/redaxo/issues/5122

**Comment by tema-web** [comment]
Mit der aktuellen GitHub-Version lässt sich Ycom problemlos installieren.

**Comment by brandes-webdesign** [comment]
Ich hatte Anfang des Jahres auch Probleme mit dem Update, habe das aber irgendwie hinbekommen.
Müßte wenn genau nachschauen wie, wenn das hilft?
Aus dem Gedächnis: Ich habe glaube ich aus GitHub die neuste Version genommen und dann hat es geklappt.
