### ISSUE TITLE
media_auth Neue Bilder trotz Berechtigung gesperrt

### ISSUE THREAD

**Issue by ritzfritz** [yakamara/redaxo_ycom#401]
Trotz Zugriffsrecht kein Zugriff auf 2 neue Dateien in /media
Ging bis jetzt immer.
Früher eingebundene werden immer noch angezeigt.

- .htaccess neue gesetzt
- Cache gelöscht
- Rechte in rex_media überprüft (0 0)
- YCom 4.0.6
- yrewrite 2.8.3

**Comment by dergel** [comment]
Auch mit 4.0.7?

**Comment by ritzfritz** [comment]
Grüß Dich Jan,

irgendwie geht’s jetzt wie von „Zauberhand“, nachdem ich mich nach 3 Wochen dem Projekt wieder widmen konnte.

Hätte Dir gern genauere Problembeschreibungen zukommen lassen.

Schöne Grüße

ritzfritz

Von: Jan Kristinus ***@***.***>
Gesendet: Freitag, 29. April 2022 13:22
An: yakamara/redaxo_ycom ***@***.***>
Cc: Fritz Ritzinger ***@***.***>; Author ***@***.***>
Betreff: Re: [yakamara/redaxo_ycom] media_auth Neue Bilder trotz Berechtigung gesperrt (Issue #401)


Auch mit 4.0.7?
