### ISSUE TITLE
"Eingeloggt bleiben" Einstellung wirkungslos

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#402]
Die Einstellung "Eingeloggt bleiben", z.B. 14 Tage, bleibt wirkungslos. 

Vermutlich muss man beim Login `stayfield` mit angeben, falls das so gedacht ist?

Daraus ergeben sich zwei Lösungsoptionen

1. Entweder die Doku aktualisieren, dann bleibt die Einstellung aber irreführend.

oder

2. (Mein Favorit): YCom sollte standardmäßig davon ausgehen, dass "eingeloggt bleiben" erwünscht ist, da es schließlich diese Einstellung im Backend gibt - wünscht man es nicht, so sollte es zum einen dort eine Auswahl-Option geben "deaktiviert", zum anderen könnte man am Formular mit einer Checkbox / einem Hidden-Feld `stayfield`wieder auf 0 setzen.

**Comment by dergel** [comment]
Danke für den Hinweis und die Anregung und ich denke, dass Variante 2 auch meine Vorstellung wäre und sinnvoll klingt.

**Comment by alxndr-w** [comment]
Siehe auch #242

**Comment by dergel** [comment]
Da das Session Handling in Version 4.2 angepasst wird und wir jede einzelne Session tracken werden (wie im Core), wird dann auch dieses Problem gelöst werden. Deswegen -> 4.2

**Comment by dergel** [comment]
ist nun umgesetzt

**Comment by alxndr-w** [comment]
Yippie.
