### ISSUE TITLE
yrewrite -> sitemap.xml ist kein xml??

### ISSUE THREAD

**Issue by oioix** [yakamara/redaxo_ycom#403]
Hi,
bin etwas verwirrt. 
bing weist meine sitemap als fehlerhaft zurück, wobei sämtliche links korrekt angegeben sind.
![Screenshot 2022-05-04 | 15 03 36](https://user-images.githubusercontent.com/75900789/166686876-c95c7d72-dd33-49ee-bab5-d54a98ab1852.jpg)

yrewrite erzeut ja die sitemap.xml dynamisch.
Wenn ich die Sitemap unter https://meinedomain.de/sitemap.xml aufrufe erscheint dort eine wunderschöne Tabelle mit allen Urls, last change, usw. Nur ist diese Seite alles andere als eine xml Datei!
Die Tabelle die auf der sitemap.xml ausgegeben wird, sieht so aus (zeige hier nur den Kopf ohne die URLs) :

![Screenshot 2022-05-04 | 14 50 05](https://user-images.githubusercontent.com/75900789/166685351-df8fd698-c2ac-4d5e-9033-6174932f90f4.jpg)

**Aber eigentlich müsste ja die sitemap.xml so wie z.B. bei Redaxo aussehen:**

![Screenshot 2022-05-04 | 14 50 23](https://user-images.githubusercontent.com/75900789/166685629-3a192b4d-2e39-44a3-a3ad-9e36aac697ed.jpg)

Ich habe keine Einstellungsmöglichkeit gefunden, mit der ich den Output der xml im Backend beinflussen könnte.

Ist das ein Bug oder mache ich etwas falsch?

**Comment by eaCe** [comment]
Das ist nur ein wenig Style-Magie. 
Wenn du deine XML via CURL aufrufst, oder sie in den Netzwerkeinstellungen betrachtest kannst du diese in der Rohform sehen:
![grafik](https://user-images.githubusercontent.com/2708231/166691348-89b761b3-b005-4620-8092-51ab64e89096.png)

**Comment by oioix** [comment]
Danke für den Tipp! Das hilft weiter.

Kann man die Style-Magie irgendwie abschalten?

**Comment by eaCe** [comment]
@oioix das weiß ich leider nicht, alternativ den Seitenquelltext anzeigen lassen.

**Comment by oioix** [comment]
Ja, ist öffentlich. Die Seite läuft unter https ohne www. Alle http- und www.TLD-Anfragen werden über die htaccess sofort auf die https (ohne www) geleitet. Entsprechend enthält die Sitemap auch nur die https-Urls. In yrewrite ist nur die https (ohne www) eingetragen. 
Die Urls sind alle 100% korrekt und auch alle erreichbar, was sich ja auch durch klick auf die Links in der genannten Tabelle sehr leicht checken lässt.

Auch bei google hatte ich mich schon gewundert, dass dort mehrere Urls als "gefunden" aber "nicht in der Sitemap existent" gelistet wurden. Daher versuche ich nun herauszufinden, was die Ursache sein könnte.
bing findet ja gem. dem obigen Screenshot keine der 30 Urls. Nicht einmal die Startseite.

Hast du eventuell einen Tipp wie/wo im Code ich das Styling ausschalten kann? Den Suchmaschinen ist das Styling sicher nicht wichtig. 
Wenn kein Bug (das habe ich verstanden), dann wäre so ein Schalter dann ein Feature Request. ;-)

**Comment by alxndr-w** [comment]
`view-source:https://example.org/sitemap.xml` in deiner Adresszeile eingeben, das genügt dir nicht?

Ansonsten super, dass du das Problem weiter eingrenzen konntest. Ggf. kann ich mir dein Problem Mal direkt anschauen, wenn du mir in Slack per Direktnachricht die URL schickst.

**Comment by oioix** [comment]
Hab gerade nochmal bei google nachgesehen. Dort werden inzwischen alle 30 Urls erkannt und die Sitemap ist als "erfolgreich" gekennzeichnet. google hat die Sitmap am 27.04.22 zuletzt gesehen und bing am 25.04.22. Da hatte sich an den Artikeln bzw. den Urls nichts geändert. 
bing scheint wohl Probleme damit zu haben, google nicht. 

Danke für Dein Angebot. Ich schicke dir mal den Link per Slack.

**Comment by alxndr-w** [comment]
Hab's mir angeschaut. Sieht alles gut aus. Interessant ist, dass Google sich ja deiner Schilderung hat Umstimmen lassen. 

* Hattest du evtl. den Debug-Modus von REDAXO aktiv? 
* Hast du in System und in YRewrite als einen separaten Fehler-Artikel konfiguriert?

**Comment by oioix** [comment]
Vielen Dank fürs nachschauen.  Tja, der Unterschied zwischen bing und google bzgl der Sitemap ist echt rätselhaft.

Nein, den Debug-Modus habe ich auf dieser Domain nie an. Das kann es also nicht sein.
Ja, einen Artikel für die Fehlerseite habe ich angegeben. Die Einstellungen sehen wie folgs aus. 
Eigentlich alles normal und in den Tabs "Alias Domains" und "Weiterleitungen" gibt es keine Einträge.

![Screenshot 2022-05-05 | 09 24 19](https://user-images.githubusercontent.com/75900789/166881252-307616bb-f326-4998-9266-5327d5f538d0.jpg)

**Comment by alxndr-w** [comment]
Und unter "System" - wie sah/sieht es da aus mit dem Fehlerartikel? Nichts verändert?

Mich macht stutzig, dass es bei Google erst nicht ging - und dann doch.

**Comment by oioix** [comment]
In System sieht es genau so aus und die domain ist in yrewrite und system identisch angegeben und endet jeweils mit /

![Screenshot 2022-05-05 | 10 08 05](https://user-images.githubusercontent.com/75900789/166884960-9bcd0123-9987-4916-8647-9bbdb2bc0682.jpg)

Nachdem in den Einstellungen kein Fehler zu finden ist würde ich doch gerne mal das styling in der sitemap.xml abschalten und die sitemap neu einreichen. Auch wenn es kein Bug ist. bing sind immerhin die ehemaligen Entwickler von IE, falls du verstehst was ich meine. ,-)

**Comment by oioix** [comment]
Ich habe gerade noch einmal sämtliche Reiter im bing dashboard durchgesehen.

Es gibt dort eine Meldung, dass meine Startseite (also root) ein einschränkendes robots-tag haben soll.
Das ist aber definitiv nicht der Fall!
Auf Impressum und Datenschutz gibt es ein einschränkendes robots-tag (noindex,nofollow,noarchive), weil diese beiden Seiten nicht im Index landen und schon gar nicht archiviert werden sollen, aber alle anderen öffentlichen Seiten haben (index,follow,noarchive). noarchive ist meines Wissens für die Indexierung unschädlich. index könnte man wohl weglassen, aber auch das ist meines Wissens für die Indexierung unschädlich.

So sieht das bei bing aus und darunter steht dann als betroffene Seite die Url htts://TLD.de/ also die Startseite

![Screenshot 2022-05-05 | 10 21 27](https://user-images.githubusercontent.com/75900789/166887591-6767c224-7ce6-49cc-8483-edc2baa4816e.jpg)

Bei google aber gibt es nichts zu meckern, wie man am folgenden Bild sieht:
![Screenshot 2022-05-05 | 10 28 34](https://user-images.githubusercontent.com/75900789/166887815-763a0458-ca62-4480-9d37-c543a1793b56.jpg)

Auch unter **"Durch "noindex"-Tag ausgeschlossen"** ist bei google alles vollkommen OK!

Ich frage mich nun, ob diese definitiv falsche Fehlermeldung bei bing mit dem Sitemap-Problem zu tun haben könnte. Ich wüsste aber nicht, wie man diese falsche Fehlermeldung be bing abstellen kann, wo es doch kein einschränkendes robots-meta und auch keinen einschränkenden robots header-Eintrag auf der Startseite gibt und auch nie gab.

**Comment by alxndr-w** [comment]
Das mit Impressum / Datenschutz mache ich in der Tat auch so, deswegen kann ich auch da versichern, dass es keine Probleme damit gibt.

Ich kann leider für dich nicht die URLs in BIng testen unter https://www.bing.com/webmasters/crawlcontrol?siteUrl=https://example.org - aber ich schätze, da hast du auch die Info mit dem Robots-Tag her. 

Letztmögliche Ursache kann imho nur sein, dass serverseitig oder programmierseitig irgendwo Bots ausgesperrt werden sollen. Das ist eigentlich nur der Fall, wenn der Debug-Modus aktiv ist (und ein Sicherheitsfeature von REDAXO).

Oder eben war und Bing sich daran verschluckt hat.

Ich denke, da muss es möglich sein, bei Bing nochmal die Sitemap zu entfernen und neu einzureichen in der Hoffnung, dass auch die Indexierung damit neu angestoßen wird.

**Comment by oioix** [comment]
Habe die Stelle in yrewrite gefunden an der das Styling mit minimaler Code-Änderung abgeschaltet werden kann.
Ich habe aus vorgenannten Gründen die Vermutung, dass bing mit dem xml-Styling nicht klarkommt.

Die Stelle im Addon:
yrewrite/lib/yrewrite/seo.php
ab Zeile 262 den Abschnitt:
```
        rex_response::cleanOutputBuffers();
        header('Content-Type: application/xml');
        $content = '<?xml version="1.0" encoding="UTF-8"?>';
        $content .= "\n".'<?xml-stylesheet type="text/xsl" href="assets/addons/yrewrite/xsl-stylesheets/xml-sitemap.xsl"?>';
        $content .= "\n".'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">';
        $content .= implode("\n", $sitemap);
        $content .= "\n".'</urlset>';
        echo $content;
```

ändern in:
```
	$useStyleSheet = false; // <- enable / disable syling of xml output
		
        rex_response::cleanOutputBuffers();
        header('Content-Type: application/xml');
        $content = '<?xml version="1.0" encoding="UTF-8"?>';
        if($useStyleSheet) {
        	$content .= "\n".'<?xml-stylesheet type="text/xsl" href="assets/addons/yrewrite/xsl-stylesheets/xml-sitemap.xsl"?>';
       		$content .= "\n".'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">';
        }
		else $content .= "\n".'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
        $content .= implode("\n", $sitemap);
        $content .= "\n".'</urlset>';
        echo $content;
```

**Ich fände es absolut super, wenn die Abschaltbarkeit des Stylings als neues Feature aufgenommen werden würde.** Es braucht ja nur ein Checbox-Häckchen im Backend damit das dann per Addon config ansteuerbar wird. So hätte der Admin die Chance selbst zu entscheiden, ob er das Styling benötigt, oder darauf verzichten möchte.

Ich werde nun die Sitemap bei Bing ohne xml-Styling neu einreichen und hoffe, dass der Spuk dann vorbei ist. Sehen wir mal. ;-)

Vielen Dank Alex und Thorben!

**Comment by alxndr-w** [comment]
Ich verstehe nach wie vor nicht, wie du auf die Idee kommst, Bing würde die xml visuell lesen und die Optik anschauen. Deswegen möchte ich das auch so nicht unkommentiert stehen lassen.

Mit Mutmaßungen werden sicherlich keine Features hier umgesetzt, behaupte ich Mal.

Ich mache aber gerade die Probe aufs Exempel, habe alle Projekte von der Google Search console importiert und Sitemaps importiert. Bisher wurden alle anstandslos indexiert.

Dein Danke nehme ich in jedem Fall wohlwollend zur Kenntnis. :)

**Comment by eaCe** [comment]
Die Struktur der XML verändert sich nicht durch das Stylesheet. Bing wird die XML wie alle anderen auslesen können.

**Comment by oioix** [comment]
Na, wenn das nicht mal magisch ist:

![Screenshot 2022-05-05 | 14 41 59](https://user-images.githubusercontent.com/75900789/166925322-80413ccf-53c6-46a3-b0ed-70edf0dabcd1.jpg)

Ich denke das spricht für sich. Alle Urls werden nun von bing endeckt!

**Comment by eaCe** [comment]
Wenn dem so ist, hat Bing Probleme :|

**Comment by alxndr-w** [comment]
> Ich denke das spricht für sich. 

Nein.

![Screenshot_20220505-144533458 (1)](https://user-images.githubusercontent.com/3855487/166925807-9555fe7d-065c-4089-a6f4-cba0c00023b3.png)

**Comment by oioix** [comment]
Sorry, bitte nciht falsch verstehen. Mir geht es nicht darum recht haben zu wollen. 
Mir geht es einzig und allein darum indexiert zu werden. Wie ist mir am Ende wurscht, um es mal salopp zu sagen.

**Comment by eaCe** [comment]
Gibt es bei Bing irgendwo eine XML/Sitemap-Validator?

**Comment by oioix** [comment]
Hab da nichts in der Art gesehen. Außer dem Upload selbst eben.

**Comment by oioix** [comment]
Aber hey, was spricht denn dagegen die xml einfach in der Urform zur Verfügung zu stellen. Das ist am Ende immer der sicherste Weg, den man gehen kann. Schließlich kennt keiner den Bing-Algorithmus. Auch ein bing-Programmierer kann mal was übersehen.

Und wenn man für sich selbst die xml zur besseren Übersicht in Schönform sehen will (was ich ja prinzipiell auch nicht schlecht finde) dann könnte man das einfach an einen Backendlogin (Session) oder auch an eine definierte IP binden (gem. Vorbild maintenance-Addon).

**Comment by alxndr-w** [comment]
Die Diskussion ist am Thema vorbei, ich bin hier raus.
