### ISSUE TITLE
Fehler beim YCom installieren

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_ycom#404]
Beim Versuch, die aktuelle yCom 4.0.7 (aus Installer) zu installieren kommt folgender Fehler (auch bei Install über im Safe-Mode):

Declaration of rex_yform_value_ycom_auth_password::getDescription() must be compatible with rex_yform_base_abstract::getDescription(): string

**ErrorException:** Declaration of rex_yform_value_ycom_auth_password::getDescription() must be compatible with rex_yform_base_abstract::getDescription(): string
**File:** redaxo/src/addons/ycom/plugins/auth/lib/yform/value/ycom_auth_password.php
**Line:** 57

Redaxo 5.13.3 mit yForm 4.0.2

**Comment by eaCe** [comment]
Duplikat: https://github.com/yakamara/redaxo_ycom/issues/391

**Comment by alxndr-w** [comment]
1. In den Safe Mode wechseln
2. YCom deaktivieren
3. edit: Safe Mode verlassen
4. YForm updaten
5. YCom updaten
6. YCom aktivieren

Diese Anleitung würde ich mir bitte im Installer wünschen @dergel

**Comment by TobiasKrais** [comment]
Es wäre sehr sinnvoll, wenn wir hier eine Lösung finden. Da kommt im Slack Channel eine Menge Support auf uns zu.

**Comment by dergel** [comment]
Ist in der aktuellsten Version 4.0.11 nun im Installer als Information mit drin, werde ich auch in den nächsten Versionen mit reinschreiben. Danke für die Information und sorry, dass es so spät erst umgesetzt wurde.
