### ISSUE TITLE
Validate-Typ `unique` auf `rex_ycom_user.activation_key` setzen (und damit an der DB-Tabelle)

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ycom#414]
Der Login über den `activation_key` hat nicht funktioniert, weil er (aus welchen Gründen auch immer) mehrfach vorkam. In der Tabellendefinition findet jedoch keine Validierung statt.

**Comment by dergel** [comment]
ich verweise hier einfach mal auf die YForm .. das muss dort gelöst werden. 

https://github.com/yakamara/redaxo_yform/issues/1217

**Comment by alxndr-w** [comment]
Sorry, aber es handelt sich hier um ein anderes Thema. Was du meinst, wäre, dass eine YForm-unique-Validierungsdefinition auch das passende UNIQUE an der DB-Tabelle setzt?

**Comment by dergel** [comment]
oja sorry.. da war ich in Gedanken wohl bei einem anderen Issue. Sorry

**Comment by dergel** [comment]
ist nun drin
