### ISSUE TITLE
Version 4.0.9 bringt REDAXO zum Absturz

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_ycom#422]
Version 4.0.7 funktioniert problemlos, die Beta stürzt auch ab. Folgender Fehler (das ist alles was ich rausfinden konnte):

PHP Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/projekt/redaxo/src/core/lib/autoload.php on line 409

Hab die max_execution_time mal auf 60 erhöht - keine Änderung.

REDAXO Version: 5.14.1
PHP Version: 7.4.32 

Sieht meiner Meinung nach Endlosschleife aus.

**Comment by georgkaser** [comment]
Update: Nach einem Upgrade der PHP Version auf 8.1 nun folgender Fehler:

PHP Fatal error: Declaration of rex_logger::log($level, $message, array $context = [], $file = null, $line = null) must be compatible with Psr\Log\AbstractLogger::log($level, Stringable|string $message, array $context = []): void in /var/www/net_staticpages/redaxo/src/core/lib/util/logger.php on line 86

**Comment by eaCe** [comment]
@georgkaser es kann sein das du irgendwo im Projekt als Vendor Psr\Log nutzt. Daher der zweite Fehler

**Comment by georgkaser** [comment]
Keine Ahnung - ich hab nur ein Update von PHP gemacht und dabei noch den Debug Modus aktiviert. Vielleicht spuckt es deshalb jetzt eine genauere Fehlermeldung aus. Ich mach nochmal ein Downgrade von PHP und schau was da rauskommt...

**Comment by eaCe** [comment]
@georgkaser ich denke es liegt am .tools Ordner in YCom, da ist eine neuere Logger Version drin. Die mag REDAXO aber nicht. .tools sollten nicht im Installer landen. cc @dergel

**Comment by eaCe** [comment]
@georgkaser ich denke es liegt am .tools Ordner in YCom, da ist eine neuere Logger Version drin. Die mag REDAXO aber nicht. .tools sollten nicht im Installer landen. cc @dergel

**Comment by dergel** [comment]
Sollte nun passen. Vendor war bei mir noch lokal vorhanden und wurde beim publishen mit geschickt. Version 4.0.10 hat das behoben

**Comment by georgkaser** [comment]
Danke Jan!

**Comment by georgkaser** [comment]
Blöderweise besteht das Problem immer noch: Ich hab jetzt Version 4.0.10 installiert (vorher den Cache gelöscht und die alte Version gelöscht). Sobald ich auf "System" - "Logdateien" gehe, reagiert das System nicht mehr und es kommt ein 504er. Selbiges passiert wenn ich das Frontend aufrufe.

**Comment by eaCe** [comment]
@georgkaser hast du auch mal geschaut ob in YForm noch ein .tools Ordner liegt?

**Comment by eaCe** [comment]
Hilft es wenn du die psr/log Version im Auth-Plugin auf 1.1.4 setzt?

**Comment by georgkaser** [comment]
Wo mach ich das?

**Comment by eaCe** [comment]
Hm du könntest hier den vendor-Ordner und composer.lock löschen, dann z.B. `composer require psr/log:1.1.4` und danach noch mal `composer install`. Das könnte funktionieren. Oder es kommt doch von einer anderen Stelle :/

**Comment by georgkaser** [comment]
So funktionierts! Du hast's drauf :) Danke.

**Comment by eaCe** [comment]
Prima dann ist das wirklich noch ein Problem. Dazu gibt es auch schon ein weiteres Issue: https://github.com/yakamara/redaxo_ycom/issues/423
