### ISSUE TITLE
returnTo: Parameter bei URL gehen verloren

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_ycom#424]
Bei Zugriff auf eine Seite nur für eingeloggte User, wird man ja automatisch auf die Login-Seite umgeleitet und es wird der returnTo Parameter mit der URL, auf die man sich eigentlich einloggen wollte, gesetzt. Hat diese URL ebenfalls Parameter, gehen diese verloren und es wir nur die URL ohne die Parameter gesetzt (z.B. ?productid=1 bei einem Bestellformular welches nur für eingeloggte User verfügbar ist).

**Comment by georgkaser** [comment]
Kann das jemand prüfen? Oder ist das nur bei mir so?

**Comment by dergel** [comment]
Ja, die Parameter werden nicht übernommen. Das war mal so gewollt, dass nicht irgendwelche Phisinglinks speziellere Aufrufe machen können. Umgehen kannst du es, indem du z.B. Seiten mit productid als komplette URL darstellst - URL AddOn nutzen z.B.

**Comment by dergel** [comment]
Ich will das gerne so belassen. Deswegen schließe ich das Issue
