### ISSUE TITLE
Korrekte Login-Daten aber status < 1 führt nicht mehr auf Fehlerartikel

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_ycom#426]
Im Betreff steht eigentlich schon alles.

Ich habe hier 2 Projekte, eins mit `v4.0.7`, das andere aktuell mit `4.0.11`. Beim ersteren ist es so, dass wenn man sich mit gültigen Login-Daten einloggt, aber der User-Status < 1 ist, man den Fehlerartikel vorgesetzt bekommt.

Beim 2. (`va4.0.11`) wird man stattdessen wieder kommentarlos zum Login zurpckgeschickt.

Thema Sicherheit: Da man bei 2. ja auch keine Fehlermeldung erhält, wie sonst bei falschen Credentials, ist im Grunde so auch recht klar, dass die Login-Daten stimmen. Wenn man penibel ist, ist selbst Variante 1 (`v4.0.7`) kritisch zu sehen, da das umleiten auf den Fehlerartikel genauso ein Abweichen vom üblichen verhalten bei falschen Credentials darstellt.

Ich hab auch keine Ahnung, was hier die beste Lösung ist. Vielleicht sollte man in dem Fall sogar das gleiche Verhalten durchspielen, als wenn der User falsche Login-Daten benutzt hätte. Wenn man dann seine Fehlermeldung noch anpasst, z.B. so ...

```
Die eingegebenen Login-Daten sind ungültig oder Ihr Account-Status erlaubt keinen Zugriff.
```

... dann ist dem Nutzer gar nicht klar, ob er nun Mumpitz eingegeben hat oder sein Account gesperrt ist. Gegen Passwort-Diebstahl, Bruteforce-Gedöns etc. wäre das auch das bessere Verhalten oder? Bin aber auf dem Sektor eher nachlässig und unerfahren ...

**Comment by dergel** [comment]
Bitte mit der aktuellen github-Version testen

**Comment by bitshiftersgmbh** [comment]
Hatte noch keine Zeit für den Test, aber eine Frage die evtl. damit in Zusammenhang steht: Kann es sein, dass `Letzter erfolgreicher Login` auch aktualisiert wird, selbst wenn man sich mit (noch) inaktivem Account und richtigen Credentials einloggt?

**Comment by dergel** [comment]
Wäre ein neues Issue. ```Kann es ein``` bitte ersetzen durch ```nach meinen tests sieht es so aus``` ;) Und bitte mit der aktuellen Version aus github testen.

**Comment by dergel** [comment]
Es gab in Problem, dass man ohne aktiven Status während eines Aufrufes im Skript zu spät richtig geprüft wurde, auf eie nicht erlaubte Seite hätte kommen können, diese dann aber gesperrt ist und der Zugriff erst dort verboten wurden. Kompliziert aber am Ende existiert das nun nicht mehr .. ich denke, dass kann hier diesen Nebeneffekt gehabt haben. Ich kann das obige Problem nicht (mehr) nachvollziehen.
