### ISSUE TITLE
ycom_user eingebettet als Inline-be_manager_relation löscht Passwort

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_ycom#427]
In der Einzel-Ansicht der ycom_user-Table wird das Passwort (Feld-Typ `ycom_auth_password`) ja immer als leer angezeigt, dann beim Speichern des Datensatzes aber nicht als leerer String in die DB geschrieben, sondern bleibt einfach unbeachtet - funktioniert!

Stecken die User in einer (Inline-)`be_manager_relation` einer anderen Table, passiert aber leider genau das. Das Passswort wird als Leerstring in die Datenbank geschrieben und löscht das aktuelle Passwort damit.

![Screenshot 2022-11-27 110415](https://user-images.githubusercontent.com/7023022/204129544-7a5dfc0a-3387-4bc2-a7b6-c9321e96a82d.png)

**Comment by dergel** [comment]
kannst du es damit prüfen und mir eine Info geben?

**Comment by bitshiftersgmbh** [comment]
Mach ich morgen Nachmittag. Danke schon mal!

**Comment by bitshiftersgmbh** [comment]
OK, ich hab gelogen. :P Ich teste es aber auf jeden Fall noch diese Woche! #EHRENWORT!

**Comment by dergel** [comment]
Bin gespannt ;) ich muss schon nachrechnen, was dieses WE dann jetzt ist .. ;) ..

**Comment by bitshiftersgmbh** [comment]
> Bin gespannt ;) ich muss schon nachrechnen, was dieses WE dann jetzt ist .. ;) ..

Bin krank und hab ne perverse Deadline nächste Woche Mittwoch. Ich bitte um noch ein wenig Geduld. 🤒

**Comment by dergel** [comment]
Sollte nun passen
