### ISSUE TITLE
YCom kann nicht im SafeMode installiert werden

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ycom#428]
weil YForm AddOn und die entsprechenden Classes fehlen.

Bessere Fehlermeldungen generieren

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_ycom/issues/404#issuecomment-1118379546

**Comment by eaCe** [comment]
@alxndr-w 404 ist bekannt. Es bezieht sich nur auf den Safemode, dort funktioniert das Vorgehen wohl nicht.

**Comment by alxndr-w** [comment]
@eaCe deswegen ist meine Anleitung im verlinkten Kommentar ja auch, den safe_mode vorher wieder zu aktivieren.

Es würde ja bereits helfen, wenn in der Installer-Beschreibung darauf hingewiesen wird - man muss ja nicht immer ein technisches Problem aus einem Kommunikationsproblem machen.

**Comment by eaCe** [comment]
Sorry total übersehen :)

**Comment by dergel** [comment]
Ich habe vorschnell das Issue geschrieben. Der getestete Fall war anders.

Ich kann im Moment nur nachvollziehen, dass, wenn jemand eine alte YCom installiert hatte, dass diese sich mit einer aktuellen YForm nicht verträgt und deswegen der Prozess mit Safemode aktivieren .. ycom deaktivieren, yform installieren etc durchlaufen muss.

Übersehe ich etwas? @eaCe @alxndr-w

**Comment by alxndr-w** [comment]
Ja. Statt eines Whoops müsste eine Meldung kommen in etwa wie "YCom kann nicht im Safe Mode installiert werden, da YForm dadurch deaktiviert ist."
