### ISSUE TITLE
MediaAuth-Plugin: Komplette Media-Kategorien rekursiv schützen

### ISSUE THREAD

**Issue by danspringer** [yakamara/redaxo_ycom#431]
Anstatt jeder Datei einzeln zuweisen zu müssen, ob sie geschützt ist, wäre es schön, wenn man in den Plugin-Einstellungen wählen könnte, dass ganze Ordner und deren Unterordner geschützt sind

**Comment by dergel** [comment]
Leider sehe ich das hier nicht. Das würde bedeuten, dass es das vorhandene ersetzt und ich sehe auch nicht, dass der Medienpool in dieser Form bestehen bleibt (also so fix auf Kategorien basierend) .. Ich schliesse mal .. 

Aber du solltest das leicht selbst einbauen können.

EP abfangen, Kategorie abfragen und deine Regeln hinterlegen,
