### ISSUE TITLE
YCOM 4.2-beta IP Adresse in der Session-List

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#448]
Ich bin mir nicht sicher, aber ich denke die Anzeige der IP in der Sessionlist im Backend ist ggf. ein DSGVo-Problem. Vor allem wenn mehre Nutzer den gleichen Account verwenden. Das müsste geklärt werden. Ich denke das gilt auch für den Core.

**Comment by dergel** [comment]
Wie bei allen Dingen ist das eine Frage des Anwendungsfalles. Deswegen kann man es auch deaktivieren. Hier geht es um Fehlererkennung und Fehleranalyse. Diese Daten sollten im Normalfall nach kurzer Zeit gelöscht werden. Die Entscheidung, wie jemand damit umgeht und ob und wie es aktiviert wird, liegt beim Entwickler. Der Zugriff ist dem Admin vorenthalten. Das ist ein DSGVO-Thema, aber nur, wenn man diese Daten zur Auswertung nutzt, und nicht regelmäßig löscht. Bei Unsicherheit immer deaktivieren.
