### ISSUE TITLE
Password Feld doppelt nach Update

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#450]
Nach dem Update von  ycom 4.0.6 auf 4.2.0-beta-1 hab ich in rex_ycom_user das Feld `ycom_auth_password` zweimal mit der gleichen ID im TableManager. In der DB ist aber nur ein Feld.
Wenn ich das erste Feld lösche funktioniert alles wieder normal.
Ich hab das lokal und auf einer Staging Instanz so reproduzieren können.

**Comment by eaCe** [comment]
Eventuell das gleiche https://github.com/yakamara/redaxo_ycom/issues/446

**Comment by dergel** [comment]
ich denke auch
