### ISSUE TITLE
auth_facebook install: Felder werden nicht angelegt

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_ycom#53]
Bei der Installation des auth_facebook Plugins werden die notwendigen Felder
- facebookid
- authsource

nicht angelegt. Liegt bestimmt an xForm 4.8 (oder 4.7+). Kann das jemand mal anschauen und beheben? Ich konnte da nicht genau durchsteigen

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/wiki
