### ISSUE TITLE
Community Addon erhöht die Ladezeit von Bildern des ImageManagers stark

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_ycom#57]
Testseite: http://test.kaltenbach.de/de/powerful-solutions/
Benutzername und Passwort sind jeweils "test". Hier mit aktiviertem Community Addon. Ladezeit min. 20 Sekunden wegen der Bilder.

Deaktiviere ich das Community Addon liegt die Ladezeit der Seite bei 3-5 Sekunden.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/wiki
