### ISSUE TITLE
$REX['COM_USER'] nicht gesetzt beim EP IMAGE_MANAGER_INIT

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_ycom#63]
Wenn man Bilder über auth_media absichert, werden die vom Image Manager bearbeiteten Bilder nicht mehr ausgegeben, da der auth EP nach dem EP IMAGE_MANAGER_INIT aufgerufen wird. Das funktioniert leider nicht: #59. Wenn ich bei IMAGE_MANAGER_INIT den Flag REX_EXTENSION_EARLY entferne klappt es. Die EPs müssen also irgendwie in der Reihenfolge angepasst werden.

**Comment by dergel** [comment]
das sollte eigentlich schon behoben worden sein, entweder durch eine änderungen im image_manager oder im community addon. Wenn nciht, dann gerne als Pull Request (auch hier sorry. Nach so langer Zeit kann man sicher nicht mehr erwarten)

https://github.com/yakamara/redaxo_ycom/wiki
