### ISSUE TITLE
Zusätzlicher Extensionpoint beim Newsletterversand

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_ycom#65]
Wäre es möglich, hier (https://github.com/yakamara/redaxo_community/blob/master/plugins/newsletter/pages/index.inc.php#L247) einen zusätzlichen Extension Point einzubinden, um die User-Variablen vor dem Versand zu verändern? 
Damit wäre es z.B. möglich, Passworte für eine größere Gruppe an Nutzern zu setzen und zu versenden, ist z.B. praktisch, wenn einige Nutzer zu einem geschlossenen Bereich (Firmenintranet) einladen möchte.

**Comment by dergel** [comment]
wird hier nicht mehr eingebaut .. in r5 wird ein eigenes newsletter addon entstehen.
