### ISSUE TITLE
Redirect bei Logout will nicht

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_ycom#67]
Zum einen gibt rex_com_auth::login nicht den korrekten Status (3) zurück.
Hierfür muss in der class.rex_com_auth.inc.php in der Zeile 270 eine 3 hin.
auth.php habe ich dann um diese Zeilen ergänzt (Hack):
```
if ($login_status == 3) {
  if ($referer) {
    $redirect = urldecode($referer);
  } else { 
    $redirect = rex_getUrl($REX['ADDON']['community']['plugin_auth']['article_logout']);
    $redirect = $REX['SERVER'].ltrim($redirect,'./');
  }
}
```
Damit funktioniert alles. Ich hab seo42 mit nav42 im Einsatz.

Lg Wolfgang

**Comment by dergel** [comment]
vielen Dank.. 

https://github.com/yakamara/redaxo_ycom/wiki

wenn du das als Pull Request für den redaxo4 branch noch reinlegst wäre das toll (was ich aber nach so langer Zeit nicht erwarten kann)..
