### ISSUE TITLE
auth_media Plugin: Problem bei nachträglicher Installation

### ISSUE THREAD

**Issue by tito-tema** [yakamara/redaxo_ycom#68]
Hi Leute,
habe das Community-Addon samt auth_media nachträglich installiert. Folgendes Problem ist aufgetaucht: jpg-Bilder sowie pdf-Dokumente konnten nicht mehr geöffnet/angezeigt werden.
Abhilfe brachte folgende Lösung: in der Datenbank-Tabelle "rex_file" die neuen Felder "med_com_auth_media_comusers" und "med_com_groups" per sql-Befehl mit dem Inhalt " || " füllen. Anscheinend wird sonst nicht erkannt, dass die Datei ungeschützt ist (wobei auch nicht auf die Login-Seite weitergeleitet wurde).
Sollte mal überarbeitet werden ;-)
Gruß
Tito

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/wiki

Lang ists her .. sorry für die späte Info.
