### ISSUE TITLE
Filebrowser Modul auf Windows-System

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_ycom#69]
Hi, auf Windows-Systemen läuft das Modul nicht, weil die Backslashes im Zielpfad die Ausgabe zerlegen.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/wiki

aber das behalte ich noch als issue als info, sobald das plugin für rex5 adaptiert wird.
