### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_ycom#77]
Bei com_auth_form_login und com_auth_form_password fehlt noch die Möglichkeit, wie bei den anderen Xform-Feldern Placeholder-Texte mit "#placeholder:Passwort" zu definieren.

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/wiki

**Comment by polarpixel** [comment]
Ich meinte hier schon Version 5. Es stimmt, das ist mittlerweile dort eingebaut, aber noch nicht bei ycom_auth_password. Ich eröffne dafür ein neues Issue.
