### ISSUE TITLE
Kein Bootstrap-Markup bei com_auth_form_login und com_auth_form_password

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_ycom#78]
Das Markup für das Bootstrap-Skin greift noch nicht bei com_auth_form_login und com_auth_form_password. Wäre hilfreich zu haben für die geplante Demo ...

**Comment by dergel** [comment]
ist bei rex5 dafür schon so ..

https://github.com/yakamara/redaxo_ycom/wiki
