### ISSUE TITLE
Fehler beim installieren des group Plugins

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_ycom#79]
Beta-2 - folgender Fehler wird geworfen:

```
PlugIn group konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement using params {"table_name":"rex_ycom_group","prio":"1","type_id":"value","type_name":"text","list_hidden":"0","search":"1","name":"name","label":"translate:name","not_required":"","options":"","multiple":"","default":"","size":"","only_empty":"","message":"","table":"","hashname":"","password_hash":"","no_db":"","password_label":"","field":"","type":"","empty_value":"","empty_option":""}! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '")' at line 1
```

Hab die komplette Erweiterung auch mehrmals deinstalliert, gelöscht und die Datenbank Tabellen gelöscht. Zum Schluss noch hier die Master runtergeladen und installiert. Selbes Problem.

EDIT: Beta-3 ebenso

**Comment by Kalle01** [comment]
Kann das Problem bei Beta 3 mit gleicher Fehlermeldung bestätigen. 
@dergel 
Wenn du eine Zugang brauchst melde Dich.
Gruß Kalle

**Comment by Kalle01** [comment]
Witzig, trotz Fehler wurde ein Teil der Tabellen offensichtlich angelegt

**Comment by dergel** [comment]
jein .. wenn sie schon da sind, taucht das problem erst auf.. liegt an yform.. habe die beta6 raus und damit sollte es behoben sein .. freue mich über info

**Comment by Kalle01** [comment]
Nach dem Upgrade von YForm konnte Ycom ohne Probleme installiert werden. 
Danke!
Gruß Kalle

**Comment by dergel** [comment]
danke für die info.

**Comment by georgkaser** [comment]
Yeah, bei mir auch! Danke Jan!
