### ISSUE TITLE
Feature Request Facebook Authentifizierung

### ISSUE THREAD

**Issue by Kalle01** [yakamara/redaxo_ycom#80]
in der alten Community gab es die Facebook Authentifizierung. Es wäre cool, wenn diese auch den Weg in die 5er Version schafft.

**Comment by dergel** [comment]
Hallo Kalle01

das wird kommen. Habe aber noch keinen Termin. Schneller wirds gehen, wenn uns jemand dafür einen Auftrag vergibt .. :)

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_ycom/issues/240
