### ISSUE TITLE
Fehler bei der Installation des GroupPlugin

### ISSUE THREAD

**Issue by Kalle01** [yakamara/redaxo_ycom#81]
Fehler bei der Installation des GroupPlugin:

```
PlugIn group konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_ycom_user` ADD `password` varchar(255) NOT NULL! SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'password'
```

Es wird ein Folder im linken Menübereich angelegt hier sind folgende Fehlermeldungen zu finden:

```
Error while executing statement "SHOW COLUMNS FROM `rex_ycom_group`! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db252992_10.rex_ycom_group' doesn't exist
#0 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/addons/debug/lib/sql_debug.php(23): rex_sql->setQuery('SHOW COLUMNS FR...', Array)
#1 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/core/lib/sql/sql.php(1256): rex_sql_debug->setQuery('SHOW COLUMNS FR...')
#2 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(901): rex_sql::showColumns('rex_ycom_group')
#3 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(572): rex_yform_manager->getDataListQuery(Array, Object(rex_yform_manager_search))
#4 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/addons/yform/plugins/manager/pages/data_edit.php(21): rex_yform_manager->getDataPage()
#5 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/addons/yform/pages/index.php(3): include('/kunden/252992_...')
#6 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/core/lib/packages/package.php(228): include('/kunden/252992_...')
#7 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/core/lib/be/controller.php(444): rex_package->includeFile('pages/index.php', Array)
#8 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/kunden/252992_...')
#9 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/core/backend.php(136): rex_be_controller::includeCurrentPage()
#10 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/src/core/boot.php(105): require('/kunden/252992_...')
#11 /kunden/252992_40822/webseiten/cms-LH-REX-5/redaxo/index.php(9): require('/kunden/252992_...')
#12 {main}
```

**Comment by Kalle01** [comment]
habe eben das Update reingeladen (vorher die Tabelle ycom_group mit PHPMyadmin gelöscht) Fehler ist konstant. 
die angelegte Group Tabelle sieht so aus
![test_ycom](https://cloud.githubusercontent.com/assets/4243589/14187650/54749ffc-f784-11e5-9d56-5ebdb1bf6eb0.JPG)

**Comment by dergel** [comment]
kann ich leider nicht nachvollziehen.. prüf mal ob die yform aktuell ist.

**Comment by dergel** [comment]
auch hier .. wenn nach updates von yform und ycom immernoch der fehler existiert - dann wieder aufmachen

**Comment by Kalle01** [comment]
sorry, habe verpennt den Fehler zu schließen.

**Comment by cukabeka** [comment]
Also ich hatte das biest eben wieder. R5, komplett aktualisierte addons. mit der community demo installiert. ycom group scheint aber nach dem update wieder deaktiviert worden zu sein.

**Comment by cukabeka** [comment]
Update: Die Sache wird komplizierter. Nachdem ich wie im Forum vorgeschlagen das Addon komplett deinstalliert habe (und Yform direkt dazu) und wieder neu installiert + in der Datenbank alle Tabellen zum Thema ycom gelöscht habe, bekomme ich dennoch den hier:

> redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php on line 183
> Fatal error: Call to a member function getFields() on null

oder alternativ 

`redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table_api.php on line 183
Fatal error: Call to a member function getFields() on null`

Das scheint j anoch damit zusammenzuhängen, oder?

**Comment by dergel** [comment]
das sollte nicht mehr so sein.. yform sei dank..
