### ISSUE TITLE
Fehler? 

### ISSUE THREAD

**Issue by Kalle01** [yakamara/redaxo_ycom#82]
![communityfehler](https://cloud.githubusercontent.com/assets/4243589/14144785/7b176c50-f691-11e5-86ce-e3bbd85bfa76.JPG)
Normaler Weise deutet so etwas auf eine nicht korrekte Installation hin. In Zusammenhang mit dem Group plugin bin ich fast sicher...

**Comment by dergel** [comment]
wundert mich auch .. ist bei mir nicht so.. kann aber auch der yform liegen.. beides am besten auf den neuesten stand bringen..

**Comment by dergel** [comment]
ich schliesse das mal .. wenn immernoch ein fehler, trotz update von yform und ycom gerne wieder aufmachen

**Comment by Kalle01** [comment]
sorry, habe verpennt den Fehler zu schließen. Alles Gut!
