### ISSUE TITLE
$amp; in der Registrierungsmail

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#83]
Aus dem hier:

`
echo rex::getServer().rex_getUrl(24,'', 
[
  'rex_ycom_activation_key' => REX_YFORM_DATA[field="activation_key"],
  'rex_ycom_id' => REX_YFORM_DATA[field="ID"]
]); 
'

Wird das:

`http://url.de/?rex_ycom_activation_key=2a5244abe168ba29c6gf52e0edd42a1a&amp;rex_ycom_id=8`

Das **& amp;** sollte ein **&** sein.

LG
Oliver

**Comment by dergel** [comment]
das ist so auch richtig .. in der rex_getUrl kannst du den Trenner definieren.

```
echo rex::getServer().rex_getUrl(24,'',
[
'rex_ycom_activation_key' => REX_YFORM_DATA[field="activation_key"],
'rex_ycom_id' => REX_YFORM_DATA[field="ID"]
],
'&');
';
```

**Comment by olien** [comment]
wieder etwas gelernt. danke!
