### ISSUE TITLE
Warning im Frontend (boot.php)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#84]
Warning: Invalid argument supplied for foreach() in /abc/redaxo/src/addons/ycom/boot.php on line 13

**Comment by staabm** [comment]
Wurde das mit https://github.com/yakamara/redaxo_ycom/commit/819121c61a578be9a4bb74d1ec5a81a97f8a5e8c behoben?

**Comment by olien** [comment]
Ok. Ist so anscheinend nich nicht im installier :-). Danke!

**Comment by staabm** [comment]
Fyi: wenn man den commit anschaut sieht man dass dieser aktuell nur in "master" enthalten ist, d.h. Es gab noch kein release seit der Änderung
