### ISSUE TITLE
Fehler beim Update

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ycom#85]
ycom Update von der letzten auf die aktuelle Version aus dem Installer.

```
"rex_exception" thrown in /kunden/1234/webseiten/rex/redaxo/src/core/lib/api_function.php on line 133
Illegal result returned from api-function install_package_update
#0 /kunden/1234/webseiten/rex/redaxo/src/core/backend.php(132): rex_api_function::handleCall()
#1 /kunden/1234/webseiten/rex/redaxo/src/core/boot.php(105): require('/kunden/252992_...')
#2 /kunden/1234/webseiten/rex/redaxo/index.php(9): require('/kunden/1234...')
#3 {main}
```

Nach dem Verlassen des safe modes und dem Reinstallieren des Addons funktioniert es.

LG
Oliver

**Comment by staabm** [comment]
Hi Oli! Mit welcher version hast du getestet?

**Comment by olien** [comment]
core aktuellste Version aus dem Installer
ycom vorletzte Version aus dem Installer auf die aktuellste Version aus dem Installer (1.0-beta5)

**Comment by dergel** [comment]
sehr seltsam .. kann ich elider nicht nachvollziehen.. gibt es noch jemanden mit diesem problem
