### ISSUE TITLE
Column password already exists

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_ycom#87]
Fehlt nen check bei re-install o.ä.?

```
SQL error: Error while executing statement
 "ALTER TABLE `rex_ycom_user` ADD `password` varchar(255) NOT NULL! SQLSTATE[42S21]: 
Column already exists: 1060 Duplicate column name 'password'
```

Aus http://www.redaxo.org/de/forum/allgemeines-f39/inhalte-vor-nicht-eingeloggten-nutzern-verbergen-t21142.html#p118820

**Comment by dergel** [comment]
sollte nicht mehr passieren. im notfall kann man das plugin deinstallieren und wieder installieren

**Comment by staabm** [comment]
danke
