### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by TrueHatori** [yakamara/redaxo_ycom#88]
Gut, gefunden ;)

> Ich nehme an, Du hast das Feld username bei Dir in der Usertabelle angelegt (mit Yform, nicht direkt in der Datenbank)?
Und Du hast bei den Einstellungen der Community dieses Felds als Login-Feld definiert?

Ja, habe ich gemacht, mit Yform. Auch die validate-Felder (empty und unique). Der username wird in das Feld login kopiert und das ist in den Einstellungen als Login-Feld festgelegt.
Der User wird auch angelegt, die vier Felder, die ausgefüllt sein müssen (aus dem Registrierungsformular), sind drin. Erst nach dem Eintrag kommt der Fehler.
Kann es sein, dass mir irgendwelche Dateien fehlen? Ich hab mal mit der Demo verglichen und da gibt es noch zusätzliche css- und js-Dateien.

Gerade eben hatte ich die Hoffnung, das Problem gefunden zu haben, leider lag ich falsch. Ich war in meiner Datenbank und hab mir die Tabelle dort angesehen. Da stehen alle Felder auf NOT NULL. Nun habe ich aber nicht alle Felder in der Registrierung, die müssten also auf DEFAULT NULL stehen. Habe nun alle Felder entsprechend angepasst und nur die auf NOT NULL stehen lassen, die in der Registrierung ausgefüllt werden müssen (login, username, email, password) und hatte gehofft, das wäre der richtige Weg. Tja, war es aber nicht, leider, ich krieg nach wie vor denselben Fehler :(

**Comment by tbaddade** [comment]
Welcher Fatal Error wird denn angezeigt?

**Comment by TrueHatori** [comment]
Ja, hätte wohl doch den kompletten Beitrag rüberholen sollen. Steht hier:
[https://github.com/FriendsOfREDAXO/demo_community/issues/4](https://github.com/FriendsOfREDAXO/demo_community/issues/4)

Jetzt gehts aber weiter. Da ja der User, den ich registriert habe, eingetragen wurde, hab ich den mal von Hand freigeschalten, damit ich die weiteren Funktionen testen kann. Beim Versuch, mich einzuloggen kommt dann das hier:
`"ErrorException" thrown in /is/htdocs/wp10477139_MJAUB0YEIY/www/ninja4ever/redaxo/src/addons/yform/lib/yform/value/php.php(15) : eval()'d code on line 1
Parse error: syntax error, unexpected '}'`
Ich dreh noch durch mit dem Ding :( :(

**Comment by tbaddade** [comment]
Nichts für ungut, aber wenn ich mir deinen ganzen Beiträge so ansehe, wäre es sinnvoller jemanden mit dem Projekt zu beauftragen.

**Comment by TrueHatori** [comment]
Auf deutsch -> ich bin zu doof. Kann gut sein, man kann nicht alles können. Seltsam nur, dass ich seit gut 20 Jahren mit solchen Sachen arbeite. Es handelt sich hier um meine ganz private HP, ich könnte sie auch auf dem alten System weiterlaufen lassen (für das ich diverse Plugins selber geschrieben habe, nicht nur für meine Seite, auch für etliche andere), wollte aber mal was neues probieren.
Und ich habs weiß Gott nicht nötig, mir sowas sagen zu lassen. So ein Login-System gehört normalerweise ins Core, wird es doch bei 99% der Webseiten gebraucht. Aber gut, man kann es auch als AddOn bringen - für das eine Prozent, dass es nicht braucht.
Ok, ich werde Euch nicht weiter belästigen. Ein schönes System, aber es gibt auch noch andere.

**Comment by phoebusryan** [comment]
Ich möchte mich hier auch mal zu Wort melden, auch wenn ich mich damit möglicherweise zum Feind mache.

@TrueHatori Niemand sagt, dass du zu doof dafür ist. Ich habe aber auch deine Forenbeiträge und deine Issues überall mitgelesen und es ist schon seltsam, dass 90% deiner Probleme nirgendwo sonst auftritt. Für mich kann es dafür eigentlich nur zwei Gründe geben: Entweder ist es ein komplett misskonfigurierter Server, der mit dem Redaxocode nicht klar kommt oder aber es liegt wirklich an dir. Letzteres ist nicht mal böse gemeint, aber du lehnst dich mit deinen Aussagen zum Teil schon weit aus dem Fenster. Zum Beispiel grade "Login gehört in den Core weil 99% gebraucht". Ich habe in den letzten 5 Jahren zwei (!!) gebaut wo ein Loginbereich notwendig war. Und ich baue viele und auch grössere Webseiten. Ich könnte hier also auch den Sinn hinterfragen und dich fragen warum deine _private_ Webseite einen Loginbereich benötigt. Aber es spielt auch keine Rolle.

Grundsätzlich ist sicher jeder aus der Community hilfsbereit und will dir helfen. Das hast du an unseren unzähligen Forenbeiträgen gesehen. Statt aber überall Meldungen zu bringen über nicht funktionierende Funktionen/Addons/Plugins oder was auch immer, würde ich wirklich mal den Grund für die Probleme suchen. Beispiel "Misskonfigurierter Server". Da kann dir niemand wirklich weiterhelfen ausser dein Provider/Serveradmin. Evtl. probierst du es einfach mal mit einem anderen Hoster um dieses Problem auszuschliessen.

Übrigens ist Redaxo inkl. den Addons natürlich auch nicht fehlerfrei aber wir sind sehr bemüht Fehler schnellstmöglichst auszumerzen. Dafür müssen wir das ganze aber reproduzieren können, was wir in den meisten deiner gemeldeten Fälle nicht können. Das macht uns den Support unglaublich schwer. So viel ich weiss hast du auch nie jemandem Zugang gegeben, damit er sich das mal anschauen kann (korrigiere ich mich wenn ich mich täusche).... aber wäre das der Fall gewesen wäre es schnell klar gewesen ob die Probleme vom Server, dem Code oder woher auch immer kommen.

Nimms nicht persönlich aber überlege dir, was du willst und wie du das Ziel erreichst. Ein anderer Server wäre einfach mal eine Überlegung wert.

**Comment by TrueHatori** [comment]
- Ich kann nichts dafür, dass die Fehler nur bei mir auftreten, ich bau sie bestimmt nicht selber ein.

- Ich kenne fast keine Seiten ohne Login, selbst bei Redaxo muss man sich für bestimmte Sachen registrieren und einloggen.

- Ich brauche ein Login, weil ich eine Verantwortung habe. Manche Sachen wie die Technikbeschreibungen sind eben nicht sinnvoll in jedermanns Hand, es laufen zuviele Idioten in dieser Welt rum. Zudem kriegen meine Schüler im Trainingstagebuch nicht nur Lob sondern auch einiges an Kritik - und hat in der Gruppe zu bleiben.

- Dass die Community hilfsbereit ist, weiß ich, das war ein Grund für Redaxo.

Ich hab gestern mal das System im root installiert - es gab nach der Installation von Ycom und Yform Fehlermeldungen über Fehlermeldungen. Aber klar, liegt natürlich auch wieder an meiner Dummheit oder der Blödheit des Hosters (Hosteurope). Seltsam nur, dass alle anderen Systeme, die ich bisher installiert habe, liefen.
Letztendlich auch egal, muss ich eben sehen, wie ich alleine klarkomme. Und nein, ein anderer Server kommt nicht in Frage, ich bin schon sehr lange bei Hosteurope und war immer zufrieden. Wegen eines CMS, sei es noch toll, werde ich den Hoster nicht wechseln.
Es muss auch niemand mehr antworten hier, das Thema ist für mich durch.
Danke

**Comment by polarpixel** [comment]
Ich kann nur ergänzen: An Hosteurope allgemein kann es nicht liegen, ich habe knapp 10 Kunden dort, deren Redaxo-Websites laufen.
Viel Glück jedenfalls für Dich, mit welchem System auch immer!

**Comment by TrueHatori** [comment]
Vielleicht hilft es anderen weiter - irgendwas funktioniert an "mail" nicht. Da ich das Problem bisher nie hatte, bin ich da erst gestern drauf gekommen, mal auf smtp umzustellen. Damit läuft die Registrierung jetzt durch. Einloggen kann ich mich aber nach wie vor nicht, es kommt immer noch der Fehler
`"ErrorException" thrown in /is/htdocs/wp10477139_MJAUB0YEIY/www/ninja4ever/redaxo/src/addons/yform/lib/yform/value/php.php(15) : eval()'d code on line 1 Parse error: syntax error, unexpected '}'`
Das die Meldung Blödsinn ist, weiß ich, das hilft mir aber nicht weiter. Ich hab jetzt alles dutzende Male überprüft und finde keinen Fehler. Sollte ich das Problem noch irgendwie lösen können, sag ich Bescheid.

**Comment by staabm** [comment]
@TrueHatori welche version von yform benutzt Du? hast du manuelle anpassungen in der Datei vorgenommen die hier angemerkt wird?

was liefert ein `php -l /pfad/zur/datei`?

**Comment by TrueHatori** [comment]
PHP - PHP Version 5.6.22
MySQL - 5.5.46
Ycom v 1.0
Alles was ich gemacht hab, steht drin hier.
Mit Konsole komme ich an meinen Webspace nicht dran, kann ich diesen Befehl auch irgendwie in eine Datei schreiben? Und welche Datei genau meinst Du, die aus der Fehlermeldung?
Ach ja, ich hatte probeweise in der php.php in der letzten Zeile das PHP geschlossen, die Datei wird mit <?php angefangen, es gibt aber kein abschließendes ?> .  Hat aber nichts bewirkt, ansonsten hab ich nichts gemacht, auch den Abschluss wieder rückgängig gemacht.

**Comment by staabm** [comment]
PHP Dateien müssen nicht mit `?>` enden. man lässt dies normalerweise weg, da es mehr Fehler bringt und keine Vorteile hat.

Die Fehlermeldung oben sagt aus, dass mit der `php.php` etwas nicht stimmt. am besten du setzt diese zurück auf den stand wie sie im download enthalten war.

**Comment by TrueHatori** [comment]
Wie gesagt, hab ich gemacht, also das ?> wieder entfernt, weiter hatte ich ja nix gemacht damit.
Ich hab mir das Login-Formular mal im Source angeschaut, da sieht die Zeile zum Öffnen des Formulars so aus:
`<form action="./index.php?article_id=18&amp;rex_ycom_auth_ref=" method="post" id="form_formular" class="hide-label" enctype="multipart/form-data">`
Ist das richtig? Oder fehlt da hinter rex_ycom_auth_ref= etwas? Ich weiß es nicht. Wenn was fehlt, dann muss ja in meinem Form was fehlen. Ich hab zwar alles hundert Mal verglichen, aber ... na ja.

**Comment by TrueHatori** [comment]
Abschließend:
Der Oliver Kreische hat es gerade bei mir versucht und grübelt jetzt - es geht gar nichts. Hab ihm ein Verzeichnis und eine Datenbank angelegt und die Zugangsdaten gegeben. Es war zwar "nur" ein Schnellversuch, aber er sagt schon jetzt, sowas ist ihm noch nie untergekommen, es geht wirklich gar nix. Wollte das nur kurz angemerkt haben, mittlerweile dachte ich ja wirklich schon, ich wäre zu doof dafür.

**Comment by olien** [comment]
So. Seite läuft (E-Mails senden nicht aber das ist nicht mein Problem).
Es gibt extrem viele Berechtigungsprobleme (Ordnerrechte, Dateirechte, Benutzerzuordnungen usw.) auf dem Server. Der Import der Demo klappte im System nicht. Drop Table wurde ausgeführt.. dann war Ende und die Tabellen waren weg. Ein manueller Import via phpMyAdmin löste das Problem. Durch die Berechtigungsprobleme wurde der Ressourcen Ordner der Demo nicht angelegt usw... usw...

Ich bin zu wenig Serveradmin um da genauere Infos geben zu können. 
Wie meine pers. Erfahrung zeigt ist es wahrscheinlich am besten Hosteurope zu meiden... 

LG
Oliver

**Comment by staabm** [comment]
Normalerweise werden die dateirechte im setup gechecked. Wurden diese nach beenden des setups nochmal modifiziert?

**Comment by olien** [comment]
Nein. Die Rechte die ich beim Setup gerade gezogen habe haben weiterhin gepasst. Aber bei der Installation von Addons / dem Import der Demo gab es Probleme die ich beim WWW und FTP User Handling vermute.. Kenne mich da zu wenig aus.

**Comment by staabm** [comment]
Ganz konkret: bei welchen ordner/dateien gab es probleme und wie hast du sie aufgelöst?

**Comment by olien** [comment]
Oh mann. Ich hab gut 4 Stunden gebastelt gestern Nacht.... Hab das nicht dokumentiert. Ich denke, dass  das verwunderlichste / schlimmste ist, dass die COM Demo SQL beim Import Tabellen gelöscht hat und dementsprechend abgebrochen wurde. Der Datei Import der Demo hat auch so gar nicht funktioniert...
