### ISSUE TITLE
Passwort automatisch generieren

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#89]
Legt man im Backend einen neuen Benutzer an und es wird kein Passwort angegeben, könnte es automatisch erstellt und gespeichert werden. In der Info-Meldung "Datensatz wurde angelegt" könnte es dann angezeigt werden.

**Comment by dergel** [comment]
ich stelle mir sowas wie einen Passwortgenerator vor.. Javascriptseitig kann man das Passwort bei der Eingabe einsetzen und entsprechend der Regeln ein Passwort generieren lassen.

**Comment by skerbis** [comment]
Sowas? https://simplecodetips.com/password-generator/ 
https://github.com/cosminrr/jQuery-Bootstrap-Password-Generator

**Comment by dergel** [comment]
ist jetzt drin .. man hat einen PasswortCreatorButton mit welchem man ein Passwort mit den passenden Regeln generieren lassen kann.
