### ISSUE TITLE
Passwort ist nicht vorhanden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ycom#90]
Verwendet man den Code zum Passwort ändern aus der Anleitung, so erscheint "Passwort ist nicht vorhanden" als placeholder. Passwort ist aber vorhanden, da bereits erfolgreich eingeloggt.

**Comment by dergel** [comment]
kannst du prüfen ob das immernoch so ist ? hat sich einiges geändert.

**Comment by dergel** [comment]
veraltet - mittlerweile behoben
