### ISSUE TITLE
Wunsch :: Admin sollte im Frontend Zugriff haben

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#91]
Ein Backend-Admin oder -Redakteur sollte sich eine Community-Seite ohne Login anschauen können.

**Comment by tbaddade** [comment]
Den Registrierungs-/Loginprozess will man ja auch prüfen. Da hilft es nicht, wenn man gleich als "eingeloggt" gilt und durch das Frontend gehen kann.

Beschreib doch mal wie du dir das genau vorstellst.

**Comment by skerbis** [comment]
Es geht um den Backend-Admin/oder Redakteur. Sie sollten sich die eingepflegten Seiten ohne Login anzeigen lassen können zur Kontrolle. Es ist schwierig den Redakteuren zu vermitteln, dass Sie sich zunächst in der Community einloggen müssen um die eingepflegten Inhalte zu überprüfen.

**Comment by dergel** [comment]
z.B. "Als User xy einloggen" .. und man wäre direkt eingeloggt - wäre eine Möglichkeit.

**Comment by skerbis** [comment]
Das wäre sehr praktisch @dergel  vor allem auch hinsichtlich des History-Plugins. Aktuell muss für den Versionsvergleich der Backenduser auch im Frontend angemeldet sein, damit er die Versionen vergleichen kann.

**Comment by staabm** [comment]
rein vom wording her nennt man sowas ein "impersonate" feature

**Comment by DavidBruchmann** [comment]
"impersonate"-Login steht aber im Kontrast zu einem Admin Login, weil beim Admin-Login die Sichtbarkeit von Themen nicht individuell angepasst werden kann. Es scheint also um zwei unterschiedliche Ansätze zu gehen, die sich widersprechen bzw. per Bedingungen gegenseitig ausschließen müssen.

**Comment by IngoWinter** [comment]
Ich hab das bei einem aktuellen Projekt so gelöst:
```
// backendnutzer als ycom nutzer einloggen
rex_extension::register('YCOM_AUTH_USER_CHECK', function ($ep) {
    // backendnutzer bei jedem seitenaufruf einloggen (wg ycom benutzerwechsel)
    if (rex::getUser())
    {
        $user_id = rex_get('user_id', 'int', 0);
        if ($user_id)
        {
            $ycom_user = rex_ycom_auth::loginWithParams(['id' => $user_id]);
            if ($ycom_user) {
                return true;
            }
        }
    }
    // eingeloggter ycom nutzer
    if($ep->getSubject()) {
        return true;
    }
    return false;
});
```

**Comment by alexplusde** [comment]
Kann hier @gharlan was beitragen durch die Identitäs-Wechsel-Funktion in REDAXO selbst? Da könnte vlt. gleich die Minibar ihre Stärken ausspielen...

**Comment by skerbis** [comment]
Habe es probiert. Leider funktioniert es nicht mehr so wie Ingo es oben beschrieben hat mit der aktuellen Version. Daher habe ich auch das geplante AddOn bei FOR entfernt.

**Comment by IngoWinter** [comment]
So funktionierts in 4.0.3:
```
rex_extension::register('YCOM_AUTH_USER_CHECK', function ($ep) {
    // backendnutzer bei jedem seitenaufruf einloggen (wg ycom benutzerwechsel)
    if (rex_backend_login::hasSession() && $beUser = rex_backend_login::createUser()) {
        if ($beUser->isAdmin() || $beUser->hasPerm('glaspreis_komplett[]')) {
            $user_id = rex_get('user_id', 'int', 0);
            if ($user_id) {
                $ycom_user = rex_ycom_auth::loginWithParams(['id' => $user_id]);
                if ($ycom_user) {
                    return true;
                }
            }
        }
    }
});
```

**Comment by skerbis** [comment]
Dann versuch ich das doch noch mal.

**Comment by skerbis** [comment]
@IngoWinter Danke. 
https://github.com/FriendsOfREDAXO/ycom_impersonate
Gerne hier weiterhelfen.

**Comment by dergel** [comment]
Ist nun eingebaut.

**Comment by alxndr-w** [comment]
D.h. https://github.com/FriendsOfREDAXO/ycom_impersonate ist obsolet?

**Comment by skerbis** [comment]
@alxndr-w nein

**Comment by dergel** [comment]
Als nicht Admin kann du kein impersonate innerhalb von YCom nutzen. Wenn man das will, müsste man das ycom_impersonate AddOn anpassen.
