### ISSUE TITLE
Passwort / Backend: Passwort stimmt nicht nach Ändern des Users

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#95]
Ändert man Einstellungen des Users wird über das Formular der verschlüsselte Code des Passwortes   gesendet. Im Anschluss stimmt das Passwort nicht mehr und der User kann sich nicht anmelden. 
![bildschirmfoto 2016-08-16 um 17 34 09](https://cloud.githubusercontent.com/assets/791247/17705160/b2437350-63d7-11e6-9d10-c3538d2195be.png)
Als Platzhalter werden auch mehr Punkte dargestellt als das Passwort hat. 
Hier: Test.

**Comment by tbaddade** [comment]
welche YForm Version nutzt du? Ich kann es mit der **Version 1.0** zumindest nicht nachvollziehen. Es erscheint im Passwortfeld **Passwort existiert** als placeholder. Nach dem Aktualisieren steht dann **Passwort wurde nicht aktualisiert**

**Comment by skerbis** [comment]
Ich habe die 1.0 hier - aus dem Installer

**Comment by skerbis** [comment]
![bildschirmfoto 2016-08-16 um 17 47 56](https://cloud.githubusercontent.com/assets/791247/17705711/a1641bbe-63d9-11e6-85a0-4029c7662f49.png)
Sehe auch keinen Placeholde
r

**Comment by skerbis** [comment]
Value müsste eigentlich leer sein? - Oder nicht?

**Comment by dergel** [comment]
müsste leer sein, ja .. hast du das mal mit der yform version 1.1 beta getestet ?

**Comment by skerbis** [comment]
wo finde ich denn die?

**Comment by dergel** [comment]
installer innerhalb von redaxo .. oder die github version hier nehmen

**Comment by skerbis** [comment]
Sorry, habe es überlesen. Yform ist 1.1 beta

**Comment by skerbis** [comment]
![bildschirmfoto 2016-08-17 um 13 41 19](https://cloud.githubusercontent.com/assets/791247/17735025/52c0a9f8-6480-11e6-8c67-ca5e888977c9.png)

**Comment by skerbis** [comment]
habe es jetzt auch noch mit dem aktuellen Stand aus Github versucht. Ohne Besserung

**Comment by skerbis** [comment]
Stimmt hier vielleicht was nicht?
![bildschirmfoto 2016-08-17 um 13 58 39](https://cloud.githubusercontent.com/assets/791247/17735496/c4c85544-6482-11e6-99a1-76b234efc487.png)

**Comment by marcohanke** [comment]
Ich habe die aktuelle CommuntyVersion und die YForm 1.1-beta1 aus dem Installer und damit das gleiche Problem. Mit der Vorversion von YForm aus dem Installer (welche auch immer das war) hat es noch funktioniert!

**Comment by dergel** [comment]
war wirklich ein Problem der YForm. Ist behoben und ist beim nächsten YForm Uüdate behoben

**Comment by marcohanke** [comment]
Wann ist mit dem nächsten Update zu rechnen bzw. welcher Teil des Codes müsste ausgetauscht werden.
So möchte ich meinem Kunden den Zugang nicht freigeben, damit er nichts zerschießt, die Zeit drängt aber.

**Comment by dergel** [comment]
Das dauert nicht mehr allzulange. Aber verstehe bitte, dass ich keine feste Aussage machen möchte ..

das sind noch die Todos:
https://github.com/yakamara/redaxo_yform/milestone/2

**Comment by skerbis** [comment]
@marcohanke Vorschlag: Wenn Du nicht warten kannst:  Erstelle ein Backup und versuch es mal testweise mit dem aktuellen Github-Stand.

**Comment by marcohanke** [comment]
Hallo Skerbis,
danke für die Info. ich hab’ halt etwas Angst, dass ich mir neue Probleme schaffe,
zumal sich aktuell täglich ca. 10 neue Mitglieder in die Community eintragen. Das gäbe dann ein riesiges durcheinander falls ich zurückspielen müsste ….
