### ISSUE TITLE
auth_media

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_ycom#97]
Gibt es Neuigkeiten zu auth_media?
Ist das mittlerweile in Planung bzw. mit wie viel Aufwand ist für die Umsetzung zu rechnen?

Ohne ist die Community für mich eher nutzlos. Was bringt mir ein Login, wenn ich an die Daten auch ohne Login komme?

**Comment by skerbis** [comment]
Hier meine Lösung: https://github.com/FriendsOfREDAXO/tricks/blob/master/ycom_protected_files.md

**Comment by skerbis** [comment]
Es gibt jetzt noch eine 2. Variante: https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_ycom_protected_files_enhanced.md

**Comment by TobiasKrais** [comment]
Danke für die Lösungsvorschläge. Es wäre toll, wenn wir hierfür wieder ein Plugin hätten, wie unter R4. Würde mich auch an der Entwicklung beteiligen.

**Comment by TobiasKrais** [comment]
Ich werde mich in den nächsten Wochen an die Programmierung dieses Plugins machen. Funktionsumfang orientiert sich am auth_media Plugin von Redaxo 4. Wenn ich fertig bin mache ich einen Pull Request und melde mich hier.

**Comment by TobiasKrais** [comment]
An alle Teilnehmer: kann mir jemand bei der Entwicklung mit folgendem Problem weiterhelfen: https://redaxo.org/forum/addons-packages-r5-f43/ycom-auth_media-plugin-brauche-hilfe-fuer-htaccess-t21996.html?

**Comment by TobiasKrais** [comment]
Eine erste lauffähige Version ist jetzt fertig: https://github.com/TobiasKrais/redaxo_ycom/tree/auth_media/plugins/auth_media. Hat jemand Lust zu testen bevor ich einen Pull Request mache?

**Comment by dergel** [comment]
wie schon geschrieben - leider habe ich das irgendwie vergessen/überlesen oder sonstwas und habe nun ein eigenes media_auth geschrieben, was bereits fertig ist, aber erst mit redaxo 5.7. richtig funktioniert und auch yrewrite braucht. Jedes Medium bekommt eigene Rechte, wie auch bei den Artikeln, man kann auch Gruppen zuweisen etc. Sorry für die Doppeltarbeit - aber da es anders funktioniert, wäre es als eigenes AddOn vielleicht auch nicht schlecht

**Comment by TobiasKrais** [comment]
Ich schaue mir deine Lösung in Redaxo 5.7 an. Dann werde ich meine Lösung voraussichtlich einstampfen. Ich bin kein Freund von 2 Lösungen, die im Grunde das selbe anbieten und dann doppelt gepflegt werden müssen. Besser beide arbeiten an deiner Lösung und diese kommt dann weiter voran.

**Comment by skerbis** [comment]
@dergel hast du auch vorgesehen dass man einfach auch nur eine komplette Kategorie schützen kann? Das hat sich als seht praktikabel bei meinen Kunden erwiesen.

**Comment by dergel** [comment]
komplette Kategorie habe ich noch vor, geht aber noch nicht.. Machst du ein Issue ? Ich hätte da auch was zu diskutieren, weil ich mir ja den medienpool eh anders vorstelle und sich dann dieses Thema vielleicht mit schliesst .. tbd

**Comment by dergel** [comment]
@TobiasKrais wirklich sorry, mich selbst würde es nerven wenn ich schon etwas entwickelt hätte und dann kommt einfach nochmal sowas ..

**Comment by TobiasKrais** [comment]
@dergel mach dir nichts draus. Wir sind alle nur Menschen.

**Comment by skerbis** [comment]
https://github.com/yakamara/redaxo_ycom/issues/207

**Comment by TobiasKrais** [comment]
@dergel: ich habe dein Plugin jetzt auf Herz und Nieren getestet. Es funktioniert (fast) sehr gut. Aber es hat einen entscheidenden Nachteil: große Dateien können nicht ausgeliefert werden. Ein Kunde von mir hat viele MP4 Videos, TIF und andere Dateien die mit deiner Lösung gar nicht mehr ausgeliefert werden können. Warum? Die maximale Speichergrenze wird überschritten. In meiner Lösung konnte man den Schutz auf bestimmte Dateitypen begrenzen. Damit blieben die Dateien verfügbar. Was denkst du darüber?

**Comment by dergel** [comment]
dann müssen wir schauen, wie wir den internen Speicher entsprechend begrenzen, damit die allermeisten Dateien ausgeliefert werden. Bei Videos werden sowieso "eigentlich" nur immer Teile durch geschickt, aber das muss erst beim media_manager angepasst werden. Stichwort: HTTP_RANGE..

**Comment by TobiasKrais** [comment]
Was hältst du von der Methode die Authentifizierung über Cookies zu machen. Das habe ich jetzt noch nicht fertig gedacht, aber auf einer Nicht Redaxo Seite habe ich das so gelöst:
`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_URI} ^.*media/.*
RewriteCond %{HTTP_COOKIE} !^.*ycom_is_authorized.*$ [NC]
RewriteRule \.(.*)$ - [F]
</IfModule>`

Soll ich einen eigenen Issue dafür öffnen?

**Comment by dergel** [comment]
mach mal auf und wir diskutieren da weiter

**Comment by TobiasKrais** [comment]
Jep. Hier geht es weiter: https://github.com/yakamara/redaxo_ycom/issues/223
