### ISSUE TITLE
Gruppen / Rechtsverwaltung :: Artikel- / Kategorie-Rechte

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#98]
Für kleine Lösungen ist der Weg der Rechtsvergabe über die Metadaten der Artikel sicher ausreichend. 
Eine Lösung vergleichbar mit der Benutzerverwaltung in Redaxo, wo die einzelnen Kategorien ausgewählt werden können, wäre sicher komfortabler und übersichtlicher.

**Comment by dergel** [comment]
das ist nicht geplant und würde eine komplett andere Richtung vorgeben. Vor allem kann man die Rechte jetzt eigenständig erweitern, z.b. mit Dingen wie IP Range oder ähnlichem. Damit fällt der umgekehrte Weg leider weg.
