### ISSUE TITLE
Letzter Login

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_ycom#99]
<img width="142" alt="bildschirmfoto 2016-08-31 um 19 40 04" src="https://cloud.githubusercontent.com/assets/791247/18139738/f4217380-6fb2-11e6-92a5-b8ce75a7f434.png">
Der Kunde / Redakteur kann mit dem Timestamp nicht viel anfangen

**Comment by dergel** [comment]
nicht ? ;) ..

**Comment by skerbis** [comment]
Hab ihm erklärt wie er es ausrechnen kann ... aber das fand er dann doch etwas kompliziert.

**Comment by staabm** [comment]
wir sollten den timestamp mit http://www.unixtimestamp.com/ verlinken damit man das dort nachschlagen kann ;-)

**Comment by skerbis** [comment]
Es wäre echt nützlich, wenn es ein lesbares Datum wäre. (oder als bubble)

**Comment by dergel** [comment]
klar. mit der neuen yform kann man das entsprechend setzen. sobald die yform draussen ist, mache ich mich an die anpassungen von ycom. dann sollte es wieder passen

**Comment by skerbis** [comment]
wie kann ich das jetzt schon hinbekommen?

**Comment by dergel** [comment]
das ist bereits in der aktuellen github version angepasst.. aber achtung .. braucht yform 2.1 und auch anzahl fehllogins ist eingebaut.
